In [1]:
import warnings

In [2]:
import numpy as np
import pandas as pd

In [3]:
data = pd.read_csv('train.csv')

In [4]:
data

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
0,1000001,P00069042,F,0-17,10,A,2,0,3,NaN,NaN,8370
1,1000001,P00248942,F,0-17,10,A,2,0,1,6.0,14.0,15200
2,1000001,P00087842,F,0-17,10,A,2,0,12,NaN,NaN,1422
3,1000001,P00085442,F,0-17,10,A,2,0,12,14.0,NaN,1057
4,1000002,P00285442,M,55+,16,C,4+,0,8,NaN,NaN,7969
5,1000003,P00193542,M,26-35,15,A,3,0,1,2.0,NaN,15227
6,1000004,P00184942,M,46-50,7,B,2,1,1,8.0,17.0,19215
7,1000004,P00346142,M,46-50,7,B,2,1,1,15.0,NaN,15854
8,1000004,P0097242,M,46-50,7,B,2,1,1,16.0,NaN,15686
9,1000005,P00274942,M,26-35,20,A,1,1,8,NaN,NaN,7871
10,1000005,P00251242,M,26-35,20,A,1,1,5,11.0,NaN,5254
11,1000005,P00014542,M,26-35,20,A,1,1,8,NaN,NaN,3957
12,1000005,P00031342,M,26-35,20,A,1,1,8,NaN,NaN,6073
13,1000005,P00145042,M,26-35,20,A,1,1,1,2.0,5.0,15665
14,1000006,P00231342,F,51-55,9,A,1,0,5,8.0,14.0,5378
15,1000006,P00190242,F,51-55,9,A,1,0,4,5.0,NaN,2079
16,1000006,P0096642,F,51-55,9,A,1,0,2,3.0,4.0,13055
17,1000006,P00058442,F,51-55,9,A,1,0,5,14.0,NaN,8851
18,1000007,P00036842,M,36-45,1,B,1,1,1,14.0,16.0,11788
19,1000008,P00249542,M,26-35,12,C,4+,1,1,5.0,15.0,19614
20,1000008,P00220442,M,26-35,12,C,4+,1,5,14.0,NaN,8584
21,1000008,P00156442,M,26-35,12,C,4+,1,8,NaN,NaN,9872
22,1000008,P00213742,M,26-35,12,C,4+,1,8,NaN,NaN,9743
23,1000008,P00214442,M,26-35,12,C,4+,1,8,NaN,NaN,5982
24,1000008,P00303442,M,26-35,12,C,4+,1,1,8.0,14.0,11927
25,1000009,P00135742,M,26-35,17,C,0,0,6,8.0,NaN,16662
26,1000009,P00039942,M,26-35,17,C,0,0,8,NaN,NaN,5887
27,1000009,P00161442,M,26-35,17,C,0,0,5,14.0,NaN,6973
28,1000009,P00078742,M,26-35,17,C,0,0,5,8.0,14.0,5391
29,1000010,P00085942,F,36-45,1,B,4+,1,2,4.0,8.0,16352
...,...,...,...,...,...,...,...,...,...,...,...,...
550038,1005995,P00375436,F,36-45,1,C,2,1,20,NaN,NaN,596
550039,1005996,P00371644,F,26-35,0,B,1,1,20,NaN,NaN,595
550040,1005997,P00370853,F,26-35,7,A,3,0,19,NaN,NaN,26
550041,1006000,P00371644,M,46-50,17,B,2,1,20,NaN,NaN,488
550042,1006002,P00371644,M,51-55,0,C,1,1,20,NaN,NaN,243
550043,1006003,P00370293,F,46-50,17,C,1,0,19,NaN,NaN,48
550044,1006004,P00370853,F,26-35,15,C,2,0,19,NaN,NaN,62
550045,1006005,P00371644,F,26-35,5,C,2,1,20,NaN,NaN,252
550046,1006006,P00375436,F,0-17,0,C,1,0,20,NaN,NaN,236
550047,1006009,P00372445,F,26-35,12,C,3,0,20,NaN,NaN,244
550048,1006010,P00371644,M,36-45,0,C,1,0,20,NaN,NaN,591
550049,1006011,P00375436,M,36-45,15,C,3,0,20,NaN,NaN,473
550050,1006012,P00371644,M,36-45,15,C,4+,1,20,NaN,NaN,368
550051,1006013,P00375436,F,26-35,20,C,3,0,20,NaN,NaN,489
550052,1006016,P00375436,M,46-50,1,B,1,1,20,NaN,NaN,239
550053,1006017,P00371644,F,36-45,7,B,1,0,20,NaN,NaN,371
550054,1006018,P00370293,M,36-45,1,C,3,0,19,NaN,NaN,60
550055,1006019,P00372445,M,26-35,0,A,4+,0,20,NaN,NaN,238
550056,1006022,P00375436,M,26-35,17,C,4+,0,20,NaN,NaN,254
550057,1006023,P00370853,M,26-35,0,C,2,1,19,NaN,NaN,61
550058,1006024,P00372445,M,26-35,12,A,0,1,20,NaN,NaN,121
550059,1006025,P00370853,F,26-35,1,B,1,0,19,NaN,NaN,48
550060,1006026,P00371644,M,36-45,6,C,1,1,20,NaN,NaN,494
550061,1006029,P00372445,F,26-35,1,C,1,1,20,NaN,NaN,599
550062,1006032,P00372445,M,46-50,7,A,3,0,20,NaN,NaN,473
550063,1006033,P00372445,M,51-55,13,B,1,1,20,NaN,NaN,368
550064,1006035,P00375436,F,26-35,1,C,3,0,20,NaN,NaN,371
550065,1006036,P00375436,F,26-35,15,B,4+,1,20,NaN,NaN,137
550066,1006038,P00375436,F,55+,1,C,2,0,20,NaN,NaN,365
550067,1006039,P00371644,F,46-50,0,B,4+,1,20,NaN,NaN,490

In [5]:
data['Product_Category_2'].fillna(0, inplace=True)
data['Product_Category_3'].fillna(0, inplace=True)

In [6]:
data

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
0,1000001,P00069042,F,0-17,10,A,2,0,3,0.0,0.0,8370
1,1000001,P00248942,F,0-17,10,A,2,0,1,6.0,14.0,15200
2,1000001,P00087842,F,0-17,10,A,2,0,12,0.0,0.0,1422
3,1000001,P00085442,F,0-17,10,A,2,0,12,14.0,0.0,1057
4,1000002,P00285442,M,55+,16,C,4+,0,8,0.0,0.0,7969
5,1000003,P00193542,M,26-35,15,A,3,0,1,2.0,0.0,15227
6,1000004,P00184942,M,46-50,7,B,2,1,1,8.0,17.0,19215
7,1000004,P00346142,M,46-50,7,B,2,1,1,15.0,0.0,15854
8,1000004,P0097242,M,46-50,7,B,2,1,1,16.0,0.0,15686
9,1000005,P00274942,M,26-35,20,A,1,1,8,0.0,0.0,7871
10,1000005,P00251242,M,26-35,20,A,1,1,5,11.0,0.0,5254
11,1000005,P00014542,M,26-35,20,A,1,1,8,0.0,0.0,3957
12,1000005,P00031342,M,26-35,20,A,1,1,8,0.0,0.0,6073
13,1000005,P00145042,M,26-35,20,A,1,1,1,2.0,5.0,15665
14,1000006,P00231342,F,51-55,9,A,1,0,5,8.0,14.0,5378
15,1000006,P00190242,F,51-55,9,A,1,0,4,5.0,0.0,2079
16,1000006,P0096642,F,51-55,9,A,1,0,2,3.0,4.0,13055
17,1000006,P00058442,F,51-55,9,A,1,0,5,14.0,0.0,8851
18,1000007,P00036842,M,36-45,1,B,1,1,1,14.0,16.0,11788
19,1000008,P00249542,M,26-35,12,C,4+,1,1,5.0,15.0,19614
20,1000008,P00220442,M,26-35,12,C,4+,1,5,14.0,0.0,8584
21,1000008,P00156442,M,26-35,12,C,4+,1,8,0.0,0.0,9872
22,1000008,P00213742,M,26-35,12,C,4+,1,8,0.0,0.0,9743
23,1000008,P00214442,M,26-35,12,C,4+,1,8,0.0,0.0,5982
24,1000008,P00303442,M,26-35,12,C,4+,1,1,8.0,14.0,11927
25,1000009,P00135742,M,26-35,17,C,0,0,6,8.0,0.0,16662
26,1000009,P00039942,M,26-35,17,C,0,0,8,0.0,0.0,5887
27,1000009,P00161442,M,26-35,17,C,0,0,5,14.0,0.0,6973
28,1000009,P00078742,M,26-35,17,C,0,0,5,8.0,14.0,5391
29,1000010,P00085942,F,36-45,1,B,4+,1,2,4.0,8.0,16352
...,...,...,...,...,...,...,...,...,...,...,...,...
550038,1005995,P00375436,F,36-45,1,C,2,1,20,0.0,0.0,596
550039,1005996,P00371644,F,26-35,0,B,1,1,20,0.0,0.0,595
550040,1005997,P00370853,F,26-35,7,A,3,0,19,0.0,0.0,26
550041,1006000,P00371644,M,46-50,17,B,2,1,20,0.0,0.0,488
550042,1006002,P00371644,M,51-55,0,C,1,1,20,0.0,0.0,243
550043,1006003,P00370293,F,46-50,17,C,1,0,19,0.0,0.0,48
550044,1006004,P00370853,F,26-35,15,C,2,0,19,0.0,0.0,62
550045,1006005,P00371644,F,26-35,5,C,2,1,20,0.0,0.0,252
550046,1006006,P00375436,F,0-17,0,C,1,0,20,0.0,0.0,236
550047,1006009,P00372445,F,26-35,12,C,3,0,20,0.0,0.0,244
550048,1006010,P00371644,M,36-45,0,C,1,0,20,0.0,0.0,591
550049,1006011,P00375436,M,36-45,15,C,3,0,20,0.0,0.0,473
550050,1006012,P00371644,M,36-45,15,C,4+,1,20,0.0,0.0,368
550051,1006013,P00375436,F,26-35,20,C,3,0,20,0.0,0.0,489
550052,1006016,P00375436,M,46-50,1,B,1,1,20,0.0,0.0,239
550053,1006017,P00371644,F,36-45,7,B,1,0,20,0.0,0.0,371
550054,1006018,P00370293,M,36-45,1,C,3,0,19,0.0,0.0,60
550055,1006019,P00372445,M,26-35,0,A,4+,0,20,0.0,0.0,238
550056,1006022,P00375436,M,26-35,17,C,4+,0,20,0.0,0.0,254
550057,1006023,P00370853,M,26-35,0,C,2,1,19,0.0,0.0,61
550058,1006024,P00372445,M,26-35,12,A,0,1,20,0.0,0.0,121
550059,1006025,P00370853,F,26-35,1,B,1,0,19,0.0,0.0,48
550060,1006026,P00371644,M,36-45,6,C,1,1,20,0.0,0.0,494
550061,1006029,P00372445,F,26-35,1,C,1,1,20,0.0,0.0,599
550062,1006032,P00372445,M,46-50,7,A,3,0,20,0.0,0.0,473
550063,1006033,P00372445,M,51-55,13,B,1,1,20,0.0,0.0,368
550064,1006035,P00375436,F,26-35,1,C,3,0,20,0.0,0.0,371
550065,1006036,P00375436,F,26-35,15,B,4+,1,20,0.0,0.0,137
550066,1006038,P00375436,F,55+,1,C,2,0,20,0.0,0.0,365
550067,1006039,P00371644,F,46-50,0,B,4+,1,20,0.0,0.0,490

In [7]:
data.loc[data['Gender'] == 'F', 'Gender'] = 0
data.loc[data['Gender'] == 'M', 'Gender'] = 1
data.loc[data['Age'] == '0-17', 'Age'] = 0
data.loc[data['Age'] == '18-25', 'Age'] = 1
data.loc[data['Age'] == '26-35', 'Age'] = 2
data.loc[data['Age'] == '36-45', 'Age'] = 3
data.loc[data['Age'] == '46-50', 'Age'] = 4
data.loc[data['Age'] == '51-55', 'Age'] = 5
data.loc[data['Age'] == '55+', 'Age'] = 6

In [8]:
data.loc[data['Stay_In_Current_City_Years'] == '4+', 'Stay_In_Current_City_Years'] = 4
data.loc[data['City_Category'] == 'A', 'City_Category'] = 0
data.loc[data['City_Category'] == 'B', 'City_Category'] = 1
data.loc[data['City_Category'] == 'C', 'City_Category'] = 2

In [9]:
data

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
0,1000001,P00069042,0,0,10,0,2,0,3,0.0,0.0,8370
1,1000001,P00248942,0,0,10,0,2,0,1,6.0,14.0,15200
2,1000001,P00087842,0,0,10,0,2,0,12,0.0,0.0,1422
3,1000001,P00085442,0,0,10,0,2,0,12,14.0,0.0,1057
4,1000002,P00285442,1,6,16,2,4,0,8,0.0,0.0,7969
5,1000003,P00193542,1,2,15,0,3,0,1,2.0,0.0,15227
6,1000004,P00184942,1,4,7,1,2,1,1,8.0,17.0,19215
7,1000004,P00346142,1,4,7,1,2,1,1,15.0,0.0,15854
8,1000004,P0097242,1,4,7,1,2,1,1,16.0,0.0,15686
9,1000005,P00274942,1,2,20,0,1,1,8,0.0,0.0,7871
10,1000005,P00251242,1,2,20,0,1,1,5,11.0,0.0,5254
11,1000005,P00014542,1,2,20,0,1,1,8,0.0,0.0,3957
12,1000005,P00031342,1,2,20,0,1,1,8,0.0,0.0,6073
13,1000005,P00145042,1,2,20,0,1,1,1,2.0,5.0,15665
14,1000006,P00231342,0,5,9,0,1,0,5,8.0,14.0,5378
15,1000006,P00190242,0,5,9,0,1,0,4,5.0,0.0,2079
16,1000006,P0096642,0,5,9,0,1,0,2,3.0,4.0,13055
17,1000006,P00058442,0,5,9,0,1,0,5,14.0,0.0,8851
18,1000007,P00036842,1,3,1,1,1,1,1,14.0,16.0,11788
19,1000008,P00249542,1,2,12,2,4,1,1,5.0,15.0,19614
20,1000008,P00220442,1,2,12,2,4,1,5,14.0,0.0,8584
21,1000008,P00156442,1,2,12,2,4,1,8,0.0,0.0,9872
22,1000008,P00213742,1,2,12,2,4,1,8,0.0,0.0,9743
23,1000008,P00214442,1,2,12,2,4,1,8,0.0,0.0,5982
24,1000008,P00303442,1,2,12,2,4,1,1,8.0,14.0,11927
25,1000009,P00135742,1,2,17,2,0,0,6,8.0,0.0,16662
26,1000009,P00039942,1,2,17,2,0,0,8,0.0,0.0,5887
27,1000009,P00161442,1,2,17,2,0,0,5,14.0,0.0,6973
28,1000009,P00078742,1,2,17,2,0,0,5,8.0,14.0,5391
29,1000010,P00085942,0,3,1,1,4,1,2,4.0,8.0,16352
...,...,...,...,...,...,...,...,...,...,...,...,...
550038,1005995,P00375436,0,3,1,2,2,1,20,0.0,0.0,596
550039,1005996,P00371644,0,2,0,1,1,1,20,0.0,0.0,595
550040,1005997,P00370853,0,2,7,0,3,0,19,0.0,0.0,26
550041,1006000,P00371644,1,4,17,1,2,1,20,0.0,0.0,488
550042,1006002,P00371644,1,5,0,2,1,1,20,0.0,0.0,243
550043,1006003,P00370293,0,4,17,2,1,0,19,0.0,0.0,48
550044,1006004,P00370853,0,2,15,2,2,0,19,0.0,0.0,62
550045,1006005,P00371644,0,2,5,2,2,1,20,0.0,0.0,252
550046,1006006,P00375436,0,0,0,2,1,0,20,0.0,0.0,236
550047,1006009,P00372445,0,2,12,2,3,0,20,0.0,0.0,244
550048,1006010,P00371644,1,3,0,2,1,0,20,0.0,0.0,591
550049,1006011,P00375436,1,3,15,2,3,0,20,0.0,0.0,473
550050,1006012,P00371644,1,3,15,2,4,1,20,0.0,0.0,368
550051,1006013,P00375436,0,2,20,2,3,0,20,0.0,0.0,489
550052,1006016,P00375436,1,4,1,1,1,1,20,0.0,0.0,239
550053,1006017,P00371644,0,3,7,1,1,0,20,0.0,0.0,371
550054,1006018,P00370293,1,3,1,2,3,0,19,0.0,0.0,60
550055,1006019,P00372445,1,2,0,0,4,0,20,0.0,0.0,238
550056,1006022,P00375436,1,2,17,2,4,0,20,0.0,0.0,254
550057,1006023,P00370853,1,2,0,2,2,1,19,0.0,0.0,61
550058,1006024,P00372445,1,2,12,0,0,1,20,0.0,0.0,121
550059,1006025,P00370853,0,2,1,1,1,0,19,0.0,0.0,48
550060,1006026,P00371644,1,3,6,2,1,1,20,0.0,0.0,494
550061,1006029,P00372445,0,2,1,2,1,1,20,0.0,0.0,599
550062,1006032,P00372445,1,4,7,0,3,0,20,0.0,0.0,473
550063,1006033,P00372445,1,5,13,1,1,1,20,0.0,0.0,368
550064,1006035,P00375436,0,2,1,2,3,0,20,0.0,0.0,371
550065,1006036,P00375436,0,2,15,1,4,1,20,0.0,0.0,137
550066,1006038,P00375436,0,6,1,2,2,0,20,0.0,0.0,365
550067,1006039,P00371644,0,4,0,1,4,1,20,0.0,0.0,490

In [10]:
data['User_Score'] = 0.0

In [11]:
data

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase,User_Score
0,1000001,P00069042,0,0,10,0,2,0,3,0.0,0.0,8370,0.0
1,1000001,P00248942,0,0,10,0,2,0,1,6.0,14.0,15200,0.0
2,1000001,P00087842,0,0,10,0,2,0,12,0.0,0.0,1422,0.0
3,1000001,P00085442,0,0,10,0,2,0,12,14.0,0.0,1057,0.0
4,1000002,P00285442,1,6,16,2,4,0,8,0.0,0.0,7969,0.0
5,1000003,P00193542,1,2,15,0,3,0,1,2.0,0.0,15227,0.0
6,1000004,P00184942,1,4,7,1,2,1,1,8.0,17.0,19215,0.0
7,1000004,P00346142,1,4,7,1,2,1,1,15.0,0.0,15854,0.0
8,1000004,P0097242,1,4,7,1,2,1,1,16.0,0.0,15686,0.0
9,1000005,P00274942,1,2,20,0,1,1,8,0.0,0.0,7871,0.0
10,1000005,P00251242,1,2,20,0,1,1,5,11.0,0.0,5254,0.0
11,1000005,P00014542,1,2,20,0,1,1,8,0.0,0.0,3957,0.0
12,1000005,P00031342,1,2,20,0,1,1,8,0.0,0.0,6073,0.0
13,1000005,P00145042,1,2,20,0,1,1,1,2.0,5.0,15665,0.0
14,1000006,P00231342,0,5,9,0,1,0,5,8.0,14.0,5378,0.0
15,1000006,P00190242,0,5,9,0,1,0,4,5.0,0.0,2079,0.0
16,1000006,P0096642,0,5,9,0,1,0,2,3.0,4.0,13055,0.0
17,1000006,P00058442,0,5,9,0,1,0,5,14.0,0.0,8851,0.0
18,1000007,P00036842,1,3,1,1,1,1,1,14.0,16.0,11788,0.0
19,1000008,P00249542,1,2,12,2,4,1,1,5.0,15.0,19614,0.0
20,1000008,P00220442,1,2,12,2,4,1,5,14.0,0.0,8584,0.0
21,1000008,P00156442,1,2,12,2,4,1,8,0.0,0.0,9872,0.0
22,1000008,P00213742,1,2,12,2,4,1,8,0.0,0.0,9743,0.0
23,1000008,P00214442,1,2,12,2,4,1,8,0.0,0.0,5982,0.0
24,1000008,P00303442,1,2,12,2,4,1,1,8.0,14.0,11927,0.0
25,1000009,P00135742,1,2,17,2,0,0,6,8.0,0.0,16662,0.0
26,1000009,P00039942,1,2,17,2,0,0,8,0.0,0.0,5887,0.0
27,1000009,P00161442,1,2,17,2,0,0,5,14.0,0.0,6973,0.0
28,1000009,P00078742,1,2,17,2,0,0,5,8.0,14.0,5391,0.0
29,1000010,P00085942,0,3,1,1,4,1,2,4.0,8.0,16352,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
550038,1005995,P00375436,0,3,1,2,2,1,20,0.0,0.0,596,0.0
550039,1005996,P00371644,0,2,0,1,1,1,20,0.0,0.0,595,0.0
550040,1005997,P00370853,0,2,7,0,3,0,19,0.0,0.0,26,0.0
550041,1006000,P00371644,1,4,17,1,2,1,20,0.0,0.0,488,0.0
550042,1006002,P00371644,1,5,0,2,1,1,20,0.0,0.0,243,0.0
550043,1006003,P00370293,0,4,17,2,1,0,19,0.0,0.0,48,0.0
550044,1006004,P00370853,0,2,15,2,2,0,19,0.0,0.0,62,0.0
550045,1006005,P00371644,0,2,5,2,2,1,20,0.0,0.0,252,0.0
550046,1006006,P00375436,0,0,0,2,1,0,20,0.0,0.0,236,0.0
550047,1006009,P00372445,0,2,12,2,3,0,20,0.0,0.0,244,0.0
550048,1006010,P00371644,1,3,0,2,1,0,20,0.0,0.0,591,0.0
550049,1006011,P00375436,1,3,15,2,3,0,20,0.0,0.0,473,0.0
550050,1006012,P00371644,1,3,15,2,4,1,20,0.0,0.0,368,0.0
550051,1006013,P00375436,0,2,20,2,3,0,20,0.0,0.0,489,0.0
550052,1006016,P00375436,1,4,1,1,1,1,20,0.0,0.0,239,0.0
550053,1006017,P00371644,0,3,7,1,1,0,20,0.0,0.0,371,0.0
550054,1006018,P00370293,1,3,1,2,3,0,19,0.0,0.0,60,0.0
550055,1006019,P00372445,1,2,0,0,4,0,20,0.0,0.0,238,0.0
550056,1006022,P00375436,1,2,17,2,4,0,20,0.0,0.0,254,0.0
550057,1006023,P00370853,1,2,0,2,2,1,19,0.0,0.0,61,0.0
550058,1006024,P00372445,1,2,12,0,0,1,20,0.0,0.0,121,0.0
550059,1006025,P00370853,0,2,1,1,1,0,19,0.0,0.0,48,0.0
550060,1006026,P00371644,1,3,6,2,1,1,20,0.0,0.0,494,0.0
550061,1006029,P00372445,0,2,1,2,1,1,20,0.0,0.0,599,0.0
550062,1006032,P00372445,1,4,7,0,3,0,20,0.0,0.0,473,0.0
550063,1006033,P00372445,1,5,13,1,1,1,20,0.0,0.0,368,0.0
550064,1006035,P00375436,0,2,1,2,3,0,20,0.0,0.0,371,0.0
550065,1006036,P00375436,0,2,15,1,4,1,20,0.0,0.0,137,0.0
550066,1006038,P00375436,0,6,1,2,2,0,20,0.0,0.0,365,0.0
550067,1006039,P00371644,0,4,0,1,4,1,20,0.0,0.0,490,0.0

In [22]:
required_user_data = data[['User_ID', 'Purchase', 'User_Score']]

In [23]:
required_user_data

        User_ID  Purchase  User_Score
0       1000001      8370         0.0
1       1000001     15200         0.0
2       1000001      1422         0.0
3       1000001      1057         0.0
4       1000002      7969         0.0
5       1000003     15227         0.0
6       1000004     19215         0.0
7       1000004     15854         0.0
8       1000004     15686         0.0
9       1000005      7871         0.0
10      1000005      5254         0.0
11      1000005      3957         0.0
12      1000005      6073         0.0
13      1000005     15665         0.0
14      1000006      5378         0.0
15      1000006      2079         0.0
16      1000006     13055         0.0
17      1000006      8851         0.0
18      1000007     11788         0.0
19      1000008     19614         0.0
20      1000008      8584         0.0
21      1000008      9872         0.0
22      1000008      9743         0.0
23      1000008      5982         0.0
24      1000008     11927         0.0
25      1000009     16662         0.0
26      1000009      5887         0.0
27      1000009      6973         0.0
28      1000009      5391         0.0
29      1000010     16352         0.0
...         ...       ...         ...
550038  1005995       596         0.0
550039  1005996       595         0.0
550040  1005997        26         0.0
550041  1006000       488         0.0
550042  1006002       243         0.0
550043  1006003        48         0.0
550044  1006004        62         0.0
550045  1006005       252         0.0
550046  1006006       236         0.0
550047  1006009       244         0.0
550048  1006010       591         0.0
550049  1006011       473         0.0
550050  1006012       368         0.0
550051  1006013       489         0.0
550052  1006016       239         0.0
550053  1006017       371         0.0
550054  1006018        60         0.0
550055  1006019       238         0.0
550056  1006022       254         0.0
550057  1006023        61         0.0
550058  1006024       121         0.0
550059  1006025        48         0.0
550060  1006026       494         0.0
550061  1006029       599         0.0
550062  1006032       473         0.0
550063  1006033       368         0.0
550064  1006035       371         0.0
550065  1006036       137         0.0
550066  1006038       365         0.0
550067  1006039       490         0.0

[550068 rows x 3 columns]

In [24]:
grouped_user_data = required_user_data.groupby(['User_ID']).sum()

In [25]:
grouped_user_data = grouped_user_data.reset_index()

In [26]:
grouped_user_data

      User_ID  Purchase  User_Score
0     1000001    334093         0.0
1     1000002    810472         0.0
2     1000003    341635         0.0
3     1000004    206468         0.0
4     1000005    821001         0.0
5     1000006    379930         0.0
6     1000007    234668         0.0
7     1000008    796593         0.0
8     1000009    594099         0.0
9     1000010   2169510         0.0
10    1000011    557023         0.0
11    1000012    120801         0.0
12    1000013    713927         0.0
13    1000014    127629         0.0
14    1000015   1047728         0.0
15    1000016    150490         0.0
16    1000017   1425995         0.0
17    1000018   1979047         0.0
18    1000019   1458069         0.0
19    1000020    185747         0.0
20    1000021    127099         0.0
21    1000022   1279914         0.0
22    1000023   1670998         0.0
23    1000024    720899         0.0
24    1000025    534706         0.0
25    1000026   1606174         0.0
26    1000027    448934         0.0
27    1000028    516560         0.0
28    1000029    696201         0.0
29    1000030    261584         0.0
...       ...       ...         ...
5861  1006011   1198714         0.0
5862  1006012    127920         0.0
5863  1006013    622847         0.0
5864  1006014    528238         0.0
5865  1006015    255812         0.0
5866  1006016   3770970         0.0
5867  1006017    160230         0.0
5868  1006018    975585         0.0
5869  1006019    604563         0.0
5870  1006020    374475         0.0
5871  1006021    709448         0.0
5872  1006022    278257         0.0
5873  1006023   1222210         0.0
5874  1006024    827570         0.0
5875  1006025   1040257         0.0
5876  1006026    490768         0.0
5877  1006027    265201         0.0
5878  1006028    362972         0.0
5879  1006029    157436         0.0
5880  1006030    737361         0.0
5881  1006031    286374         0.0
5882  1006032    517261         0.0
5883  1006033    501843         0.0
5884  1006034    197086         0.0
5885  1006035    956645         0.0
5886  1006036   4116058         0.0
5887  1006037   1119538         0.0
5888  1006038     90034         0.0
5889  1006039    590319         0.0
5890  1006040   1653299         0.0

[5891 rows x 3 columns]

In [27]:
max_purchase = grouped_user_data['Purchase'].max()

In [28]:
max_purchase

10536909

In [30]:
final_user_data = grouped_user_data[['User_ID', 'Purchase', 'User_Score']]

In [31]:
final_user_data = pd.DataFrame(final_user_data)

In [32]:
final_user_data

      User_ID  Purchase  User_Score
0     1000001    334093         0.0
1     1000002    810472         0.0
2     1000003    341635         0.0
3     1000004    206468         0.0
4     1000005    821001         0.0
5     1000006    379930         0.0
6     1000007    234668         0.0
7     1000008    796593         0.0
8     1000009    594099         0.0
9     1000010   2169510         0.0
10    1000011    557023         0.0
11    1000012    120801         0.0
12    1000013    713927         0.0
13    1000014    127629         0.0
14    1000015   1047728         0.0
15    1000016    150490         0.0
16    1000017   1425995         0.0
17    1000018   1979047         0.0
18    1000019   1458069         0.0
19    1000020    185747         0.0
20    1000021    127099         0.0
21    1000022   1279914         0.0
22    1000023   1670998         0.0
23    1000024    720899         0.0
24    1000025    534706         0.0
25    1000026   1606174         0.0
26    1000027    448934         0.0
27    1000028    516560         0.0
28    1000029    696201         0.0
29    1000030    261584         0.0
...       ...       ...         ...
5861  1006011   1198714         0.0
5862  1006012    127920         0.0
5863  1006013    622847         0.0
5864  1006014    528238         0.0
5865  1006015    255812         0.0
5866  1006016   3770970         0.0
5867  1006017    160230         0.0
5868  1006018    975585         0.0
5869  1006019    604563         0.0
5870  1006020    374475         0.0
5871  1006021    709448         0.0
5872  1006022    278257         0.0
5873  1006023   1222210         0.0
5874  1006024    827570         0.0
5875  1006025   1040257         0.0
5876  1006026    490768         0.0
5877  1006027    265201         0.0
5878  1006028    362972         0.0
5879  1006029    157436         0.0
5880  1006030    737361         0.0
5881  1006031    286374         0.0
5882  1006032    517261         0.0
5883  1006033    501843         0.0
5884  1006034    197086         0.0
5885  1006035    956645         0.0
5886  1006036   4116058         0.0
5887  1006037   1119538         0.0
5888  1006038     90034         0.0
5889  1006039    590319         0.0
5890  1006040   1653299         0.0

[5891 rows x 3 columns]

In [33]:
for index, row in final_user_data.iterrows():
    user_score = (float(row['Purchase']) / float(max_purchase))
    final_user_data.set_value(index, 'User_Score', user_score)

/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/ipykernel/__main__.py:3: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
  app.launch_new_instance()

In [34]:
final_user_data

      User_ID  Purchase  User_Score
0     1000001    334093    0.031707
1     1000002    810472    0.076917
2     1000003    341635    0.032423
3     1000004    206468    0.019595
4     1000005    821001    0.077917
5     1000006    379930    0.036057
6     1000007    234668    0.022271
7     1000008    796593    0.075600
8     1000009    594099    0.056383
9     1000010   2169510    0.205896
10    1000011    557023    0.052864
11    1000012    120801    0.011465
12    1000013    713927    0.067755
13    1000014    127629    0.012113
14    1000015   1047728    0.099434
15    1000016    150490    0.014282
16    1000017   1425995    0.135333
17    1000018   1979047    0.187820
18    1000019   1458069    0.138377
19    1000020    185747    0.017628
20    1000021    127099    0.012062
21    1000022   1279914    0.121470
22    1000023   1670998    0.158585
23    1000024    720899    0.068417
24    1000025    534706    0.050746
25    1000026   1606174    0.152433
26    1000027    448934    0.042606
27    1000028    516560    0.049024
28    1000029    696201    0.066073
29    1000030    261584    0.024825
...       ...       ...         ...
5861  1006011   1198714    0.113763
5862  1006012    127920    0.012140
5863  1006013    622847    0.059111
5864  1006014    528238    0.050132
5865  1006015    255812    0.024278
5866  1006016   3770970    0.357882
5867  1006017    160230    0.015207
5868  1006018    975585    0.092587
5869  1006019    604563    0.057376
5870  1006020    374475    0.035539
5871  1006021    709448    0.067330
5872  1006022    278257    0.026408
5873  1006023   1222210    0.115993
5874  1006024    827570    0.078540
5875  1006025   1040257    0.098725
5876  1006026    490768    0.046576
5877  1006027    265201    0.025169
5878  1006028    362972    0.034448
5879  1006029    157436    0.014941
5880  1006030    737361    0.069979
5881  1006031    286374    0.027178
5882  1006032    517261    0.049090
5883  1006033    501843    0.047627
5884  1006034    197086    0.018704
5885  1006035    956645    0.090790
5886  1006036   4116058    0.390632
5887  1006037   1119538    0.106249
5888  1006038     90034    0.008545
5889  1006039    590319    0.056024
5890  1006040   1653299    0.156906

[5891 rows x 3 columns]

In [35]:
for index, row in data.iterrows():
    u_score = final_user_data.loc[final_user_data.User_ID == row['User_ID'], 'User_Score'].values[0]
    data.set_value(index, 'User_Score', u_score)

/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/ipykernel/__main__.py:3: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
  app.launch_new_instance()

In [36]:
data

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase,User_Score
0,1000001,P00069042,0,0,10,0,2,0,3,0.0,0.0,8370,0.031707
1,1000001,P00248942,0,0,10,0,2,0,1,6.0,14.0,15200,0.031707
2,1000001,P00087842,0,0,10,0,2,0,12,0.0,0.0,1422,0.031707
3,1000001,P00085442,0,0,10,0,2,0,12,14.0,0.0,1057,0.031707
4,1000002,P00285442,1,6,16,2,4,0,8,0.0,0.0,7969,0.076917
5,1000003,P00193542,1,2,15,0,3,0,1,2.0,0.0,15227,0.032423
6,1000004,P00184942,1,4,7,1,2,1,1,8.0,17.0,19215,0.019595
7,1000004,P00346142,1,4,7,1,2,1,1,15.0,0.0,15854,0.019595
8,1000004,P0097242,1,4,7,1,2,1,1,16.0,0.0,15686,0.019595
9,1000005,P00274942,1,2,20,0,1,1,8,0.0,0.0,7871,0.077917
10,1000005,P00251242,1,2,20,0,1,1,5,11.0,0.0,5254,0.077917
11,1000005,P00014542,1,2,20,0,1,1,8,0.0,0.0,3957,0.077917
12,1000005,P00031342,1,2,20,0,1,1,8,0.0,0.0,6073,0.077917
13,1000005,P00145042,1,2,20,0,1,1,1,2.0,5.0,15665,0.077917
14,1000006,P00231342,0,5,9,0,1,0,5,8.0,14.0,5378,0.036057
15,1000006,P00190242,0,5,9,0,1,0,4,5.0,0.0,2079,0.036057
16,1000006,P0096642,0,5,9,0,1,0,2,3.0,4.0,13055,0.036057
17,1000006,P00058442,0,5,9,0,1,0,5,14.0,0.0,8851,0.036057
18,1000007,P00036842,1,3,1,1,1,1,1,14.0,16.0,11788,0.022271
19,1000008,P00249542,1,2,12,2,4,1,1,5.0,15.0,19614,0.075600
20,1000008,P00220442,1,2,12,2,4,1,5,14.0,0.0,8584,0.075600
21,1000008,P00156442,1,2,12,2,4,1,8,0.0,0.0,9872,0.075600
22,1000008,P00213742,1,2,12,2,4,1,8,0.0,0.0,9743,0.075600
23,1000008,P00214442,1,2,12,2,4,1,8,0.0,0.0,5982,0.075600
24,1000008,P00303442,1,2,12,2,4,1,1,8.0,14.0,11927,0.075600
25,1000009,P00135742,1,2,17,2,0,0,6,8.0,0.0,16662,0.056383
26,1000009,P00039942,1,2,17,2,0,0,8,0.0,0.0,5887,0.056383
27,1000009,P00161442,1,2,17,2,0,0,5,14.0,0.0,6973,0.056383
28,1000009,P00078742,1,2,17,2,0,0,5,8.0,14.0,5391,0.056383
29,1000010,P00085942,0,3,1,1,4,1,2,4.0,8.0,16352,0.205896
...,...,...,...,...,...,...,...,...,...,...,...,...,...
550038,1005995,P00375436,0,3,1,2,2,1,20,0.0,0.0,596,0.096327
550039,1005996,P00371644,0,2,0,1,1,1,20,0.0,0.0,595,0.286774
550040,1005997,P00370853,0,2,7,0,3,0,19,0.0,0.0,26,0.038885
550041,1006000,P00371644,1,4,17,1,2,1,20,0.0,0.0,488,0.225181
550042,1006002,P00371644,1,5,0,2,1,1,20,0.0,0.0,243,0.174953
550043,1006003,P00370293,0,4,17,2,1,0,19,0.0,0.0,48,0.152510
550044,1006004,P00370853,0,2,15,2,2,0,19,0.0,0.0,62,0.030968
550045,1006005,P00371644,0,2,5,2,2,1,20,0.0,0.0,252,0.035107
550046,1006006,P00375436,0,0,0,2,1,0,20,0.0,0.0,236,0.048868
550047,1006009,P00372445,0,2,12,2,3,0,20,0.0,0.0,244,0.026471
550048,1006010,P00371644,1,3,0,2,1,0,20,0.0,0.0,591,0.183565
550049,1006011,P00375436,1,3,15,2,3,0,20,0.0,0.0,473,0.113763
550050,1006012,P00371644,1,3,15,2,4,1,20,0.0,0.0,368,0.012140
550051,1006013,P00375436,0,2,20,2,3,0,20,0.0,0.0,489,0.059111
550052,1006016,P00375436,1,4,1,1,1,1,20,0.0,0.0,239,0.357882
550053,1006017,P00371644,0,3,7,1,1,0,20,0.0,0.0,371,0.015207
550054,1006018,P00370293,1,3,1,2,3,0,19,0.0,0.0,60,0.092587
550055,1006019,P00372445,1,2,0,0,4,0,20,0.0,0.0,238,0.057376
550056,1006022,P00375436,1,2,17,2,4,0,20,0.0,0.0,254,0.026408
550057,1006023,P00370853,1,2,0,2,2,1,19,0.0,0.0,61,0.115993
550058,1006024,P00372445,1,2,12,0,0,1,20,0.0,0.0,121,0.078540
550059,1006025,P00370853,0,2,1,1,1,0,19,0.0,0.0,48,0.098725
550060,1006026,P00371644,1,3,6,2,1,1,20,0.0,0.0,494,0.046576
550061,1006029,P00372445,0,2,1,2,1,1,20,0.0,0.0,599,0.014941
550062,1006032,P00372445,1,4,7,0,3,0,20,0.0,0.0,473,0.049090
550063,1006033,P00372445,1,5,13,1,1,1,20,0.0,0.0,368,0.047627
550064,1006035,P00375436,0,2,1,2,3,0,20,0.0,0.0,371,0.090790
550065,1006036,P00375436,0,2,15,1,4,1,20,0.0,0.0,137,0.390632
550066,1006038,P00375436,0,6,1,2,2,0,20,0.0,0.0,365,0.008545
550067,1006039,P00371644,0,4,0,1,4,1,20,0.0,0.0,490,0.056024

In [37]:
data.dtypes

User_ID                         int64
Product_ID                     object
Gender                          int64
Age                             int64
Occupation                      int64
City_Category                   int64
Stay_In_Current_City_Years     object
Marital_Status                  int64
Product_Category_1              int64
Product_Category_2            float64
Product_Category_3            float64
Purchase                        int64
User_Score                    float64
dtype: object

In [38]:
data['Stay_In_Current_City_Years'] = data['Stay_In_Current_City_Years'].astype(str).astype(int)

In [39]:
data

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase,User_Score
0,1000001,P00069042,0,0,10,0,2,0,3,0.0,0.0,8370,0.031707
1,1000001,P00248942,0,0,10,0,2,0,1,6.0,14.0,15200,0.031707
2,1000001,P00087842,0,0,10,0,2,0,12,0.0,0.0,1422,0.031707
3,1000001,P00085442,0,0,10,0,2,0,12,14.0,0.0,1057,0.031707
4,1000002,P00285442,1,6,16,2,4,0,8,0.0,0.0,7969,0.076917
5,1000003,P00193542,1,2,15,0,3,0,1,2.0,0.0,15227,0.032423
6,1000004,P00184942,1,4,7,1,2,1,1,8.0,17.0,19215,0.019595
7,1000004,P00346142,1,4,7,1,2,1,1,15.0,0.0,15854,0.019595
8,1000004,P0097242,1,4,7,1,2,1,1,16.0,0.0,15686,0.019595
9,1000005,P00274942,1,2,20,0,1,1,8,0.0,0.0,7871,0.077917
10,1000005,P00251242,1,2,20,0,1,1,5,11.0,0.0,5254,0.077917
11,1000005,P00014542,1,2,20,0,1,1,8,0.0,0.0,3957,0.077917
12,1000005,P00031342,1,2,20,0,1,1,8,0.0,0.0,6073,0.077917
13,1000005,P00145042,1,2,20,0,1,1,1,2.0,5.0,15665,0.077917
14,1000006,P00231342,0,5,9,0,1,0,5,8.0,14.0,5378,0.036057
15,1000006,P00190242,0,5,9,0,1,0,4,5.0,0.0,2079,0.036057
16,1000006,P0096642,0,5,9,0,1,0,2,3.0,4.0,13055,0.036057
17,1000006,P00058442,0,5,9,0,1,0,5,14.0,0.0,8851,0.036057
18,1000007,P00036842,1,3,1,1,1,1,1,14.0,16.0,11788,0.022271
19,1000008,P00249542,1,2,12,2,4,1,1,5.0,15.0,19614,0.075600
20,1000008,P00220442,1,2,12,2,4,1,5,14.0,0.0,8584,0.075600
21,1000008,P00156442,1,2,12,2,4,1,8,0.0,0.0,9872,0.075600
22,1000008,P00213742,1,2,12,2,4,1,8,0.0,0.0,9743,0.075600
23,1000008,P00214442,1,2,12,2,4,1,8,0.0,0.0,5982,0.075600
24,1000008,P00303442,1,2,12,2,4,1,1,8.0,14.0,11927,0.075600
25,1000009,P00135742,1,2,17,2,0,0,6,8.0,0.0,16662,0.056383
26,1000009,P00039942,1,2,17,2,0,0,8,0.0,0.0,5887,0.056383
27,1000009,P00161442,1,2,17,2,0,0,5,14.0,0.0,6973,0.056383
28,1000009,P00078742,1,2,17,2,0,0,5,8.0,14.0,5391,0.056383
29,1000010,P00085942,0,3,1,1,4,1,2,4.0,8.0,16352,0.205896
...,...,...,...,...,...,...,...,...,...,...,...,...,...
550038,1005995,P00375436,0,3,1,2,2,1,20,0.0,0.0,596,0.096327
550039,1005996,P00371644,0,2,0,1,1,1,20,0.0,0.0,595,0.286774
550040,1005997,P00370853,0,2,7,0,3,0,19,0.0,0.0,26,0.038885
550041,1006000,P00371644,1,4,17,1,2,1,20,0.0,0.0,488,0.225181
550042,1006002,P00371644,1,5,0,2,1,1,20,0.0,0.0,243,0.174953
550043,1006003,P00370293,0,4,17,2,1,0,19,0.0,0.0,48,0.152510
550044,1006004,P00370853,0,2,15,2,2,0,19,0.0,0.0,62,0.030968
550045,1006005,P00371644,0,2,5,2,2,1,20,0.0,0.0,252,0.035107
550046,1006006,P00375436,0,0,0,2,1,0,20,0.0,0.0,236,0.048868
550047,1006009,P00372445,0,2,12,2,3,0,20,0.0,0.0,244,0.026471
550048,1006010,P00371644,1,3,0,2,1,0,20,0.0,0.0,591,0.183565
550049,1006011,P00375436,1,3,15,2,3,0,20,0.0,0.0,473,0.113763
550050,1006012,P00371644,1,3,15,2,4,1,20,0.0,0.0,368,0.012140
550051,1006013,P00375436,0,2,20,2,3,0,20,0.0,0.0,489,0.059111
550052,1006016,P00375436,1,4,1,1,1,1,20,0.0,0.0,239,0.357882
550053,1006017,P00371644,0,3,7,1,1,0,20,0.0,0.0,371,0.015207
550054,1006018,P00370293,1,3,1,2,3,0,19,0.0,0.0,60,0.092587
550055,1006019,P00372445,1,2,0,0,4,0,20,0.0,0.0,238,0.057376
550056,1006022,P00375436,1,2,17,2,4,0,20,0.0,0.0,254,0.026408
550057,1006023,P00370853,1,2,0,2,2,1,19,0.0,0.0,61,0.115993
550058,1006024,P00372445,1,2,12,0,0,1,20,0.0,0.0,121,0.078540
550059,1006025,P00370853,0,2,1,1,1,0,19,0.0,0.0,48,0.098725
550060,1006026,P00371644,1,3,6,2,1,1,20,0.0,0.0,494,0.046576
550061,1006029,P00372445,0,2,1,2,1,1,20,0.0,0.0,599,0.014941
550062,1006032,P00372445,1,4,7,0,3,0,20,0.0,0.0,473,0.049090
550063,1006033,P00372445,1,5,13,1,1,1,20,0.0,0.0,368,0.047627
550064,1006035,P00375436,0,2,1,2,3,0,20,0.0,0.0,371,0.090790
550065,1006036,P00375436,0,2,15,1,4,1,20,0.0,0.0,137,0.390632
550066,1006038,P00375436,0,6,1,2,2,0,20,0.0,0.0,365,0.008545
550067,1006039,P00371644,0,4,0,1,4,1,20,0.0,0.0,490,0.056024

In [40]:
data.dtypes

User_ID                         int64
Product_ID                     object
Gender                          int64
Age                             int64
Occupation                      int64
City_Category                   int64
Stay_In_Current_City_Years      int64
Marital_Status                  int64
Product_Category_1              int64
Product_Category_2            float64
Product_Category_3            float64
Purchase                        int64
User_Score                    float64
dtype: object

In [41]:
data['Product_ID'] = data['Product_ID'].str[2:]

In [42]:
data['Product_ID'] = data['Product_ID'].astype(str).astype(int)

In [43]:
data.dtypes

User_ID                         int64
Product_ID                      int64
Gender                          int64
Age                             int64
Occupation                      int64
City_Category                   int64
Stay_In_Current_City_Years      int64
Marital_Status                  int64
Product_Category_1              int64
Product_Category_2            float64
Product_Category_3            float64
Purchase                        int64
User_Score                    float64
dtype: object

In [44]:
data

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase,User_Score
0,1000001,69042,0,0,10,0,2,0,3,0.0,0.0,8370,0.031707
1,1000001,248942,0,0,10,0,2,0,1,6.0,14.0,15200,0.031707
2,1000001,87842,0,0,10,0,2,0,12,0.0,0.0,1422,0.031707
3,1000001,85442,0,0,10,0,2,0,12,14.0,0.0,1057,0.031707
4,1000002,285442,1,6,16,2,4,0,8,0.0,0.0,7969,0.076917
5,1000003,193542,1,2,15,0,3,0,1,2.0,0.0,15227,0.032423
6,1000004,184942,1,4,7,1,2,1,1,8.0,17.0,19215,0.019595
7,1000004,346142,1,4,7,1,2,1,1,15.0,0.0,15854,0.019595
8,1000004,97242,1,4,7,1,2,1,1,16.0,0.0,15686,0.019595
9,1000005,274942,1,2,20,0,1,1,8,0.0,0.0,7871,0.077917
10,1000005,251242,1,2,20,0,1,1,5,11.0,0.0,5254,0.077917
11,1000005,14542,1,2,20,0,1,1,8,0.0,0.0,3957,0.077917
12,1000005,31342,1,2,20,0,1,1,8,0.0,0.0,6073,0.077917
13,1000005,145042,1,2,20,0,1,1,1,2.0,5.0,15665,0.077917
14,1000006,231342,0,5,9,0,1,0,5,8.0,14.0,5378,0.036057
15,1000006,190242,0,5,9,0,1,0,4,5.0,0.0,2079,0.036057
16,1000006,96642,0,5,9,0,1,0,2,3.0,4.0,13055,0.036057
17,1000006,58442,0,5,9,0,1,0,5,14.0,0.0,8851,0.036057
18,1000007,36842,1,3,1,1,1,1,1,14.0,16.0,11788,0.022271
19,1000008,249542,1,2,12,2,4,1,1,5.0,15.0,19614,0.075600
20,1000008,220442,1,2,12,2,4,1,5,14.0,0.0,8584,0.075600
21,1000008,156442,1,2,12,2,4,1,8,0.0,0.0,9872,0.075600
22,1000008,213742,1,2,12,2,4,1,8,0.0,0.0,9743,0.075600
23,1000008,214442,1,2,12,2,4,1,8,0.0,0.0,5982,0.075600
24,1000008,303442,1,2,12,2,4,1,1,8.0,14.0,11927,0.075600
25,1000009,135742,1,2,17,2,0,0,6,8.0,0.0,16662,0.056383
26,1000009,39942,1,2,17,2,0,0,8,0.0,0.0,5887,0.056383
27,1000009,161442,1,2,17,2,0,0,5,14.0,0.0,6973,0.056383
28,1000009,78742,1,2,17,2,0,0,5,8.0,14.0,5391,0.056383
29,1000010,85942,0,3,1,1,4,1,2,4.0,8.0,16352,0.205896
...,...,...,...,...,...,...,...,...,...,...,...,...,...
550038,1005995,375436,0,3,1,2,2,1,20,0.0,0.0,596,0.096327
550039,1005996,371644,0,2,0,1,1,1,20,0.0,0.0,595,0.286774
550040,1005997,370853,0,2,7,0,3,0,19,0.0,0.0,26,0.038885
550041,1006000,371644,1,4,17,1,2,1,20,0.0,0.0,488,0.225181
550042,1006002,371644,1,5,0,2,1,1,20,0.0,0.0,243,0.174953
550043,1006003,370293,0,4,17,2,1,0,19,0.0,0.0,48,0.152510
550044,1006004,370853,0,2,15,2,2,0,19,0.0,0.0,62,0.030968
550045,1006005,371644,0,2,5,2,2,1,20,0.0,0.0,252,0.035107
550046,1006006,375436,0,0,0,2,1,0,20,0.0,0.0,236,0.048868
550047,1006009,372445,0,2,12,2,3,0,20,0.0,0.0,244,0.026471
550048,1006010,371644,1,3,0,2,1,0,20,0.0,0.0,591,0.183565
550049,1006011,375436,1,3,15,2,3,0,20,0.0,0.0,473,0.113763
550050,1006012,371644,1,3,15,2,4,1,20,0.0,0.0,368,0.012140
550051,1006013,375436,0,2,20,2,3,0,20,0.0,0.0,489,0.059111
550052,1006016,375436,1,4,1,1,1,1,20,0.0,0.0,239,0.357882
550053,1006017,371644,0,3,7,1,1,0,20,0.0,0.0,371,0.015207
550054,1006018,370293,1,3,1,2,3,0,19,0.0,0.0,60,0.092587
550055,1006019,372445,1,2,0,0,4,0,20,0.0,0.0,238,0.057376
550056,1006022,375436,1,2,17,2,4,0,20,0.0,0.0,254,0.026408
550057,1006023,370853,1,2,0,2,2,1,19,0.0,0.0,61,0.115993
550058,1006024,372445,1,2,12,0,0,1,20,0.0,0.0,121,0.078540
550059,1006025,370853,0,2,1,1,1,0,19,0.0,0.0,48,0.098725
550060,1006026,371644,1,3,6,2,1,1,20,0.0,0.0,494,0.046576
550061,1006029,372445,0,2,1,2,1,1,20,0.0,0.0,599,0.014941
550062,1006032,372445,1,4,7,0,3,0,20,0.0,0.0,473,0.049090
550063,1006033,372445,1,5,13,1,1,1,20,0.0,0.0,368,0.047627
550064,1006035,375436,0,2,1,2,3,0,20,0.0,0.0,371,0.090790
550065,1006036,375436,0,2,15,1,4,1,20,0.0,0.0,137,0.390632
550066,1006038,375436,0,6,1,2,2,0,20,0.0,0.0,365,0.008545
550067,1006039,371644,0,4,0,1,4,1,20,0.0,0.0,490,0.056024

In [45]:
data['Product_Score'] = 0.0

In [46]:
data

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase,User_Score,Product_Score
0,1000001,69042,0,0,10,0,2,0,3,0.0,0.0,8370,0.031707,0.0
1,1000001,248942,0,0,10,0,2,0,1,6.0,14.0,15200,0.031707,0.0
2,1000001,87842,0,0,10,0,2,0,12,0.0,0.0,1422,0.031707,0.0
3,1000001,85442,0,0,10,0,2,0,12,14.0,0.0,1057,0.031707,0.0
4,1000002,285442,1,6,16,2,4,0,8,0.0,0.0,7969,0.076917,0.0
5,1000003,193542,1,2,15,0,3,0,1,2.0,0.0,15227,0.032423,0.0
6,1000004,184942,1,4,7,1,2,1,1,8.0,17.0,19215,0.019595,0.0
7,1000004,346142,1,4,7,1,2,1,1,15.0,0.0,15854,0.019595,0.0
8,1000004,97242,1,4,7,1,2,1,1,16.0,0.0,15686,0.019595,0.0
9,1000005,274942,1,2,20,0,1,1,8,0.0,0.0,7871,0.077917,0.0
10,1000005,251242,1,2,20,0,1,1,5,11.0,0.0,5254,0.077917,0.0
11,1000005,14542,1,2,20,0,1,1,8,0.0,0.0,3957,0.077917,0.0
12,1000005,31342,1,2,20,0,1,1,8,0.0,0.0,6073,0.077917,0.0
13,1000005,145042,1,2,20,0,1,1,1,2.0,5.0,15665,0.077917,0.0
14,1000006,231342,0,5,9,0,1,0,5,8.0,14.0,5378,0.036057,0.0
15,1000006,190242,0,5,9,0,1,0,4,5.0,0.0,2079,0.036057,0.0
16,1000006,96642,0,5,9,0,1,0,2,3.0,4.0,13055,0.036057,0.0
17,1000006,58442,0,5,9,0,1,0,5,14.0,0.0,8851,0.036057,0.0
18,1000007,36842,1,3,1,1,1,1,1,14.0,16.0,11788,0.022271,0.0
19,1000008,249542,1,2,12,2,4,1,1,5.0,15.0,19614,0.075600,0.0
20,1000008,220442,1,2,12,2,4,1,5,14.0,0.0,8584,0.075600,0.0
21,1000008,156442,1,2,12,2,4,1,8,0.0,0.0,9872,0.075600,0.0
22,1000008,213742,1,2,12,2,4,1,8,0.0,0.0,9743,0.075600,0.0
23,1000008,214442,1,2,12,2,4,1,8,0.0,0.0,5982,0.075600,0.0
24,1000008,303442,1,2,12,2,4,1,1,8.0,14.0,11927,0.075600,0.0
25,1000009,135742,1,2,17,2,0,0,6,8.0,0.0,16662,0.056383,0.0
26,1000009,39942,1,2,17,2,0,0,8,0.0,0.0,5887,0.056383,0.0
27,1000009,161442,1,2,17,2,0,0,5,14.0,0.0,6973,0.056383,0.0
28,1000009,78742,1,2,17,2,0,0,5,8.0,14.0,5391,0.056383,0.0
29,1000010,85942,0,3,1,1,4,1,2,4.0,8.0,16352,0.205896,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
550038,1005995,375436,0,3,1,2,2,1,20,0.0,0.0,596,0.096327,0.0
550039,1005996,371644,0,2,0,1,1,1,20,0.0,0.0,595,0.286774,0.0
550040,1005997,370853,0,2,7,0,3,0,19,0.0,0.0,26,0.038885,0.0
550041,1006000,371644,1,4,17,1,2,1,20,0.0,0.0,488,0.225181,0.0
550042,1006002,371644,1,5,0,2,1,1,20,0.0,0.0,243,0.174953,0.0
550043,1006003,370293,0,4,17,2,1,0,19,0.0,0.0,48,0.152510,0.0
550044,1006004,370853,0,2,15,2,2,0,19,0.0,0.0,62,0.030968,0.0
550045,1006005,371644,0,2,5,2,2,1,20,0.0,0.0,252,0.035107,0.0
550046,1006006,375436,0,0,0,2,1,0,20,0.0,0.0,236,0.048868,0.0
550047,1006009,372445,0,2,12,2,3,0,20,0.0,0.0,244,0.026471,0.0
550048,1006010,371644,1,3,0,2,1,0,20,0.0,0.0,591,0.183565,0.0
550049,1006011,375436,1,3,15,2,3,0,20,0.0,0.0,473,0.113763,0.0
550050,1006012,371644,1,3,15,2,4,1,20,0.0,0.0,368,0.012140,0.0
550051,1006013,375436,0,2,20,2,3,0,20,0.0,0.0,489,0.059111,0.0
550052,1006016,375436,1,4,1,1,1,1,20,0.0,0.0,239,0.357882,0.0
550053,1006017,371644,0,3,7,1,1,0,20,0.0,0.0,371,0.015207,0.0
550054,1006018,370293,1,3,1,2,3,0,19,0.0,0.0,60,0.092587,0.0
550055,1006019,372445,1,2,0,0,4,0,20,0.0,0.0,238,0.057376,0.0
550056,1006022,375436,1,2,17,2,4,0,20,0.0,0.0,254,0.026408,0.0
550057,1006023,370853,1,2,0,2,2,1,19,0.0,0.0,61,0.115993,0.0
550058,1006024,372445,1,2,12,0,0,1,20,0.0,0.0,121,0.078540,0.0
550059,1006025,370853,0,2,1,1,1,0,19,0.0,0.0,48,0.098725,0.0
550060,1006026,371644,1,3,6,2,1,1,20,0.0,0.0,494,0.046576,0.0
550061,1006029,372445,0,2,1,2,1,1,20,0.0,0.0,599,0.014941,0.0
550062,1006032,372445,1,4,7,0,3,0,20,0.0,0.0,473,0.049090,0.0
550063,1006033,372445,1,5,13,1,1,1,20,0.0,0.0,368,0.047627,0.0
550064,1006035,375436,0,2,1,2,3,0,20,0.0,0.0,371,0.090790,0.0
550065,1006036,375436,0,2,15,1,4,1,20,0.0,0.0,137,0.390632,0.0
550066,1006038,375436,0,6,1,2,2,0,20,0.0,0.0,365,0.008545,0.0
550067,1006039,371644,0,4,0,1,4,1,20,0.0,0.0,490,0.056024,0.0

In [47]:
required_product_data = data[['Product_ID', 'Product_Score']]

In [48]:
required_product_data

        Product_ID  Product_Score
0            69042            0.0
1           248942            0.0
2            87842            0.0
3            85442            0.0
4           285442            0.0
5           193542            0.0
6           184942            0.0
7           346142            0.0
8            97242            0.0
9           274942            0.0
10          251242            0.0
11           14542            0.0
12           31342            0.0
13          145042            0.0
14          231342            0.0
15          190242            0.0
16           96642            0.0
17           58442            0.0
18           36842            0.0
19          249542            0.0
20          220442            0.0
21          156442            0.0
22          213742            0.0
23          214442            0.0
24          303442            0.0
25          135742            0.0
26           39942            0.0
27          161442            0.0
28           78742            0.0
29           85942            0.0
...            ...            ...
550038      375436            0.0
550039      371644            0.0
550040      370853            0.0
550041      371644            0.0
550042      371644            0.0
550043      370293            0.0
550044      370853            0.0
550045      371644            0.0
550046      375436            0.0
550047      372445            0.0
550048      371644            0.0
550049      375436            0.0
550050      371644            0.0
550051      375436            0.0
550052      375436            0.0
550053      371644            0.0
550054      370293            0.0
550055      372445            0.0
550056      375436            0.0
550057      370853            0.0
550058      372445            0.0
550059      370853            0.0
550060      371644            0.0
550061      372445            0.0
550062      372445            0.0
550063      372445            0.0
550064      375436            0.0
550065      375436            0.0
550066      375436            0.0
550067      371644            0.0

[550068 rows x 2 columns]

In [49]:
required_product_data['Frequency'] = 1

/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':

In [50]:
required_product_data

        Product_ID  Product_Score  Frequency
0            69042            0.0          1
1           248942            0.0          1
2            87842            0.0          1
3            85442            0.0          1
4           285442            0.0          1
5           193542            0.0          1
6           184942            0.0          1
7           346142            0.0          1
8            97242            0.0          1
9           274942            0.0          1
10          251242            0.0          1
11           14542            0.0          1
12           31342            0.0          1
13          145042            0.0          1
14          231342            0.0          1
15          190242            0.0          1
16           96642            0.0          1
17           58442            0.0          1
18           36842            0.0          1
19          249542            0.0          1
20          220442            0.0          1
21          156442            0.0          1
22          213742            0.0          1
23          214442            0.0          1
24          303442            0.0          1
25          135742            0.0          1
26           39942            0.0          1
27          161442            0.0          1
28           78742            0.0          1
29           85942            0.0          1
...            ...            ...        ...
550038      375436            0.0          1
550039      371644            0.0          1
550040      370853            0.0          1
550041      371644            0.0          1
550042      371644            0.0          1
550043      370293            0.0          1
550044      370853            0.0          1
550045      371644            0.0          1
550046      375436            0.0          1
550047      372445            0.0          1
550048      371644            0.0          1
550049      375436            0.0          1
550050      371644            0.0          1
550051      375436            0.0          1
550052      375436            0.0          1
550053      371644            0.0          1
550054      370293            0.0          1
550055      372445            0.0          1
550056      375436            0.0          1
550057      370853            0.0          1
550058      372445            0.0          1
550059      370853            0.0          1
550060      371644            0.0          1
550061      372445            0.0          1
550062      372445            0.0          1
550063      372445            0.0          1
550064      375436            0.0          1
550065      375436            0.0          1
550066      375436            0.0          1
550067      371644            0.0          1

[550068 rows x 3 columns]

In [52]:
grouped_product_data = required_product_data.groupby(['Product_ID']).sum()

In [53]:
grouped_product_data

            Product_Score  Frequency
Product_ID
142                   0.0       1152
242                   0.0        376
342                   0.0        244
442                   0.0         92
542                   0.0        149
642                   0.0        512
742                   0.0        241
842                   0.0         36
942                   0.0         55
1042                  0.0        503
1142                  0.0        578
1242                  0.0        100
1342                  0.0         62
1442                  0.0         85
1542                  0.0         69
1642                  0.0        354
1742                  0.0        461
1842                  0.0         76
1942                  0.0        211
2042                  0.0         93
2142                  0.0        735
2242                  0.0        198
2342                  0.0         67
2442                  0.0        330
2542                  0.0        539
2642                  0.0         63
2742                  0.0         40
2842                  0.0         84
2942                  0.0        224
3042                  0.0         37
...                   ...        ...
368242                0.0        115
368342                0.0         82
368442                0.0        127
368542                0.0         20
368642                0.0        130
368742                0.0          8
368842                0.0         14
368942                0.0         10
369042                0.0         65
369142                0.0         78
369242                0.0         15
369342                0.0         15
369442                0.0          8
369542                0.0         14
369642                0.0         12
369742                0.0         49
369842                0.0          5
369942                0.0         24
370042                0.0         46
370142                0.0         30
370242                0.0        463
370293                0.0        785
370342                0.0        166
370442                0.0         25
370542                0.0         23
370642                0.0        217
370853                0.0        818
371644                0.0        899
372445                0.0        837
375436                0.0        814

[3631 rows x 2 columns]

In [54]:
grouped_product_data = grouped_product_data.reset_index()

In [55]:
grouped_product_data

      Product_ID  Product_Score  Frequency
0            142            0.0       1152
1            242            0.0        376
2            342            0.0        244
3            442            0.0         92
4            542            0.0        149
5            642            0.0        512
6            742            0.0        241
7            842            0.0         36
8            942            0.0         55
9           1042            0.0        503
10          1142            0.0        578
11          1242            0.0        100
12          1342            0.0         62
13          1442            0.0         85
14          1542            0.0         69
15          1642            0.0        354
16          1742            0.0        461
17          1842            0.0         76
18          1942            0.0        211
19          2042            0.0         93
20          2142            0.0        735
21          2242            0.0        198
22          2342            0.0         67
23          2442            0.0        330
24          2542            0.0        539
25          2642            0.0         63
26          2742            0.0         40
27          2842            0.0         84
28          2942            0.0        224
29          3042            0.0         37
...          ...            ...        ...
3601      368242            0.0        115
3602      368342            0.0         82
3603      368442            0.0        127
3604      368542            0.0         20
3605      368642            0.0        130
3606      368742            0.0          8
3607      368842            0.0         14
3608      368942            0.0         10
3609      369042            0.0         65
3610      369142            0.0         78
3611      369242            0.0         15
3612      369342            0.0         15
3613      369442            0.0          8
3614      369542            0.0         14
3615      369642            0.0         12
3616      369742            0.0         49
3617      369842            0.0          5
3618      369942            0.0         24
3619      370042            0.0         46
3620      370142            0.0         30
3621      370242            0.0        463
3622      370293            0.0        785
3623      370342            0.0        166
3624      370442            0.0         25
3625      370542            0.0         23
3626      370642            0.0        217
3627      370853            0.0        818
3628      371644            0.0        899
3629      372445            0.0        837
3630      375436            0.0        814

[3631 rows x 3 columns]

In [56]:
max_frequency = grouped_product_data['Frequency'].max()

In [57]:
max_frequency

1880

In [58]:
final_product_data = grouped_product_data[['Product_ID', 'Product_Score', 'Frequency']]

In [60]:
final_product_data = pd.DataFrame(final_product_data)

In [61]:
final_product_data

      Product_ID  Product_Score  Frequency
0            142            0.0       1152
1            242            0.0        376
2            342            0.0        244
3            442            0.0         92
4            542            0.0        149
5            642            0.0        512
6            742            0.0        241
7            842            0.0         36
8            942            0.0         55
9           1042            0.0        503
10          1142            0.0        578
11          1242            0.0        100
12          1342            0.0         62
13          1442            0.0         85
14          1542            0.0         69
15          1642            0.0        354
16          1742            0.0        461
17          1842            0.0         76
18          1942            0.0        211
19          2042            0.0         93
20          2142            0.0        735
21          2242            0.0        198
22          2342            0.0         67
23          2442            0.0        330
24          2542            0.0        539
25          2642            0.0         63
26          2742            0.0         40
27          2842            0.0         84
28          2942            0.0        224
29          3042            0.0         37
...          ...            ...        ...
3601      368242            0.0        115
3602      368342            0.0         82
3603      368442            0.0        127
3604      368542            0.0         20
3605      368642            0.0        130
3606      368742            0.0          8
3607      368842            0.0         14
3608      368942            0.0         10
3609      369042            0.0         65
3610      369142            0.0         78
3611      369242            0.0         15
3612      369342            0.0         15
3613      369442            0.0          8
3614      369542            0.0         14
3615      369642            0.0         12
3616      369742            0.0         49
3617      369842            0.0          5
3618      369942            0.0         24
3619      370042            0.0         46
3620      370142            0.0         30
3621      370242            0.0        463
3622      370293            0.0        785
3623      370342            0.0        166
3624      370442            0.0         25
3625      370542            0.0         23
3626      370642            0.0        217
3627      370853            0.0        818
3628      371644            0.0        899
3629      372445            0.0        837
3630      375436            0.0        814

[3631 rows x 3 columns]

In [62]:
for index, row in final_product_data.iterrows():
    product_score = (float(row['Frequency']) / float(max_frequency))
    final_product_data.set_value(index, 'Product_Score', product_score)

/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/ipykernel/__main__.py:3: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
  app.launch_new_instance()

In [63]:
final_product_data

      Product_ID  Product_Score  Frequency
0            142       0.612766       1152
1            242       0.200000        376
2            342       0.129787        244
3            442       0.048936         92
4            542       0.079255        149
5            642       0.272340        512
6            742       0.128191        241
7            842       0.019149         36
8            942       0.029255         55
9           1042       0.267553        503
10          1142       0.307447        578
11          1242       0.053191        100
12          1342       0.032979         62
13          1442       0.045213         85
14          1542       0.036702         69
15          1642       0.188298        354
16          1742       0.245213        461
17          1842       0.040426         76
18          1942       0.112234        211
19          2042       0.049468         93
20          2142       0.390957        735
21          2242       0.105319        198
22          2342       0.035638         67
23          2442       0.175532        330
24          2542       0.286702        539
25          2642       0.033511         63
26          2742       0.021277         40
27          2842       0.044681         84
28          2942       0.119149        224
29          3042       0.019681         37
...          ...            ...        ...
3601      368242       0.061170        115
3602      368342       0.043617         82
3603      368442       0.067553        127
3604      368542       0.010638         20
3605      368642       0.069149        130
3606      368742       0.004255          8
3607      368842       0.007447         14
3608      368942       0.005319         10
3609      369042       0.034574         65
3610      369142       0.041489         78
3611      369242       0.007979         15
3612      369342       0.007979         15
3613      369442       0.004255          8
3614      369542       0.007447         14
3615      369642       0.006383         12
3616      369742       0.026064         49
3617      369842       0.002660          5
3618      369942       0.012766         24
3619      370042       0.024468         46
3620      370142       0.015957         30
3621      370242       0.246277        463
3622      370293       0.417553        785
3623      370342       0.088298        166
3624      370442       0.013298         25
3625      370542       0.012234         23
3626      370642       0.115426        217
3627      370853       0.435106        818
3628      371644       0.478191        899
3629      372445       0.445213        837
3630      375436       0.432979        814

[3631 rows x 3 columns]

In [64]:
data

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase,User_Score,Product_Score
0,1000001,69042,0,0,10,0,2,0,3,0.0,0.0,8370,0.031707,0.0
1,1000001,248942,0,0,10,0,2,0,1,6.0,14.0,15200,0.031707,0.0
2,1000001,87842,0,0,10,0,2,0,12,0.0,0.0,1422,0.031707,0.0
3,1000001,85442,0,0,10,0,2,0,12,14.0,0.0,1057,0.031707,0.0
4,1000002,285442,1,6,16,2,4,0,8,0.0,0.0,7969,0.076917,0.0
5,1000003,193542,1,2,15,0,3,0,1,2.0,0.0,15227,0.032423,0.0
6,1000004,184942,1,4,7,1,2,1,1,8.0,17.0,19215,0.019595,0.0
7,1000004,346142,1,4,7,1,2,1,1,15.0,0.0,15854,0.019595,0.0
8,1000004,97242,1,4,7,1,2,1,1,16.0,0.0,15686,0.019595,0.0
9,1000005,274942,1,2,20,0,1,1,8,0.0,0.0,7871,0.077917,0.0
10,1000005,251242,1,2,20,0,1,1,5,11.0,0.0,5254,0.077917,0.0
11,1000005,14542,1,2,20,0,1,1,8,0.0,0.0,3957,0.077917,0.0
12,1000005,31342,1,2,20,0,1,1,8,0.0,0.0,6073,0.077917,0.0
13,1000005,145042,1,2,20,0,1,1,1,2.0,5.0,15665,0.077917,0.0
14,1000006,231342,0,5,9,0,1,0,5,8.0,14.0,5378,0.036057,0.0
15,1000006,190242,0,5,9,0,1,0,4,5.0,0.0,2079,0.036057,0.0
16,1000006,96642,0,5,9,0,1,0,2,3.0,4.0,13055,0.036057,0.0
17,1000006,58442,0,5,9,0,1,0,5,14.0,0.0,8851,0.036057,0.0
18,1000007,36842,1,3,1,1,1,1,1,14.0,16.0,11788,0.022271,0.0
19,1000008,249542,1,2,12,2,4,1,1,5.0,15.0,19614,0.075600,0.0
20,1000008,220442,1,2,12,2,4,1,5,14.0,0.0,8584,0.075600,0.0
21,1000008,156442,1,2,12,2,4,1,8,0.0,0.0,9872,0.075600,0.0
22,1000008,213742,1,2,12,2,4,1,8,0.0,0.0,9743,0.075600,0.0
23,1000008,214442,1,2,12,2,4,1,8,0.0,0.0,5982,0.075600,0.0
24,1000008,303442,1,2,12,2,4,1,1,8.0,14.0,11927,0.075600,0.0
25,1000009,135742,1,2,17,2,0,0,6,8.0,0.0,16662,0.056383,0.0
26,1000009,39942,1,2,17,2,0,0,8,0.0,0.0,5887,0.056383,0.0
27,1000009,161442,1,2,17,2,0,0,5,14.0,0.0,6973,0.056383,0.0
28,1000009,78742,1,2,17,2,0,0,5,8.0,14.0,5391,0.056383,0.0
29,1000010,85942,0,3,1,1,4,1,2,4.0,8.0,16352,0.205896,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
550038,1005995,375436,0,3,1,2,2,1,20,0.0,0.0,596,0.096327,0.0
550039,1005996,371644,0,2,0,1,1,1,20,0.0,0.0,595,0.286774,0.0
550040,1005997,370853,0,2,7,0,3,0,19,0.0,0.0,26,0.038885,0.0
550041,1006000,371644,1,4,17,1,2,1,20,0.0,0.0,488,0.225181,0.0
550042,1006002,371644,1,5,0,2,1,1,20,0.0,0.0,243,0.174953,0.0
550043,1006003,370293,0,4,17,2,1,0,19,0.0,0.0,48,0.152510,0.0
550044,1006004,370853,0,2,15,2,2,0,19,0.0,0.0,62,0.030968,0.0
550045,1006005,371644,0,2,5,2,2,1,20,0.0,0.0,252,0.035107,0.0
550046,1006006,375436,0,0,0,2,1,0,20,0.0,0.0,236,0.048868,0.0
550047,1006009,372445,0,2,12,2,3,0,20,0.0,0.0,244,0.026471,0.0
550048,1006010,371644,1,3,0,2,1,0,20,0.0,0.0,591,0.183565,0.0
550049,1006011,375436,1,3,15,2,3,0,20,0.0,0.0,473,0.113763,0.0
550050,1006012,371644,1,3,15,2,4,1,20,0.0,0.0,368,0.012140,0.0
550051,1006013,375436,0,2,20,2,3,0,20,0.0,0.0,489,0.059111,0.0
550052,1006016,375436,1,4,1,1,1,1,20,0.0,0.0,239,0.357882,0.0
550053,1006017,371644,0,3,7,1,1,0,20,0.0,0.0,371,0.015207,0.0
550054,1006018,370293,1,3,1,2,3,0,19,0.0,0.0,60,0.092587,0.0
550055,1006019,372445,1,2,0,0,4,0,20,0.0,0.0,238,0.057376,0.0
550056,1006022,375436,1,2,17,2,4,0,20,0.0,0.0,254,0.026408,0.0
550057,1006023,370853,1,2,0,2,2,1,19,0.0,0.0,61,0.115993,0.0
550058,1006024,372445,1,2,12,0,0,1,20,0.0,0.0,121,0.078540,0.0
550059,1006025,370853,0,2,1,1,1,0,19,0.0,0.0,48,0.098725,0.0
550060,1006026,371644,1,3,6,2,1,1,20,0.0,0.0,494,0.046576,0.0
550061,1006029,372445,0,2,1,2,1,1,20,0.0,0.0,599,0.014941,0.0
550062,1006032,372445,1,4,7,0,3,0,20,0.0,0.0,473,0.049090,0.0
550063,1006033,372445,1,5,13,1,1,1,20,0.0,0.0,368,0.047627,0.0
550064,1006035,375436,0,2,1,2,3,0,20,0.0,0.0,371,0.090790,0.0
550065,1006036,375436,0,2,15,1,4,1,20,0.0,0.0,137,0.390632,0.0
550066,1006038,375436,0,6,1,2,2,0,20,0.0,0.0,365,0.008545,0.0
550067,1006039,371644,0,4,0,1,4,1,20,0.0,0.0,490,0.056024,0.0

In [65]:
for index, row in data.iterrows():
    p_score = final_product_data.loc[final_product_data.Product_ID == row['Product_ID'], 'Product_Score'].values[0]
    data.set_value(index, 'Product_Score', p_score)

/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/ipykernel/__main__.py:3: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
  app.launch_new_instance()

In [66]:
data

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase,User_Score,Product_Score
0,1000001,69042,0,0,10,0,2,0,3,0.0,0.0,8370,0.031707,0.120745
1,1000001,248942,0,0,10,0,2,0,1,6.0,14.0,15200,0.031707,0.309043
2,1000001,87842,0,0,10,0,2,0,12,0.0,0.0,1422,0.031707,0.054255
3,1000001,85442,0,0,10,0,2,0,12,14.0,0.0,1057,0.031707,0.181383
4,1000002,285442,1,6,16,2,4,0,8,0.0,0.0,7969,0.076917,0.107979
5,1000003,193542,1,2,15,0,3,0,1,2.0,0.0,15227,0.032423,0.327128
6,1000004,184942,1,4,7,1,2,1,1,8.0,17.0,19215,0.019595,0.765957
7,1000004,346142,1,4,7,1,2,1,1,15.0,0.0,15854,0.019595,0.315426
8,1000004,97242,1,4,7,1,2,1,1,16.0,0.0,15686,0.019595,0.485106
9,1000005,274942,1,2,20,0,1,1,8,0.0,0.0,7871,0.077917,0.421809
10,1000005,251242,1,2,20,0,1,1,5,11.0,0.0,5254,0.077917,0.631383
11,1000005,14542,1,2,20,0,1,1,8,0.0,0.0,3957,0.077917,0.357447
12,1000005,31342,1,2,20,0,1,1,8,0.0,0.0,6073,0.077917,0.019149
13,1000005,145042,1,2,20,0,1,1,1,2.0,5.0,15665,0.077917,0.747872
14,1000006,231342,0,5,9,0,1,0,5,8.0,14.0,5378,0.036057,0.044149
15,1000006,190242,0,5,9,0,1,0,4,5.0,0.0,2079,0.036057,0.101064
16,1000006,96642,0,5,9,0,1,0,2,3.0,4.0,13055,0.036057,0.092553
17,1000006,58442,0,5,9,0,1,0,5,14.0,0.0,8851,0.036057,0.293617
18,1000007,36842,1,3,1,1,1,1,1,14.0,16.0,11788,0.022271,0.470213
19,1000008,249542,1,2,12,2,4,1,1,5.0,15.0,19614,0.075600,0.417553
20,1000008,220442,1,2,12,2,4,1,5,14.0,0.0,8584,0.075600,0.681915
21,1000008,156442,1,2,12,2,4,1,8,0.0,0.0,9872,0.075600,0.444149
22,1000008,213742,1,2,12,2,4,1,8,0.0,0.0,9743,0.075600,0.186702
23,1000008,214442,1,2,12,2,4,1,8,0.0,0.0,5982,0.075600,0.267021
24,1000008,303442,1,2,12,2,4,1,1,8.0,14.0,11927,0.075600,0.189362
25,1000009,135742,1,2,17,2,0,0,6,8.0,0.0,16662,0.056383,0.218085
26,1000009,39942,1,2,17,2,0,0,8,0.0,0.0,5887,0.056383,0.088830
27,1000009,161442,1,2,17,2,0,0,5,14.0,0.0,6973,0.056383,0.267553
28,1000009,78742,1,2,17,2,0,0,5,8.0,14.0,5391,0.056383,0.150000
29,1000010,85942,0,3,1,1,4,1,2,4.0,8.0,16352,0.205896,0.512234
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
550038,1005995,375436,0,3,1,2,2,1,20,0.0,0.0,596,0.096327,0.432979
550039,1005996,371644,0,2,0,1,1,1,20,0.0,0.0,595,0.286774,0.478191
550040,1005997,370853,0,2,7,0,3,0,19,0.0,0.0,26,0.038885,0.435106
550041,1006000,371644,1,4,17,1,2,1,20,0.0,0.0,488,0.225181,0.478191
550042,1006002,371644,1,5,0,2,1,1,20,0.0,0.0,243,0.174953,0.478191
550043,1006003,370293,0,4,17,2,1,0,19,0.0,0.0,48,0.152510,0.417553
550044,1006004,370853,0,2,15,2,2,0,19,0.0,0.0,62,0.030968,0.435106
550045,1006005,371644,0,2,5,2,2,1,20,0.0,0.0,252,0.035107,0.478191
550046,1006006,375436,0,0,0,2,1,0,20,0.0,0.0,236,0.048868,0.432979
550047,1006009,372445,0,2,12,2,3,0,20,0.0,0.0,244,0.026471,0.445213
550048,1006010,371644,1,3,0,2,1,0,20,0.0,0.0,591,0.183565,0.478191
550049,1006011,375436,1,3,15,2,3,0,20,0.0,0.0,473,0.113763,0.432979
550050,1006012,371644,1,3,15,2,4,1,20,0.0,0.0,368,0.012140,0.478191
550051,1006013,375436,0,2,20,2,3,0,20,0.0,0.0,489,0.059111,0.432979
550052,1006016,375436,1,4,1,1,1,1,20,0.0,0.0,239,0.357882,0.432979
550053,1006017,371644,0,3,7,1,1,0,20,0.0,0.0,371,0.015207,0.478191
550054,1006018,370293,1,3,1,2,3,0,19,0.0,0.0,60,0.092587,0.417553
550055,1006019,372445,1,2,0,0,4,0,20,0.0,0.0,238,0.057376,0.445213
550056,1006022,375436,1,2,17,2,4,0,20,0.0,0.0,254,0.026408,0.432979
550057,1006023,370853,1,2,0,2,2,1,19,0.0,0.0,61,0.115993,0.435106
550058,1006024,372445,1,2,12,0,0,1,20,0.0,0.0,121,0.078540,0.445213
550059,1006025,370853,0,2,1,1,1,0,19,0.0,0.0,48,0.098725,0.435106
550060,1006026,371644,1,3,6,2,1,1,20,0.0,0.0,494,0.046576,0.478191
550061,1006029,372445,0,2,1,2,1,1,20,0.0,0.0,599,0.014941,0.445213
550062,1006032,372445,1,4,7,0,3,0,20,0.0,0.0,473,0.049090,0.445213
550063,1006033,372445,1,5,13,1,1,1,20,0.0,0.0,368,0.047627,0.445213
550064,1006035,375436,0,2,1,2,3,0,20,0.0,0.0,371,0.090790,0.432979
550065,1006036,375436,0,2,15,1,4,1,20,0.0,0.0,137,0.390632,0.432979
550066,1006038,375436,0,6,1,2,2,0,20,0.0,0.0,365,0.008545,0.432979
550067,1006039,371644,0,4,0,1,4,1,20,0.0,0.0,490,0.056024,0.478191

In [67]:
data.to_csv('BlackFriday.csv')