In [1]:
import warnings

In [2]:
import numpy as np
import pandas as pd

In [3]:
train_data = pd.read_csv('TrainDataSet.csv')

In [4]:
test_data = pd.read_csv('TestDataSet.csv')

In [5]:
train_data

,Unnamed: 0,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Category_Count,Product_Score,User_Score,Purchase
0,0,1000001,69042,0,0,10,0,2,0,3,0,0,1,0.120745,0.031707,8370
1,1,1000001,248942,0,0,10,0,2,0,1,6,14,3,0.309043,0.031707,15200
2,2,1000001,87842,0,0,10,0,2,0,12,0,0,1,0.054255,0.031707,1422
3,3,1000001,85442,0,0,10,0,2,0,12,14,0,2,0.181383,0.031707,1057
4,4,1000002,285442,1,6,16,2,4,0,8,0,0,1,0.107979,0.076917,7969
5,5,1000003,193542,1,2,15,0,3,0,1,2,0,2,0.327128,0.032423,15227
6,6,1000004,184942,1,4,7,1,2,1,1,8,17,3,0.765957,0.019595,19215
7,7,1000004,346142,1,4,7,1,2,1,1,15,0,2,0.315426,0.019595,15854
8,8,1000004,97242,1,4,7,1,2,1,1,16,0,2,0.485106,0.019595,15686
9,9,1000005,274942,1,2,20,0,1,1,8,0,0,1,0.421809,0.077917,7871
10,10,1000005,251242,1,2,20,0,1,1,5,11,0,2,0.631383,0.077917,5254
11,11,1000005,14542,1,2,20,0,1,1,8,0,0,1,0.357447,0.077917,3957
12,12,1000005,31342,1,2,20,0,1,1,8,0,0,1,0.019149,0.077917,6073
13,13,1000005,145042,1,2,20,0,1,1,1,2,5,3,0.747872,0.077917,15665
14,14,1000006,231342,0,5,9,0,1,0,5,8,14,3,0.044149,0.036057,5378
15,15,1000006,190242,0,5,9,0,1,0,4,5,0,2,0.101064,0.036057,2079
16,16,1000006,96642,0,5,9,0,1,0,2,3,4,3,0.092553,0.036057,13055
17,17,1000006,58442,0,5,9,0,1,0,5,14,0,2,0.293617,0.036057,8851
18,18,1000007,36842,1,3,1,1,1,1,1,14,16,3,0.470213,0.022271,11788
19,19,1000008,249542,1,2,12,2,4,1,1,5,15,3,0.417553,0.075600,19614
20,20,1000008,220442,1,2,12,2,4,1,5,14,0,2,0.681915,0.075600,8584
21,21,1000008,156442,1,2,12,2,4,1,8,0,0,1,0.444149,0.075600,9872
22,22,1000008,213742,1,2,12,2,4,1,8,0,0,1,0.186702,0.075600,9743
23,23,1000008,214442,1,2,12,2,4,1,8,0,0,1,0.267021,0.075600,5982
24,24,1000008,303442,1,2,12,2,4,1,1,8,14,3,0.189362,0.075600,11927
25,25,1000009,135742,1,2,17,2,0,0,6,8,0,2,0.218085,0.056383,16662
26,26,1000009,39942,1,2,17,2,0,0,8,0,0,1,0.088830,0.056383,5887
27,27,1000009,161442,1,2,17,2,0,0,5,14,0,2,0.267553,0.056383,6973
28,28,1000009,78742,1,2,17,2,0,0,5,8,14,3,0.150000,0.056383,5391
29,29,1000010,85942,0,3,1,1,4,1,2,4,8,3,0.512234,0.205896,16352
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
550038,550038,1005995,375436,0,3,1,2,2,1,20,0,0,1,0.432979,0.096327,596
550039,550039,1005996,371644,0,2,0,1,1,1,20,0,0,1,0.478191,0.286774,595
550040,550040,1005997,370853,0,2,7,0,3,0,19,0,0,1,0.435106,0.038885,26
550041,550041,1006000,371644,1,4,17,1,2,1,20,0,0,1,0.478191,0.225181,488
550042,550042,1006002,371644,1,5,0,2,1,1,20,0,0,1,0.478191,0.174953,243
550043,550043,1006003,370293,0,4,17,2,1,0,19,0,0,1,0.417553,0.152510,48
550044,550044,1006004,370853,0,2,15,2,2,0,19,0,0,1,0.435106,0.030968,62
550045,550045,1006005,371644,0,2,5,2,2,1,20,0,0,1,0.478191,0.035107,252
550046,550046,1006006,375436,0,0,0,2,1,0,20,0,0,1,0.432979,0.048868,236
550047,550047,1006009,372445,0,2,12,2,3,0,20,0,0,1,0.445213,0.026471,244
550048,550048,1006010,371644,1,3,0,2,1,0,20,0,0,1,0.478191,0.183565,591
550049,550049,1006011,375436,1,3,15,2,3,0,20,0,0,1,0.432979,0.113763,473
550050,550050,1006012,371644,1,3,15,2,4,1,20,0,0,1,0.478191,0.012140,368
550051,550051,1006013,375436,0,2,20,2,3,0,20,0,0,1,0.432979,0.059111,489
550052,550052,1006016,375436,1,4,1,1,1,1,20,0,0,1,0.432979,0.357882,239
550053,550053,1006017,371644,0,3,7,1,1,0,20,0,0,1,0.478191,0.015207,371
550054,550054,1006018,370293,1,3,1,2,3,0,19,0,0,1,0.417553,0.092587,60
550055,550055,1006019,372445,1,2,0,0,4,0,20,0,0,1,0.445213,0.057376,238
550056,550056,1006022,375436,1,2,17,2,4,0,20,0,0,1,0.432979,0.026408,254
550057,550057,1006023,370853,1,2,0,2,2,1,19,0,0,1,0.435106,0.115993,61
550058,550058,1006024,372445,1,2,12,0,0,1,20,0,0,1,0.445213,0.078540,121
550059,550059,1006025,370853,0,2,1,1,1,0,19,0,0,1,0.435106,0.098725,48
550060,550060,1006026,371644,1,3,6,2,1,1,20,0,0,1,0.478191,0.046576,494
550061,550061,1006029,372445,0,2,1,2,1,1,20,0,0,1,0.445213,0.014941,599
550062,550062,1006032,372445,1,4,7,0,3,0,20,0,0,1,0.445213,0.049090,473
550063,550063,1006033,372445,1,5,13,1,1,1,20,0,0,1,0.445213,0.047627,368
550064,550064,1006035,375436,0,2,1,2,3,0,20,0,0,1,0.432979,0.090790,371
550065,550065,1006036,375436,0,2,15,1,4,1,20,0,0,1,0.432979,0.390632,137
550066,550066,1006038,375436,0,6,1,2,2,0,20,0,0,1,0.432979,0.008545,365
550067,550067,1006039,371644,0,4,0,1,4,1,20,0,0,1,0.478191,0.056024,490

In [6]:
train_data = train_data.drop(['Unnamed: 0'], axis=1)

In [7]:
train_data

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Category_Count,Product_Score,User_Score,Purchase
0,1000001,69042,0,0,10,0,2,0,3,0,0,1,0.120745,0.031707,8370
1,1000001,248942,0,0,10,0,2,0,1,6,14,3,0.309043,0.031707,15200
2,1000001,87842,0,0,10,0,2,0,12,0,0,1,0.054255,0.031707,1422
3,1000001,85442,0,0,10,0,2,0,12,14,0,2,0.181383,0.031707,1057
4,1000002,285442,1,6,16,2,4,0,8,0,0,1,0.107979,0.076917,7969
5,1000003,193542,1,2,15,0,3,0,1,2,0,2,0.327128,0.032423,15227
6,1000004,184942,1,4,7,1,2,1,1,8,17,3,0.765957,0.019595,19215
7,1000004,346142,1,4,7,1,2,1,1,15,0,2,0.315426,0.019595,15854
8,1000004,97242,1,4,7,1,2,1,1,16,0,2,0.485106,0.019595,15686
9,1000005,274942,1,2,20,0,1,1,8,0,0,1,0.421809,0.077917,7871
10,1000005,251242,1,2,20,0,1,1,5,11,0,2,0.631383,0.077917,5254
11,1000005,14542,1,2,20,0,1,1,8,0,0,1,0.357447,0.077917,3957
12,1000005,31342,1,2,20,0,1,1,8,0,0,1,0.019149,0.077917,6073
13,1000005,145042,1,2,20,0,1,1,1,2,5,3,0.747872,0.077917,15665
14,1000006,231342,0,5,9,0,1,0,5,8,14,3,0.044149,0.036057,5378
15,1000006,190242,0,5,9,0,1,0,4,5,0,2,0.101064,0.036057,2079
16,1000006,96642,0,5,9,0,1,0,2,3,4,3,0.092553,0.036057,13055
17,1000006,58442,0,5,9,0,1,0,5,14,0,2,0.293617,0.036057,8851
18,1000007,36842,1,3,1,1,1,1,1,14,16,3,0.470213,0.022271,11788
19,1000008,249542,1,2,12,2,4,1,1,5,15,3,0.417553,0.075600,19614
20,1000008,220442,1,2,12,2,4,1,5,14,0,2,0.681915,0.075600,8584
21,1000008,156442,1,2,12,2,4,1,8,0,0,1,0.444149,0.075600,9872
22,1000008,213742,1,2,12,2,4,1,8,0,0,1,0.186702,0.075600,9743
23,1000008,214442,1,2,12,2,4,1,8,0,0,1,0.267021,0.075600,5982
24,1000008,303442,1,2,12,2,4,1,1,8,14,3,0.189362,0.075600,11927
25,1000009,135742,1,2,17,2,0,0,6,8,0,2,0.218085,0.056383,16662
26,1000009,39942,1,2,17,2,0,0,8,0,0,1,0.088830,0.056383,5887
27,1000009,161442,1,2,17,2,0,0,5,14,0,2,0.267553,0.056383,6973
28,1000009,78742,1,2,17,2,0,0,5,8,14,3,0.150000,0.056383,5391
29,1000010,85942,0,3,1,1,4,1,2,4,8,3,0.512234,0.205896,16352
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
550038,1005995,375436,0,3,1,2,2,1,20,0,0,1,0.432979,0.096327,596
550039,1005996,371644,0,2,0,1,1,1,20,0,0,1,0.478191,0.286774,595
550040,1005997,370853,0,2,7,0,3,0,19,0,0,1,0.435106,0.038885,26
550041,1006000,371644,1,4,17,1,2,1,20,0,0,1,0.478191,0.225181,488
550042,1006002,371644,1,5,0,2,1,1,20,0,0,1,0.478191,0.174953,243
550043,1006003,370293,0,4,17,2,1,0,19,0,0,1,0.417553,0.152510,48
550044,1006004,370853,0,2,15,2,2,0,19,0,0,1,0.435106,0.030968,62
550045,1006005,371644,0,2,5,2,2,1,20,0,0,1,0.478191,0.035107,252
550046,1006006,375436,0,0,0,2,1,0,20,0,0,1,0.432979,0.048868,236
550047,1006009,372445,0,2,12,2,3,0,20,0,0,1,0.445213,0.026471,244
550048,1006010,371644,1,3,0,2,1,0,20,0,0,1,0.478191,0.183565,591
550049,1006011,375436,1,3,15,2,3,0,20,0,0,1,0.432979,0.113763,473
550050,1006012,371644,1,3,15,2,4,1,20,0,0,1,0.478191,0.012140,368
550051,1006013,375436,0,2,20,2,3,0,20,0,0,1,0.432979,0.059111,489
550052,1006016,375436,1,4,1,1,1,1,20,0,0,1,0.432979,0.357882,239
550053,1006017,371644,0,3,7,1,1,0,20,0,0,1,0.478191,0.015207,371
550054,1006018,370293,1,3,1,2,3,0,19,0,0,1,0.417553,0.092587,60
550055,1006019,372445,1,2,0,0,4,0,20,0,0,1,0.445213,0.057376,238
550056,1006022,375436,1,2,17,2,4,0,20,0,0,1,0.432979,0.026408,254
550057,1006023,370853,1,2,0,2,2,1,19,0,0,1,0.435106,0.115993,61
550058,1006024,372445,1,2,12,0,0,1,20,0,0,1,0.445213,0.078540,121
550059,1006025,370853,0,2,1,1,1,0,19,0,0,1,0.435106,0.098725,48
550060,1006026,371644,1,3,6,2,1,1,20,0,0,1,0.478191,0.046576,494
550061,1006029,372445,0,2,1,2,1,1,20,0,0,1,0.445213,0.014941,599
550062,1006032,372445,1,4,7,0,3,0,20,0,0,1,0.445213,0.049090,473
550063,1006033,372445,1,5,13,1,1,1,20,0,0,1,0.445213,0.047627,368
550064,1006035,375436,0,2,1,2,3,0,20,0,0,1,0.432979,0.090790,371
550065,1006036,375436,0,2,15,1,4,1,20,0,0,1,0.432979,0.390632,137
550066,1006038,375436,0,6,1,2,2,0,20,0,0,1,0.432979,0.008545,365
550067,1006039,371644,0,4,0,1,4,1,20,0,0,1,0.478191,0.056024,490

In [8]:
train_data.dtypes

User_ID                         int64
Product_ID                      int64
Gender                          int64
Age                             int64
Occupation                      int64
City_Category                   int64
Stay_In_Current_City_Years      int64
Marital_Status                  int64
Product_Category_1              int64
Product_Category_2              int64
Product_Category_3              int64
Category_Count                  int64
Product_Score                 float64
User_Score                    float64
Purchase                        int64
dtype: object

In [9]:
test_data

,Unnamed: 0,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Category_Count,User_Score,Product_Score
0,0,1000004,128942,1,4,7,1,2,1,1,11,0,2,0.019595,0.478890
1,1,1000009,113442,1,2,17,2,0,0,3,5,0,2,0.056383,0.141134
2,2,1000010,288442,0,3,1,1,4,1,5,14,0,2,0.205896,0.090470
3,3,1000010,145342,0,3,1,1,4,1,4,9,0,2,0.205896,0.009650
4,4,1000011,53842,0,2,1,2,1,0,4,5,12,3,0.052864,0.258142
5,5,1000013,350442,1,4,1,2,3,1,2,3,15,3,0.067755,0.142340
6,6,1000013,155442,1,4,1,2,3,1,1,11,15,3,0.067755,0.214717
7,7,1000013,94542,1,4,1,2,3,1,2,4,9,3,0.067755,0.082027
8,8,1000015,161842,1,2,7,0,1,0,10,13,16,3,0.099434,0.050663
9,9,1000022,67942,1,1,15,0,4,0,5,14,0,2,0.121470,0.183353
10,10,1000026,46742,1,2,7,1,2,1,1,2,15,3,0.152433,0.779252
11,11,1000026,40042,1,2,7,1,2,1,5,0,0,1,0.152433,0.059107
12,12,1000026,196542,1,2,7,1,2,1,5,8,14,3,0.152433,0.212304
13,13,1000026,4542,1,2,7,1,2,1,5,8,0,2,0.152433,0.155609
14,14,1000028,159542,0,2,1,2,2,1,10,15,16,3,0.049024,0.242461
15,15,1000029,111542,1,3,7,2,1,0,2,17,0,2,0.066073,0.255730
16,16,1000033,121042,1,4,3,0,1,1,15,0,0,1,0.184154,0.121834
17,17,1000033,344442,1,4,3,0,1,1,5,8,14,3,0.184154,0.162847
18,18,1000034,265242,0,1,0,0,0,0,5,8,0,2,0.076681,1.000000
19,19,1000035,96642,1,4,1,2,4,1,2,3,4,3,0.077945,0.094089
20,20,1000036,303042,1,2,3,1,0,0,5,0,0,1,0.219853,0.334138
21,21,1000036,59642,1,2,3,1,0,0,1,2,3,3,0.219853,0.184560
22,22,1000042,30842,1,2,8,2,0,1,1,2,15,3,0.140747,0.322075
23,23,1000045,346442,0,4,16,0,1,1,1,2,14,3,0.088118,0.124246
24,24,1000045,357242,0,4,16,0,1,1,5,0,0,1,0.088118,0.055489
25,25,1000045,284742,0,4,16,0,1,1,5,12,0,2,0.088118,0.069964
26,26,1000048,110842,1,2,4,1,3,1,1,2,5,3,0.264642,0.667069
27,27,1000048,251642,1,2,4,1,3,1,1,2,4,3,0.264642,0.120627
28,28,1000053,136742,1,2,0,1,1,0,1,14,16,3,0.405277,0.155609
29,29,1000053,97342,1,2,0,1,1,0,1,15,16,3,0.405277,0.149578
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
233569,233569,1005996,184242,0,2,0,1,1,1,9,15,0,2,0.286774,0.234017
233570,233570,1005996,45342,0,2,0,1,1,1,1,5,17,3,0.286774,0.174910
233571,233571,1006001,124642,0,2,7,0,0,1,16,0,0,1,0.119326,0.173703
233572,233572,1006002,121142,1,5,0,2,1,1,8,0,0,1,0.174953,0.178528
233573,233573,1006002,233542,1,5,0,2,1,1,1,15,0,2,0.174953,0.323281
233574,233574,1006002,226342,1,5,0,2,1,1,11,15,0,2,0.174953,0.316043
233575,233575,1006002,284842,1,5,0,2,1,1,1,8,17,3,0.174953,0.095296
233576,233576,1006003,313342,0,4,17,2,1,0,5,0,0,1,0.152510,0.313631
233577,233577,1006010,223542,1,3,0,2,1,0,1,8,17,3,0.183565,0.208685
233578,233578,1006013,20342,0,2,20,2,3,0,1,2,0,2,0.059111,0.186972
233579,233579,1006016,14842,1,4,1,1,1,1,1,2,5,3,0.357882,0.235223
233580,233580,1006016,109542,1,4,1,1,1,1,8,14,17,3,0.357882,0.243667
233581,233581,1006018,71442,1,3,1,2,3,0,15,17,0,2,0.092587,0.404101
233582,233582,1006021,112542,1,2,12,1,2,1,1,11,15,3,0.067330,0.595899
233583,233583,1006021,3442,1,2,12,1,2,1,4,5,8,3,0.067330,0.469240
233584,233584,1006023,262242,1,2,0,2,2,1,1,11,16,3,0.115993,0.211098
233585,233585,1006025,161142,0,2,1,1,1,0,11,0,0,1,0.098725,0.013269
233586,233586,1006026,110742,1,3,6,2,1,1,1,2,8,3,0.046576,0.820265
233587,233587,1006028,162442,1,1,4,0,4,0,1,16,0,2,0.034448,0.118215
233588,233588,1006030,129842,1,2,17,2,1,1,6,8,15,3,0.069979,0.287093
233589,233589,1006030,241442,1,2,17,2,1,1,2,15,0,2,0.069979,0.065139
233590,233590,1006032,252442,1,4,7,0,3,0,8,0,0,1,0.049090,0.107358
233591,233591,1006033,127642,1,5,13,1,1,1,1,2,15,3,0.047627,0.437877
233592,233592,1006035,135742,0,2,1,2,3,0,6,8,0,2,0.090790,0.184560
233593,233593,1006036,255442,0,2,15,1,4,1,8,0,0,1,0.390632,0.009650
233594,233594,1006036,118942,0,2,15,1,4,1,8,0,0,1,0.390632,0.090470
233595,233595,1006036,254642,0,2,15,1,4,1,5,8,0,2,0.390632,0.083233
233596,233596,1006036,31842,0,2,15,1,4,1,1,5,12,3,0.390632,0.094089
233597,233597,1006037,124742,0,4,1,2,4,0,10,16,0,2,0.106249,0.102533
233598,233598,1006039,316642,0,4,0,1,4,1,4,5,0,2,0.056024,0.200241

In [10]:
test_data = test_data.drop(['Unnamed: 0'], axis=1)

In [11]:
test_data

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Category_Count,User_Score,Product_Score
0,1000004,128942,1,4,7,1,2,1,1,11,0,2,0.019595,0.478890
1,1000009,113442,1,2,17,2,0,0,3,5,0,2,0.056383,0.141134
2,1000010,288442,0,3,1,1,4,1,5,14,0,2,0.205896,0.090470
3,1000010,145342,0,3,1,1,4,1,4,9,0,2,0.205896,0.009650
4,1000011,53842,0,2,1,2,1,0,4,5,12,3,0.052864,0.258142
5,1000013,350442,1,4,1,2,3,1,2,3,15,3,0.067755,0.142340
6,1000013,155442,1,4,1,2,3,1,1,11,15,3,0.067755,0.214717
7,1000013,94542,1,4,1,2,3,1,2,4,9,3,0.067755,0.082027
8,1000015,161842,1,2,7,0,1,0,10,13,16,3,0.099434,0.050663
9,1000022,67942,1,1,15,0,4,0,5,14,0,2,0.121470,0.183353
10,1000026,46742,1,2,7,1,2,1,1,2,15,3,0.152433,0.779252
11,1000026,40042,1,2,7,1,2,1,5,0,0,1,0.152433,0.059107
12,1000026,196542,1,2,7,1,2,1,5,8,14,3,0.152433,0.212304
13,1000026,4542,1,2,7,1,2,1,5,8,0,2,0.152433,0.155609
14,1000028,159542,0,2,1,2,2,1,10,15,16,3,0.049024,0.242461
15,1000029,111542,1,3,7,2,1,0,2,17,0,2,0.066073,0.255730
16,1000033,121042,1,4,3,0,1,1,15,0,0,1,0.184154,0.121834
17,1000033,344442,1,4,3,0,1,1,5,8,14,3,0.184154,0.162847
18,1000034,265242,0,1,0,0,0,0,5,8,0,2,0.076681,1.000000
19,1000035,96642,1,4,1,2,4,1,2,3,4,3,0.077945,0.094089
20,1000036,303042,1,2,3,1,0,0,5,0,0,1,0.219853,0.334138
21,1000036,59642,1,2,3,1,0,0,1,2,3,3,0.219853,0.184560
22,1000042,30842,1,2,8,2,0,1,1,2,15,3,0.140747,0.322075
23,1000045,346442,0,4,16,0,1,1,1,2,14,3,0.088118,0.124246
24,1000045,357242,0,4,16,0,1,1,5,0,0,1,0.088118,0.055489
25,1000045,284742,0,4,16,0,1,1,5,12,0,2,0.088118,0.069964
26,1000048,110842,1,2,4,1,3,1,1,2,5,3,0.264642,0.667069
27,1000048,251642,1,2,4,1,3,1,1,2,4,3,0.264642,0.120627
28,1000053,136742,1,2,0,1,1,0,1,14,16,3,0.405277,0.155609
29,1000053,97342,1,2,0,1,1,0,1,15,16,3,0.405277,0.149578
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
233569,1005996,184242,0,2,0,1,1,1,9,15,0,2,0.286774,0.234017
233570,1005996,45342,0,2,0,1,1,1,1,5,17,3,0.286774,0.174910
233571,1006001,124642,0,2,7,0,0,1,16,0,0,1,0.119326,0.173703
233572,1006002,121142,1,5,0,2,1,1,8,0,0,1,0.174953,0.178528
233573,1006002,233542,1,5,0,2,1,1,1,15,0,2,0.174953,0.323281
233574,1006002,226342,1,5,0,2,1,1,11,15,0,2,0.174953,0.316043
233575,1006002,284842,1,5,0,2,1,1,1,8,17,3,0.174953,0.095296
233576,1006003,313342,0,4,17,2,1,0,5,0,0,1,0.152510,0.313631
233577,1006010,223542,1,3,0,2,1,0,1,8,17,3,0.183565,0.208685
233578,1006013,20342,0,2,20,2,3,0,1,2,0,2,0.059111,0.186972
233579,1006016,14842,1,4,1,1,1,1,1,2,5,3,0.357882,0.235223
233580,1006016,109542,1,4,1,1,1,1,8,14,17,3,0.357882,0.243667
233581,1006018,71442,1,3,1,2,3,0,15,17,0,2,0.092587,0.404101
233582,1006021,112542,1,2,12,1,2,1,1,11,15,3,0.067330,0.595899
233583,1006021,3442,1,2,12,1,2,1,4,5,8,3,0.067330,0.469240
233584,1006023,262242,1,2,0,2,2,1,1,11,16,3,0.115993,0.211098
233585,1006025,161142,0,2,1,1,1,0,11,0,0,1,0.098725,0.013269
233586,1006026,110742,1,3,6,2,1,1,1,2,8,3,0.046576,0.820265
233587,1006028,162442,1,1,4,0,4,0,1,16,0,2,0.034448,0.118215
233588,1006030,129842,1,2,17,2,1,1,6,8,15,3,0.069979,0.287093
233589,1006030,241442,1,2,17,2,1,1,2,15,0,2,0.069979,0.065139
233590,1006032,252442,1,4,7,0,3,0,8,0,0,1,0.049090,0.107358
233591,1006033,127642,1,5,13,1,1,1,1,2,15,3,0.047627,0.437877
233592,1006035,135742,0,2,1,2,3,0,6,8,0,2,0.090790,0.184560
233593,1006036,255442,0,2,15,1,4,1,8,0,0,1,0.390632,0.009650
233594,1006036,118942,0,2,15,1,4,1,8,0,0,1,0.390632,0.090470
233595,1006036,254642,0,2,15,1,4,1,5,8,0,2,0.390632,0.083233
233596,1006036,31842,0,2,15,1,4,1,1,5,12,3,0.390632,0.094089
233597,1006037,124742,0,4,1,2,4,0,10,16,0,2,0.106249,0.102533
233598,1006039,316642,0,4,0,1,4,1,4,5,0,2,0.056024,0.200241

In [24]:
x_train = train_data.iloc[:, 0:14]

In [25]:
x_train

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Category_Count,Product_Score,User_Score
0,1000001,69042,0,0,10,0,2,0,3,0,0,1,0.120745,0.031707
1,1000001,248942,0,0,10,0,2,0,1,6,14,3,0.309043,0.031707
2,1000001,87842,0,0,10,0,2,0,12,0,0,1,0.054255,0.031707
3,1000001,85442,0,0,10,0,2,0,12,14,0,2,0.181383,0.031707
4,1000002,285442,1,6,16,2,4,0,8,0,0,1,0.107979,0.076917
5,1000003,193542,1,2,15,0,3,0,1,2,0,2,0.327128,0.032423
6,1000004,184942,1,4,7,1,2,1,1,8,17,3,0.765957,0.019595
7,1000004,346142,1,4,7,1,2,1,1,15,0,2,0.315426,0.019595
8,1000004,97242,1,4,7,1,2,1,1,16,0,2,0.485106,0.019595
9,1000005,274942,1,2,20,0,1,1,8,0,0,1,0.421809,0.077917
10,1000005,251242,1,2,20,0,1,1,5,11,0,2,0.631383,0.077917
11,1000005,14542,1,2,20,0,1,1,8,0,0,1,0.357447,0.077917
12,1000005,31342,1,2,20,0,1,1,8,0,0,1,0.019149,0.077917
13,1000005,145042,1,2,20,0,1,1,1,2,5,3,0.747872,0.077917
14,1000006,231342,0,5,9,0,1,0,5,8,14,3,0.044149,0.036057
15,1000006,190242,0,5,9,0,1,0,4,5,0,2,0.101064,0.036057
16,1000006,96642,0,5,9,0,1,0,2,3,4,3,0.092553,0.036057
17,1000006,58442,0,5,9,0,1,0,5,14,0,2,0.293617,0.036057
18,1000007,36842,1,3,1,1,1,1,1,14,16,3,0.470213,0.022271
19,1000008,249542,1,2,12,2,4,1,1,5,15,3,0.417553,0.075600
20,1000008,220442,1,2,12,2,4,1,5,14,0,2,0.681915,0.075600
21,1000008,156442,1,2,12,2,4,1,8,0,0,1,0.444149,0.075600
22,1000008,213742,1,2,12,2,4,1,8,0,0,1,0.186702,0.075600
23,1000008,214442,1,2,12,2,4,1,8,0,0,1,0.267021,0.075600
24,1000008,303442,1,2,12,2,4,1,1,8,14,3,0.189362,0.075600
25,1000009,135742,1,2,17,2,0,0,6,8,0,2,0.218085,0.056383
26,1000009,39942,1,2,17,2,0,0,8,0,0,1,0.088830,0.056383
27,1000009,161442,1,2,17,2,0,0,5,14,0,2,0.267553,0.056383
28,1000009,78742,1,2,17,2,0,0,5,8,14,3,0.150000,0.056383
29,1000010,85942,0,3,1,1,4,1,2,4,8,3,0.512234,0.205896
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
550038,1005995,375436,0,3,1,2,2,1,20,0,0,1,0.432979,0.096327
550039,1005996,371644,0,2,0,1,1,1,20,0,0,1,0.478191,0.286774
550040,1005997,370853,0,2,7,0,3,0,19,0,0,1,0.435106,0.038885
550041,1006000,371644,1,4,17,1,2,1,20,0,0,1,0.478191,0.225181
550042,1006002,371644,1,5,0,2,1,1,20,0,0,1,0.478191,0.174953
550043,1006003,370293,0,4,17,2,1,0,19,0,0,1,0.417553,0.152510
550044,1006004,370853,0,2,15,2,2,0,19,0,0,1,0.435106,0.030968
550045,1006005,371644,0,2,5,2,2,1,20,0,0,1,0.478191,0.035107
550046,1006006,375436,0,0,0,2,1,0,20,0,0,1,0.432979,0.048868
550047,1006009,372445,0,2,12,2,3,0,20,0,0,1,0.445213,0.026471
550048,1006010,371644,1,3,0,2,1,0,20,0,0,1,0.478191,0.183565
550049,1006011,375436,1,3,15,2,3,0,20,0,0,1,0.432979,0.113763
550050,1006012,371644,1,3,15,2,4,1,20,0,0,1,0.478191,0.012140
550051,1006013,375436,0,2,20,2,3,0,20,0,0,1,0.432979,0.059111
550052,1006016,375436,1,4,1,1,1,1,20,0,0,1,0.432979,0.357882
550053,1006017,371644,0,3,7,1,1,0,20,0,0,1,0.478191,0.015207
550054,1006018,370293,1,3,1,2,3,0,19,0,0,1,0.417553,0.092587
550055,1006019,372445,1,2,0,0,4,0,20,0,0,1,0.445213,0.057376
550056,1006022,375436,1,2,17,2,4,0,20,0,0,1,0.432979,0.026408
550057,1006023,370853,1,2,0,2,2,1,19,0,0,1,0.435106,0.115993
550058,1006024,372445,1,2,12,0,0,1,20,0,0,1,0.445213,0.078540
550059,1006025,370853,0,2,1,1,1,0,19,0,0,1,0.435106,0.098725
550060,1006026,371644,1,3,6,2,1,1,20,0,0,1,0.478191,0.046576
550061,1006029,372445,0,2,1,2,1,1,20,0,0,1,0.445213,0.014941
550062,1006032,372445,1,4,7,0,3,0,20,0,0,1,0.445213,0.049090
550063,1006033,372445,1,5,13,1,1,1,20,0,0,1,0.445213,0.047627
550064,1006035,375436,0,2,1,2,3,0,20,0,0,1,0.432979,0.090790
550065,1006036,375436,0,2,15,1,4,1,20,0,0,1,0.432979,0.390632
550066,1006038,375436,0,6,1,2,2,0,20,0,0,1,0.432979,0.008545
550067,1006039,371644,0,4,0,1,4,1,20,0,0,1,0.478191,0.056024

In [22]:
y_train = train_data.iloc[:, 14]

In [23]:
y_train

0          8370
1         15200
2          1422
3          1057
4          7969
5         15227
6         19215
7         15854
8         15686
9          7871
10         5254
11         3957
12         6073
13        15665
14         5378
15         2079
16        13055
17         8851
18        11788
19        19614
20         8584
21         9872
22         9743
23         5982
24        11927
25        16662
26         5887
27         6973
28         5391
29        16352
          ...
550038      596
550039      595
550040       26
550041      488
550042      243
550043       48
550044       62
550045      252
550046      236
550047      244
550048      591
550049      473
550050      368
550051      489
550052      239
550053      371
550054       60
550055      238
550056      254
550057       61
550058      121
550059       48
550060      494
550061      599
550062      473
550063      368
550064      371
550065      137
550066      365
550067      490
Name: Purchase, Length: 550068, dtype: int64

In [26]:
from sklearn.ensemble import RandomForestRegressor

In [27]:
regr = RandomForestRegressor()
regr.fit(x_train, y_train)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
           oob_score=False, random_state=None, verbose=0, warm_start=False)

In [28]:
result = regr.predict(test_data)
result

array([10734.7,  9691.9,  6302.6, ..., 11724.1, 17006.7,  1636.5])

In [32]:
finalSolution = test_data[['User_ID', 'Product_ID']]

In [33]:
finalSolution

        User_ID  Product_ID
0       1000004      128942
1       1000009      113442
2       1000010      288442
3       1000010      145342
4       1000011       53842
5       1000013      350442
6       1000013      155442
7       1000013       94542
8       1000015      161842
9       1000022       67942
10      1000026       46742
11      1000026       40042
12      1000026      196542
13      1000026        4542
14      1000028      159542
15      1000029      111542
16      1000033      121042
17      1000033      344442
18      1000034      265242
19      1000035       96642
20      1000036      303042
21      1000036       59642
22      1000042       30842
23      1000045      346442
24      1000045      357242
25      1000045      284742
26      1000048      110842
27      1000048      251642
28      1000053      136742
29      1000053       97342
...         ...         ...
233569  1005996      184242
233570  1005996       45342
233571  1006001      124642
233572  1006002      121142
233573  1006002      233542
233574  1006002      226342
233575  1006002      284842
233576  1006003      313342
233577  1006010      223542
233578  1006013       20342
233579  1006016       14842
233580  1006016      109542
233581  1006018       71442
233582  1006021      112542
233583  1006021        3442
233584  1006023      262242
233585  1006025      161142
233586  1006026      110742
233587  1006028      162442
233588  1006030      129842
233589  1006030      241442
233590  1006032      252442
233591  1006033      127642
233592  1006035      135742
233593  1006036      255442
233594  1006036      118942
233595  1006036      254642
233596  1006036       31842
233597  1006037      124742
233598  1006039      316642

[233599 rows x 2 columns]

In [34]:
finalSolution['Purchase'] = result

/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':

In [35]:
finalSolution

        User_ID  Product_ID  Purchase
0       1000004      128942   10734.7
1       1000009      113442    9691.9
2       1000010      288442    6302.6
3       1000010      145342    2389.5
4       1000011       53842    1566.0
5       1000013      350442   10738.3
6       1000013      155442   11438.1
7       1000013       94542    8703.8
8       1000015      161842   11124.1
9       1000022       67942    5497.0
10      1000026       46742   11777.7
11      1000026       40042    4333.5
12      1000026      196542    6217.4
13      1000026        4542    5006.3
14      1000028      159542   13916.5
15      1000029      111542   14280.7
16      1000033      121042   16139.1
17      1000033      344442    5156.0
18      1000034      265242    7354.1
19      1000035       96642    9192.5
20      1000036      303042    6344.9
21      1000036       59642   12058.5
22      1000042       30842   11679.7
23      1000045      346442   11094.9
24      1000045      357242    5108.3
25      1000045      284742    5840.8
26      1000048      110842   14020.9
27      1000048      251642   11366.2
28      1000053      136742   12212.1
29      1000053       97342   14016.5
...         ...         ...       ...
233569  1005996      184242   16435.4
233570  1005996       45342   14337.4
233571  1006001      124642   14704.5
233572  1006002      121142    9534.5
233573  1006002      233542   10995.7
233574  1006002      226342    4613.2
233575  1006002      284842   17349.7
233576  1006003      313342    5834.7
233577  1006010      223542   16627.2
233578  1006013       20342   12101.5
233579  1006016       14842   12978.1
233580  1006016      109542    7606.7
233581  1006018       71442   13552.7
233582  1006021      112542   15585.3
233583  1006021        3442    1829.8
233584  1006023      262242   10989.4
233585  1006025      161142    2702.6
233586  1006026      110742   14108.0
233587  1006028      162442   12459.4
233588  1006030      129842   13996.0
233589  1006030      241442    8326.7
233590  1006032      252442    5826.3
233591  1006033      127642   12503.1
233592  1006035      135742   12276.8
233593  1006036      255442    8007.8
233594  1006036      118942    6781.7
233595  1006036      254642    6450.5
233596  1006036       31842   11724.1
233597  1006037      124742   17006.7
233598  1006039      316642    1636.5

[233599 rows x 3 columns]

In [36]:
finalSolution.to_csv('Result.csv')

In [37]:
from sklearn import linear_model

In [38]:
lm = linear_model.LinearRegression()

In [39]:
model = lm.fit(x_train, y_train)

In [40]:
prediction = lm.predict(test_data)

In [41]:
prediction

array([ 9548.53929375,  9124.74226874,  8171.03946063, ...,
       12251.95294813,  6881.3319641 ,  8152.71808126])