In [1]:
import warnings

In [2]:
import numpy as np
import pandas as pd

In [3]:
train_data = pd.read_csv('TrainDataSet.csv')

In [4]:
test_data = pd.read_csv('TestDataSet.csv')

In [5]:
train_data

,Unnamed: 0,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Category_Count,Product_Score,User_Score,Purchase
0,0,1000001,69042,0,0,10,0,2,0,3,0,0,1,0.120745,0.031707,8370
1,1,1000001,248942,0,0,10,0,2,0,1,6,14,3,0.309043,0.031707,15200
2,2,1000001,87842,0,0,10,0,2,0,12,0,0,1,0.054255,0.031707,1422
3,3,1000001,85442,0,0,10,0,2,0,12,14,0,2,0.181383,0.031707,1057
4,4,1000002,285442,1,6,16,2,4,0,8,0,0,1,0.107979,0.076917,7969
5,5,1000003,193542,1,2,15,0,3,0,1,2,0,2,0.327128,0.032423,15227
6,6,1000004,184942,1,4,7,1,2,1,1,8,17,3,0.765957,0.019595,19215
7,7,1000004,346142,1,4,7,1,2,1,1,15,0,2,0.315426,0.019595,15854
8,8,1000004,97242,1,4,7,1,2,1,1,16,0,2,0.485106,0.019595,15686
9,9,1000005,274942,1,2,20,0,1,1,8,0,0,1,0.421809,0.077917,7871
10,10,1000005,251242,1,2,20,0,1,1,5,11,0,2,0.631383,0.077917,5254
11,11,1000005,14542,1,2,20,0,1,1,8,0,0,1,0.357447,0.077917,3957
12,12,1000005,31342,1,2,20,0,1,1,8,0,0,1,0.019149,0.077917,6073
13,13,1000005,145042,1,2,20,0,1,1,1,2,5,3,0.747872,0.077917,15665
14,14,1000006,231342,0,5,9,0,1,0,5,8,14,3,0.044149,0.036057,5378
15,15,1000006,190242,0,5,9,0,1,0,4,5,0,2,0.101064,0.036057,2079
16,16,1000006,96642,0,5,9,0,1,0,2,3,4,3,0.092553,0.036057,13055
17,17,1000006,58442,0,5,9,0,1,0,5,14,0,2,0.293617,0.036057,8851
18,18,1000007,36842,1,3,1,1,1,1,1,14,16,3,0.470213,0.022271,11788
19,19,1000008,249542,1,2,12,2,4,1,1,5,15,3,0.417553,0.075600,19614
20,20,1000008,220442,1,2,12,2,4,1,5,14,0,2,0.681915,0.075600,8584
21,21,1000008,156442,1,2,12,2,4,1,8,0,0,1,0.444149,0.075600,9872
22,22,1000008,213742,1,2,12,2,4,1,8,0,0,1,0.186702,0.075600,9743
23,23,1000008,214442,1,2,12,2,4,1,8,0,0,1,0.267021,0.075600,5982
24,24,1000008,303442,1,2,12,2,4,1,1,8,14,3,0.189362,0.075600,11927
25,25,1000009,135742,1,2,17,2,0,0,6,8,0,2,0.218085,0.056383,16662
26,26,1000009,39942,1,2,17,2,0,0,8,0,0,1,0.088830,0.056383,5887
27,27,1000009,161442,1,2,17,2,0,0,5,14,0,2,0.267553,0.056383,6973
28,28,1000009,78742,1,2,17,2,0,0,5,8,14,3,0.150000,0.056383,5391
29,29,1000010,85942,0,3,1,1,4,1,2,4,8,3,0.512234,0.205896,16352
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
550038,550038,1005995,375436,0,3,1,2,2,1,20,0,0,1,0.432979,0.096327,596
550039,550039,1005996,371644,0,2,0,1,1,1,20,0,0,1,0.478191,0.286774,595
550040,550040,1005997,370853,0,2,7,0,3,0,19,0,0,1,0.435106,0.038885,26
550041,550041,1006000,371644,1,4,17,1,2,1,20,0,0,1,0.478191,0.225181,488
550042,550042,1006002,371644,1,5,0,2,1,1,20,0,0,1,0.478191,0.174953,243
550043,550043,1006003,370293,0,4,17,2,1,0,19,0,0,1,0.417553,0.152510,48
550044,550044,1006004,370853,0,2,15,2,2,0,19,0,0,1,0.435106,0.030968,62
550045,550045,1006005,371644,0,2,5,2,2,1,20,0,0,1,0.478191,0.035107,252
550046,550046,1006006,375436,0,0,0,2,1,0,20,0,0,1,0.432979,0.048868,236
550047,550047,1006009,372445,0,2,12,2,3,0,20,0,0,1,0.445213,0.026471,244
550048,550048,1006010,371644,1,3,0,2,1,0,20,0,0,1,0.478191,0.183565,591
550049,550049,1006011,375436,1,3,15,2,3,0,20,0,0,1,0.432979,0.113763,473
550050,550050,1006012,371644,1,3,15,2,4,1,20,0,0,1,0.478191,0.012140,368
550051,550051,1006013,375436,0,2,20,2,3,0,20,0,0,1,0.432979,0.059111,489
550052,550052,1006016,375436,1,4,1,1,1,1,20,0,0,1,0.432979,0.357882,239
550053,550053,1006017,371644,0,3,7,1,1,0,20,0,0,1,0.478191,0.015207,371
550054,550054,1006018,370293,1,3,1,2,3,0,19,0,0,1,0.417553,0.092587,60
550055,550055,1006019,372445,1,2,0,0,4,0,20,0,0,1,0.445213,0.057376,238
550056,550056,1006022,375436,1,2,17,2,4,0,20,0,0,1,0.432979,0.026408,254
550057,550057,1006023,370853,1,2,0,2,2,1,19,0,0,1,0.435106,0.115993,61
550058,550058,1006024,372445,1,2,12,0,0,1,20,0,0,1,0.445213,0.078540,121
550059,550059,1006025,370853,0,2,1,1,1,0,19,0,0,1,0.435106,0.098725,48
550060,550060,1006026,371644,1,3,6,2,1,1,20,0,0,1,0.478191,0.046576,494
550061,550061,1006029,372445,0,2,1,2,1,1,20,0,0,1,0.445213,0.014941,599
550062,550062,1006032,372445,1,4,7,0,3,0,20,0,0,1,0.445213,0.049090,473
550063,550063,1006033,372445,1,5,13,1,1,1,20,0,0,1,0.445213,0.047627,368
550064,550064,1006035,375436,0,2,1,2,3,0,20,0,0,1,0.432979,0.090790,371
550065,550065,1006036,375436,0,2,15,1,4,1,20,0,0,1,0.432979,0.390632,137
550066,550066,1006038,375436,0,6,1,2,2,0,20,0,0,1,0.432979,0.008545,365
550067,550067,1006039,371644,0,4,0,1,4,1,20,0,0,1,0.478191,0.056024,490

In [6]:
train_data = train_data.drop(['Unnamed: 0'], axis=1)

In [7]:
train_data

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Category_Count,Product_Score,User_Score,Purchase
0,1000001,69042,0,0,10,0,2,0,3,0,0,1,0.120745,0.031707,8370
1,1000001,248942,0,0,10,0,2,0,1,6,14,3,0.309043,0.031707,15200
2,1000001,87842,0,0,10,0,2,0,12,0,0,1,0.054255,0.031707,1422
3,1000001,85442,0,0,10,0,2,0,12,14,0,2,0.181383,0.031707,1057
4,1000002,285442,1,6,16,2,4,0,8,0,0,1,0.107979,0.076917,7969
5,1000003,193542,1,2,15,0,3,0,1,2,0,2,0.327128,0.032423,15227
6,1000004,184942,1,4,7,1,2,1,1,8,17,3,0.765957,0.019595,19215
7,1000004,346142,1,4,7,1,2,1,1,15,0,2,0.315426,0.019595,15854
8,1000004,97242,1,4,7,1,2,1,1,16,0,2,0.485106,0.019595,15686
9,1000005,274942,1,2,20,0,1,1,8,0,0,1,0.421809,0.077917,7871
10,1000005,251242,1,2,20,0,1,1,5,11,0,2,0.631383,0.077917,5254
11,1000005,14542,1,2,20,0,1,1,8,0,0,1,0.357447,0.077917,3957
12,1000005,31342,1,2,20,0,1,1,8,0,0,1,0.019149,0.077917,6073
13,1000005,145042,1,2,20,0,1,1,1,2,5,3,0.747872,0.077917,15665
14,1000006,231342,0,5,9,0,1,0,5,8,14,3,0.044149,0.036057,5378
15,1000006,190242,0,5,9,0,1,0,4,5,0,2,0.101064,0.036057,2079
16,1000006,96642,0,5,9,0,1,0,2,3,4,3,0.092553,0.036057,13055
17,1000006,58442,0,5,9,0,1,0,5,14,0,2,0.293617,0.036057,8851
18,1000007,36842,1,3,1,1,1,1,1,14,16,3,0.470213,0.022271,11788
19,1000008,249542,1,2,12,2,4,1,1,5,15,3,0.417553,0.075600,19614
20,1000008,220442,1,2,12,2,4,1,5,14,0,2,0.681915,0.075600,8584
21,1000008,156442,1,2,12,2,4,1,8,0,0,1,0.444149,0.075600,9872
22,1000008,213742,1,2,12,2,4,1,8,0,0,1,0.186702,0.075600,9743
23,1000008,214442,1,2,12,2,4,1,8,0,0,1,0.267021,0.075600,5982
24,1000008,303442,1,2,12,2,4,1,1,8,14,3,0.189362,0.075600,11927
25,1000009,135742,1,2,17,2,0,0,6,8,0,2,0.218085,0.056383,16662
26,1000009,39942,1,2,17,2,0,0,8,0,0,1,0.088830,0.056383,5887
27,1000009,161442,1,2,17,2,0,0,5,14,0,2,0.267553,0.056383,6973
28,1000009,78742,1,2,17,2,0,0,5,8,14,3,0.150000,0.056383,5391
29,1000010,85942,0,3,1,1,4,1,2,4,8,3,0.512234,0.205896,16352
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
550038,1005995,375436,0,3,1,2,2,1,20,0,0,1,0.432979,0.096327,596
550039,1005996,371644,0,2,0,1,1,1,20,0,0,1,0.478191,0.286774,595
550040,1005997,370853,0,2,7,0,3,0,19,0,0,1,0.435106,0.038885,26
550041,1006000,371644,1,4,17,1,2,1,20,0,0,1,0.478191,0.225181,488
550042,1006002,371644,1,5,0,2,1,1,20,0,0,1,0.478191,0.174953,243
550043,1006003,370293,0,4,17,2,1,0,19,0,0,1,0.417553,0.152510,48
550044,1006004,370853,0,2,15,2,2,0,19,0,0,1,0.435106,0.030968,62
550045,1006005,371644,0,2,5,2,2,1,20,0,0,1,0.478191,0.035107,252
550046,1006006,375436,0,0,0,2,1,0,20,0,0,1,0.432979,0.048868,236
550047,1006009,372445,0,2,12,2,3,0,20,0,0,1,0.445213,0.026471,244
550048,1006010,371644,1,3,0,2,1,0,20,0,0,1,0.478191,0.183565,591
550049,1006011,375436,1,3,15,2,3,0,20,0,0,1,0.432979,0.113763,473
550050,1006012,371644,1,3,15,2,4,1,20,0,0,1,0.478191,0.012140,368
550051,1006013,375436,0,2,20,2,3,0,20,0,0,1,0.432979,0.059111,489
550052,1006016,375436,1,4,1,1,1,1,20,0,0,1,0.432979,0.357882,239
550053,1006017,371644,0,3,7,1,1,0,20,0,0,1,0.478191,0.015207,371
550054,1006018,370293,1,3,1,2,3,0,19,0,0,1,0.417553,0.092587,60
550055,1006019,372445,1,2,0,0,4,0,20,0,0,1,0.445213,0.057376,238
550056,1006022,375436,1,2,17,2,4,0,20,0,0,1,0.432979,0.026408,254
550057,1006023,370853,1,2,0,2,2,1,19,0,0,1,0.435106,0.115993,61
550058,1006024,372445,1,2,12,0,0,1,20,0,0,1,0.445213,0.078540,121
550059,1006025,370853,0,2,1,1,1,0,19,0,0,1,0.435106,0.098725,48
550060,1006026,371644,1,3,6,2,1,1,20,0,0,1,0.478191,0.046576,494
550061,1006029,372445,0,2,1,2,1,1,20,0,0,1,0.445213,0.014941,599
550062,1006032,372445,1,4,7,0,3,0,20,0,0,1,0.445213,0.049090,473
550063,1006033,372445,1,5,13,1,1,1,20,0,0,1,0.445213,0.047627,368
550064,1006035,375436,0,2,1,2,3,0,20,0,0,1,0.432979,0.090790,371
550065,1006036,375436,0,2,15,1,4,1,20,0,0,1,0.432979,0.390632,137
550066,1006038,375436,0,6,1,2,2,0,20,0,0,1,0.432979,0.008545,365
550067,1006039,371644,0,4,0,1,4,1,20,0,0,1,0.478191,0.056024,490

In [8]:
train_data.dtypes

User_ID                         int64
Product_ID                      int64
Gender                          int64
Age                             int64
Occupation                      int64
City_Category                   int64
Stay_In_Current_City_Years      int64
Marital_Status                  int64
Product_Category_1              int64
Product_Category_2              int64
Product_Category_3              int64
Category_Count                  int64
Product_Score                 float64
User_Score                    float64
Purchase                        int64
dtype: object

In [9]:
test_data

,Unnamed: 0,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Category_Count,User_Score,Product_Score
0,0,1000004,128942,1,4,7,1,2,1,1,11,0,2,0.019595,0.478890
1,1,1000009,113442,1,2,17,2,0,0,3,5,0,2,0.056383,0.141134
2,2,1000010,288442,0,3,1,1,4,1,5,14,0,2,0.205896,0.090470
3,3,1000010,145342,0,3,1,1,4,1,4,9,0,2,0.205896,0.009650
4,4,1000011,53842,0,2,1,2,1,0,4,5,12,3,0.052864,0.258142
5,5,1000013,350442,1,4,1,2,3,1,2,3,15,3,0.067755,0.142340
6,6,1000013,155442,1,4,1,2,3,1,1,11,15,3,0.067755,0.214717
7,7,1000013,94542,1,4,1,2,3,1,2,4,9,3,0.067755,0.082027
8,8,1000015,161842,1,2,7,0,1,0,10,13,16,3,0.099434,0.050663
9,9,1000022,67942,1,1,15,0,4,0,5,14,0,2,0.121470,0.183353
10,10,1000026,46742,1,2,7,1,2,1,1,2,15,3,0.152433,0.779252
11,11,1000026,40042,1,2,7,1,2,1,5,0,0,1,0.152433,0.059107
12,12,1000026,196542,1,2,7,1,2,1,5,8,14,3,0.152433,0.212304
13,13,1000026,4542,1,2,7,1,2,1,5,8,0,2,0.152433,0.155609
14,14,1000028,159542,0,2,1,2,2,1,10,15,16,3,0.049024,0.242461
15,15,1000029,111542,1,3,7,2,1,0,2,17,0,2,0.066073,0.255730
16,16,1000033,121042,1,4,3,0,1,1,15,0,0,1,0.184154,0.121834
17,17,1000033,344442,1,4,3,0,1,1,5,8,14,3,0.184154,0.162847
18,18,1000034,265242,0,1,0,0,0,0,5,8,0,2,0.076681,1.000000
19,19,1000035,96642,1,4,1,2,4,1,2,3,4,3,0.077945,0.094089
20,20,1000036,303042,1,2,3,1,0,0,5,0,0,1,0.219853,0.334138
21,21,1000036,59642,1,2,3,1,0,0,1,2,3,3,0.219853,0.184560
22,22,1000042,30842,1,2,8,2,0,1,1,2,15,3,0.140747,0.322075
23,23,1000045,346442,0,4,16,0,1,1,1,2,14,3,0.088118,0.124246
24,24,1000045,357242,0,4,16,0,1,1,5,0,0,1,0.088118,0.055489
25,25,1000045,284742,0,4,16,0,1,1,5,12,0,2,0.088118,0.069964
26,26,1000048,110842,1,2,4,1,3,1,1,2,5,3,0.264642,0.667069
27,27,1000048,251642,1,2,4,1,3,1,1,2,4,3,0.264642,0.120627
28,28,1000053,136742,1,2,0,1,1,0,1,14,16,3,0.405277,0.155609
29,29,1000053,97342,1,2,0,1,1,0,1,15,16,3,0.405277,0.149578
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
233569,233569,1005996,184242,0,2,0,1,1,1,9,15,0,2,0.286774,0.234017
233570,233570,1005996,45342,0,2,0,1,1,1,1,5,17,3,0.286774,0.174910
233571,233571,1006001,124642,0,2,7,0,0,1,16,0,0,1,0.119326,0.173703
233572,233572,1006002,121142,1,5,0,2,1,1,8,0,0,1,0.174953,0.178528
233573,233573,1006002,233542,1,5,0,2,1,1,1,15,0,2,0.174953,0.323281
233574,233574,1006002,226342,1,5,0,2,1,1,11,15,0,2,0.174953,0.316043
233575,233575,1006002,284842,1,5,0,2,1,1,1,8,17,3,0.174953,0.095296
233576,233576,1006003,313342,0,4,17,2,1,0,5,0,0,1,0.152510,0.313631
233577,233577,1006010,223542,1,3,0,2,1,0,1,8,17,3,0.183565,0.208685
233578,233578,1006013,20342,0,2,20,2,3,0,1,2,0,2,0.059111,0.186972
233579,233579,1006016,14842,1,4,1,1,1,1,1,2,5,3,0.357882,0.235223
233580,233580,1006016,109542,1,4,1,1,1,1,8,14,17,3,0.357882,0.243667
233581,233581,1006018,71442,1,3,1,2,3,0,15,17,0,2,0.092587,0.404101
233582,233582,1006021,112542,1,2,12,1,2,1,1,11,15,3,0.067330,0.595899
233583,233583,1006021,3442,1,2,12,1,2,1,4,5,8,3,0.067330,0.469240
233584,233584,1006023,262242,1,2,0,2,2,1,1,11,16,3,0.115993,0.211098
233585,233585,1006025,161142,0,2,1,1,1,0,11,0,0,1,0.098725,0.013269
233586,233586,1006026,110742,1,3,6,2,1,1,1,2,8,3,0.046576,0.820265
233587,233587,1006028,162442,1,1,4,0,4,0,1,16,0,2,0.034448,0.118215
233588,233588,1006030,129842,1,2,17,2,1,1,6,8,15,3,0.069979,0.287093
233589,233589,1006030,241442,1,2,17,2,1,1,2,15,0,2,0.069979,0.065139
233590,233590,1006032,252442,1,4,7,0,3,0,8,0,0,1,0.049090,0.107358
233591,233591,1006033,127642,1,5,13,1,1,1,1,2,15,3,0.047627,0.437877
233592,233592,1006035,135742,0,2,1,2,3,0,6,8,0,2,0.090790,0.184560
233593,233593,1006036,255442,0,2,15,1,4,1,8,0,0,1,0.390632,0.009650
233594,233594,1006036,118942,0,2,15,1,4,1,8,0,0,1,0.390632,0.090470
233595,233595,1006036,254642,0,2,15,1,4,1,5,8,0,2,0.390632,0.083233
233596,233596,1006036,31842,0,2,15,1,4,1,1,5,12,3,0.390632,0.094089
233597,233597,1006037,124742,0,4,1,2,4,0,10,16,0,2,0.106249,0.102533
233598,233598,1006039,316642,0,4,0,1,4,1,4,5,0,2,0.056024,0.200241

In [10]:
test_data = test_data.drop(['Unnamed: 0'], axis=1)

In [11]:
test_data

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Category_Count,User_Score,Product_Score
0,1000004,128942,1,4,7,1,2,1,1,11,0,2,0.019595,0.478890
1,1000009,113442,1,2,17,2,0,0,3,5,0,2,0.056383,0.141134
2,1000010,288442,0,3,1,1,4,1,5,14,0,2,0.205896,0.090470
3,1000010,145342,0,3,1,1,4,1,4,9,0,2,0.205896,0.009650
4,1000011,53842,0,2,1,2,1,0,4,5,12,3,0.052864,0.258142
5,1000013,350442,1,4,1,2,3,1,2,3,15,3,0.067755,0.142340
6,1000013,155442,1,4,1,2,3,1,1,11,15,3,0.067755,0.214717
7,1000013,94542,1,4,1,2,3,1,2,4,9,3,0.067755,0.082027
8,1000015,161842,1,2,7,0,1,0,10,13,16,3,0.099434,0.050663
9,1000022,67942,1,1,15,0,4,0,5,14,0,2,0.121470,0.183353
10,1000026,46742,1,2,7,1,2,1,1,2,15,3,0.152433,0.779252
11,1000026,40042,1,2,7,1,2,1,5,0,0,1,0.152433,0.059107
12,1000026,196542,1,2,7,1,2,1,5,8,14,3,0.152433,0.212304
13,1000026,4542,1,2,7,1,2,1,5,8,0,2,0.152433,0.155609
14,1000028,159542,0,2,1,2,2,1,10,15,16,3,0.049024,0.242461
15,1000029,111542,1,3,7,2,1,0,2,17,0,2,0.066073,0.255730
16,1000033,121042,1,4,3,0,1,1,15,0,0,1,0.184154,0.121834
17,1000033,344442,1,4,3,0,1,1,5,8,14,3,0.184154,0.162847
18,1000034,265242,0,1,0,0,0,0,5,8,0,2,0.076681,1.000000
19,1000035,96642,1,4,1,2,4,1,2,3,4,3,0.077945,0.094089
20,1000036,303042,1,2,3,1,0,0,5,0,0,1,0.219853,0.334138
21,1000036,59642,1,2,3,1,0,0,1,2,3,3,0.219853,0.184560
22,1000042,30842,1,2,8,2,0,1,1,2,15,3,0.140747,0.322075
23,1000045,346442,0,4,16,0,1,1,1,2,14,3,0.088118,0.124246
24,1000045,357242,0,4,16,0,1,1,5,0,0,1,0.088118,0.055489
25,1000045,284742,0,4,16,0,1,1,5,12,0,2,0.088118,0.069964
26,1000048,110842,1,2,4,1,3,1,1,2,5,3,0.264642,0.667069
27,1000048,251642,1,2,4,1,3,1,1,2,4,3,0.264642,0.120627
28,1000053,136742,1,2,0,1,1,0,1,14,16,3,0.405277,0.155609
29,1000053,97342,1,2,0,1,1,0,1,15,16,3,0.405277,0.149578
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
233569,1005996,184242,0,2,0,1,1,1,9,15,0,2,0.286774,0.234017
233570,1005996,45342,0,2,0,1,1,1,1,5,17,3,0.286774,0.174910
233571,1006001,124642,0,2,7,0,0,1,16,0,0,1,0.119326,0.173703
233572,1006002,121142,1,5,0,2,1,1,8,0,0,1,0.174953,0.178528
233573,1006002,233542,1,5,0,2,1,1,1,15,0,2,0.174953,0.323281
233574,1006002,226342,1,5,0,2,1,1,11,15,0,2,0.174953,0.316043
233575,1006002,284842,1,5,0,2,1,1,1,8,17,3,0.174953,0.095296
233576,1006003,313342,0,4,17,2,1,0,5,0,0,1,0.152510,0.313631
233577,1006010,223542,1,3,0,2,1,0,1,8,17,3,0.183565,0.208685
233578,1006013,20342,0,2,20,2,3,0,1,2,0,2,0.059111,0.186972
233579,1006016,14842,1,4,1,1,1,1,1,2,5,3,0.357882,0.235223
233580,1006016,109542,1,4,1,1,1,1,8,14,17,3,0.357882,0.243667
233581,1006018,71442,1,3,1,2,3,0,15,17,0,2,0.092587,0.404101
233582,1006021,112542,1,2,12,1,2,1,1,11,15,3,0.067330,0.595899
233583,1006021,3442,1,2,12,1,2,1,4,5,8,3,0.067330,0.469240
233584,1006023,262242,1,2,0,2,2,1,1,11,16,3,0.115993,0.211098
233585,1006025,161142,0,2,1,1,1,0,11,0,0,1,0.098725,0.013269
233586,1006026,110742,1,3,6,2,1,1,1,2,8,3,0.046576,0.820265
233587,1006028,162442,1,1,4,0,4,0,1,16,0,2,0.034448,0.118215
233588,1006030,129842,1,2,17,2,1,1,6,8,15,3,0.069979,0.287093
233589,1006030,241442,1,2,17,2,1,1,2,15,0,2,0.069979,0.065139
233590,1006032,252442,1,4,7,0,3,0,8,0,0,1,0.049090,0.107358
233591,1006033,127642,1,5,13,1,1,1,1,2,15,3,0.047627,0.437877
233592,1006035,135742,0,2,1,2,3,0,6,8,0,2,0.090790,0.184560
233593,1006036,255442,0,2,15,1,4,1,8,0,0,1,0.390632,0.009650
233594,1006036,118942,0,2,15,1,4,1,8,0,0,1,0.390632,0.090470
233595,1006036,254642,0,2,15,1,4,1,5,8,0,2,0.390632,0.083233
233596,1006036,31842,0,2,15,1,4,1,1,5,12,3,0.390632,0.094089
233597,1006037,124742,0,4,1,2,4,0,10,16,0,2,0.106249,0.102533
233598,1006039,316642,0,4,0,1,4,1,4,5,0,2,0.056024,0.200241

In [12]:
x_train = train_data.iloc[:, 0:14]

In [13]:
x_train

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Category_Count,Product_Score,User_Score
0,1000001,69042,0,0,10,0,2,0,3,0,0,1,0.120745,0.031707
1,1000001,248942,0,0,10,0,2,0,1,6,14,3,0.309043,0.031707
2,1000001,87842,0,0,10,0,2,0,12,0,0,1,0.054255,0.031707
3,1000001,85442,0,0,10,0,2,0,12,14,0,2,0.181383,0.031707
4,1000002,285442,1,6,16,2,4,0,8,0,0,1,0.107979,0.076917
5,1000003,193542,1,2,15,0,3,0,1,2,0,2,0.327128,0.032423
6,1000004,184942,1,4,7,1,2,1,1,8,17,3,0.765957,0.019595
7,1000004,346142,1,4,7,1,2,1,1,15,0,2,0.315426,0.019595
8,1000004,97242,1,4,7,1,2,1,1,16,0,2,0.485106,0.019595
9,1000005,274942,1,2,20,0,1,1,8,0,0,1,0.421809,0.077917
10,1000005,251242,1,2,20,0,1,1,5,11,0,2,0.631383,0.077917
11,1000005,14542,1,2,20,0,1,1,8,0,0,1,0.357447,0.077917
12,1000005,31342,1,2,20,0,1,1,8,0,0,1,0.019149,0.077917
13,1000005,145042,1,2,20,0,1,1,1,2,5,3,0.747872,0.077917
14,1000006,231342,0,5,9,0,1,0,5,8,14,3,0.044149,0.036057
15,1000006,190242,0,5,9,0,1,0,4,5,0,2,0.101064,0.036057
16,1000006,96642,0,5,9,0,1,0,2,3,4,3,0.092553,0.036057
17,1000006,58442,0,5,9,0,1,0,5,14,0,2,0.293617,0.036057
18,1000007,36842,1,3,1,1,1,1,1,14,16,3,0.470213,0.022271
19,1000008,249542,1,2,12,2,4,1,1,5,15,3,0.417553,0.075600
20,1000008,220442,1,2,12,2,4,1,5,14,0,2,0.681915,0.075600
21,1000008,156442,1,2,12,2,4,1,8,0,0,1,0.444149,0.075600
22,1000008,213742,1,2,12,2,4,1,8,0,0,1,0.186702,0.075600
23,1000008,214442,1,2,12,2,4,1,8,0,0,1,0.267021,0.075600
24,1000008,303442,1,2,12,2,4,1,1,8,14,3,0.189362,0.075600
25,1000009,135742,1,2,17,2,0,0,6,8,0,2,0.218085,0.056383
26,1000009,39942,1,2,17,2,0,0,8,0,0,1,0.088830,0.056383
27,1000009,161442,1,2,17,2,0,0,5,14,0,2,0.267553,0.056383
28,1000009,78742,1,2,17,2,0,0,5,8,14,3,0.150000,0.056383
29,1000010,85942,0,3,1,1,4,1,2,4,8,3,0.512234,0.205896
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
550038,1005995,375436,0,3,1,2,2,1,20,0,0,1,0.432979,0.096327
550039,1005996,371644,0,2,0,1,1,1,20,0,0,1,0.478191,0.286774
550040,1005997,370853,0,2,7,0,3,0,19,0,0,1,0.435106,0.038885
550041,1006000,371644,1,4,17,1,2,1,20,0,0,1,0.478191,0.225181
550042,1006002,371644,1,5,0,2,1,1,20,0,0,1,0.478191,0.174953
550043,1006003,370293,0,4,17,2,1,0,19,0,0,1,0.417553,0.152510
550044,1006004,370853,0,2,15,2,2,0,19,0,0,1,0.435106,0.030968
550045,1006005,371644,0,2,5,2,2,1,20,0,0,1,0.478191,0.035107
550046,1006006,375436,0,0,0,2,1,0,20,0,0,1,0.432979,0.048868
550047,1006009,372445,0,2,12,2,3,0,20,0,0,1,0.445213,0.026471
550048,1006010,371644,1,3,0,2,1,0,20,0,0,1,0.478191,0.183565
550049,1006011,375436,1,3,15,2,3,0,20,0,0,1,0.432979,0.113763
550050,1006012,371644,1,3,15,2,4,1,20,0,0,1,0.478191,0.012140
550051,1006013,375436,0,2,20,2,3,0,20,0,0,1,0.432979,0.059111
550052,1006016,375436,1,4,1,1,1,1,20,0,0,1,0.432979,0.357882
550053,1006017,371644,0,3,7,1,1,0,20,0,0,1,0.478191,0.015207
550054,1006018,370293,1,3,1,2,3,0,19,0,0,1,0.417553,0.092587
550055,1006019,372445,1,2,0,0,4,0,20,0,0,1,0.445213,0.057376
550056,1006022,375436,1,2,17,2,4,0,20,0,0,1,0.432979,0.026408
550057,1006023,370853,1,2,0,2,2,1,19,0,0,1,0.435106,0.115993
550058,1006024,372445,1,2,12,0,0,1,20,0,0,1,0.445213,0.078540
550059,1006025,370853,0,2,1,1,1,0,19,0,0,1,0.435106,0.098725
550060,1006026,371644,1,3,6,2,1,1,20,0,0,1,0.478191,0.046576
550061,1006029,372445,0,2,1,2,1,1,20,0,0,1,0.445213,0.014941
550062,1006032,372445,1,4,7,0,3,0,20,0,0,1,0.445213,0.049090
550063,1006033,372445,1,5,13,1,1,1,20,0,0,1,0.445213,0.047627
550064,1006035,375436,0,2,1,2,3,0,20,0,0,1,0.432979,0.090790
550065,1006036,375436,0,2,15,1,4,1,20,0,0,1,0.432979,0.390632
550066,1006038,375436,0,6,1,2,2,0,20,0,0,1,0.432979,0.008545
550067,1006039,371644,0,4,0,1,4,1,20,0,0,1,0.478191,0.056024

In [14]:
y_train = train_data.iloc[:, 14]

In [15]:
y_train

0          8370
1         15200
2          1422
3          1057
4          7969
5         15227
6         19215
7         15854
8         15686
9          7871
10         5254
11         3957
12         6073
13        15665
14         5378
15         2079
16        13055
17         8851
18        11788
19        19614
20         8584
21         9872
22         9743
23         5982
24        11927
25        16662
26         5887
27         6973
28         5391
29        16352
          ...
550038      596
550039      595
550040       26
550041      488
550042      243
550043       48
550044       62
550045      252
550046      236
550047      244
550048      591
550049      473
550050      368
550051      489
550052      239
550053      371
550054       60
550055      238
550056      254
550057       61
550058      121
550059       48
550060      494
550061      599
550062      473
550063      368
550064      371
550065      137
550066      365
550067      490
Name: Purchase, Length: 550068, dtype: int64

In [16]:
from sklearn.ensemble import RandomForestRegressor

In [107]:
test_data = test_data.drop(['Purchase'], axis=1)

In [109]:
regr = RandomForestRegressor(n_estimators=100, max_depth=7, n_jobs=-1)
regr.fit(x_train, y_train)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=7,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=-1,
           oob_score=False, random_state=None, verbose=0, warm_start=False)

In [110]:
result = regr.predict(test_data)
result

array([10225.38280524,  8366.6461263 ,  6338.82336828, ...,
       13871.6766243 , 18245.70750955,  1891.32331176])

In [112]:
test_data['Purchase'] = result

In [113]:
finalSolution = test_data[['User_ID', 'Product_ID', 'Purchase']]

In [114]:
finalSolution

        User_ID  Product_ID      Purchase
0       1000004      128942  10225.382805
1       1000009      113442   8366.646126
2       1000010      288442   6338.823368
3       1000010      145342   2532.417058
4       1000011       53842   1891.323312
5       1000013      350442  10440.335326
6       1000013      155442  11809.777326
7       1000013       94542  10217.574598
8       1000015      161842  18245.707510
9       1000022       67942   5890.343124
10      1000026       46742  11178.918780
11      1000026       40042   5935.711864
12      1000026      196542   6086.651267
13      1000026        4542   5935.711864
14      1000028      159542  18245.707510
15      1000029      111542  12756.605228
16      1000033      121042  14012.033756
17      1000033      344442   6318.710829
18      1000034      265242   6005.738758
19      1000035       96642  10287.536053
20      1000036      303042   6355.127735
21      1000036       59642  13535.447295
22      1000042       30842  11361.335389
23      1000045      346442  11678.652790
24      1000045      357242   6130.364325
25      1000045      284742   6130.364325
26      1000048      110842  14445.981262
27      1000048      251642  13487.719102
28      1000053      136742  13780.170042
29      1000053       97342  14600.470475
...         ...         ...           ...
233569  1005996      184242  18245.707510
233570  1005996       45342  14220.121827
233571  1006001      124642  14012.033756
233572  1006002      121142   7600.682955
233573  1006002      233542  12565.317588
233574  1006002      226342   5088.922966
233575  1006002      284842  14007.043297
233576  1006003      313342   6162.667764
233577  1006010      223542  13366.854287
233578  1006013       20342  11635.950986
233579  1006016       14842  13871.676624
233580  1006016      109542   7737.219382
233581  1006018       71442  13723.742545
233582  1006021      112542  11732.077364
233583  1006021        3442   2125.620528
233584  1006023      262242  11390.969753
233585  1006025      161142   4403.344358
233586  1006026      110742  11583.091817
233587  1006028      162442  10266.390854
233588  1006030      129842  14520.822498
233589  1006030      241442  10168.232037
233590  1006032      252442   7252.941123
233591  1006033      127642  10511.568900
233592  1006035      135742  15254.407703
233593  1006036      255442   7737.219382
233594  1006036      118942   7737.219382
233595  1006036      254642   6793.953569
233596  1006036       31842  13871.676624
233597  1006037      124742  18245.707510
233598  1006039      316642   1891.323312

[233599 rows x 3 columns]

In [115]:
finalSolution.to_csv('RandomForest.csv')

In [21]:
finalSolution['Purchase'] = result

/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':

In [22]:
finalSolution

        User_ID  Product_ID  Purchase
0       1000004      128942    8973.3
1       1000009      113442    9543.5
2       1000010      288442    6133.1
3       1000010      145342    2621.0
4       1000011       53842    2652.2
5       1000013      350442   11386.7
6       1000013      155442   13975.6
7       1000013       94542   10714.3
8       1000015      161842   16066.6
9       1000022       67942    4259.1
10      1000026       46742   10649.7
11      1000026       40042    4960.9
12      1000026      196542    5858.3
13      1000026        4542    5308.8
14      1000028      159542   17886.7
15      1000029      111542   10209.1
16      1000033      121042   17398.7
17      1000033      344442    4925.8
18      1000034      265242    6133.0
19      1000035       96642   10446.2
20      1000036      303042    5707.6
21      1000036       59642    9178.1
22      1000042       30842   13254.4
23      1000045      346442    9401.1
24      1000045      357242    4255.6
25      1000045      284742    4917.4
26      1000048      110842    8759.6
27      1000048      251642   13317.8
28      1000053      136742   14690.5
29      1000053       97342   15034.2
...         ...         ...       ...
233569  1005996      184242   18588.5
233570  1005996       45342   14903.2
233571  1006001      124642   15100.0
233572  1006002      121142    8010.8
233573  1006002      233542   14154.3
233574  1006002      226342    5425.7
233575  1006002      284842   15425.0
233576  1006003      313342    5814.3
233577  1006010      223542   16672.3
233578  1006013       20342   11691.0
233579  1006016       14842   13094.0
233580  1006016      109542    8355.8
233581  1006018       71442   13269.4
233582  1006021      112542   12482.9
233583  1006021        3442    1697.8
233584  1006023      262242   12501.6
233585  1006025      161142    3558.5
233586  1006026      110742   12726.8
233587  1006028      162442   11384.3
233588  1006030      129842   15162.7
233589  1006030      241442    8383.0
233590  1006032      252442    5633.1
233591  1006033      127642   14365.7
233592  1006035      135742   11397.1
233593  1006036      255442    8000.8
233594  1006036      118942    7587.0
233595  1006036      254642    7219.7
233596  1006036       31842   12386.6
233597  1006037      124742   22227.9
233598  1006039      316642    1818.3

[233599 rows x 3 columns]

In [23]:
finalSolution.to_csv('Result.csv')

In [24]:
from sklearn import linear_model

In [25]:
lm = linear_model.LinearRegression()

In [26]:
model = lm.fit(x_train, y_train)

In [27]:
prediction = lm.predict(test_data)

In [28]:
prediction

array([ 9548.53929375,  9124.74226874,  8171.03946063, ...,
       12251.95294813,  6881.3319641 ,  8152.71808126])

In [29]:
test_data.size

3270386

In [30]:
prediction.size

233599

In [31]:
linear_model_solution = test_data[['User_ID', 'Product_ID']]

In [32]:
linear_model_solution['Purchase'] = prediction

/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':

In [33]:
linear_model_solution

        User_ID  Product_ID      Purchase
0       1000004      128942   9548.539294
1       1000009      113442   9124.742269
2       1000010      288442   8171.039461
3       1000010      145342   8731.572138
4       1000011       53842   9775.200806
5       1000013      350442  10794.380403
6       1000013      155442  11188.806213
7       1000013       94542  10750.530040
8       1000015      161842   7901.240680
9       1000022       67942   8136.424788
10      1000026       46742  12131.007872
11      1000026       40042   8314.202963
12      1000026      196542   9995.026100
13      1000026        4542   8842.005282
14      1000028      159542   7760.765041
15      1000029      111542   9312.535103
16      1000033      121042   5565.681585
17      1000033      344442   9889.337115
18      1000034      265242   8023.254395
19      1000035       96642  10588.110226
20      1000036      303042   8586.262729
21      1000036       59642  11274.523618
22      1000042       30842  11889.011930
23      1000045      346442  10250.213078
24      1000045      357242   7093.664103
25      1000045      284742   7475.163160
26      1000048      110842  12016.906205
27      1000048      251642  11232.081717
28      1000053      136742  12503.981188
29      1000053       97342  12524.553716
...         ...         ...           ...
233569  1005996      184242   7647.139162
233570  1005996       45342  11898.637298
233571  1006001      124642   4337.605466
233572  1006002      121142   8266.493367
233573  1006002      233542  10413.313604
233574  1006002      226342   7569.303374
233575  1006002      284842  11861.501785
233576  1006003      313342   8400.750055
233577  1006010      223542  11887.078896
233578  1006013       20342   9647.622384
233579  1006016       14842  12556.099604
233580  1006016      109542  10719.493495
233581  1006018       71442   6021.702279
233582  1006021      112542  11209.332387
233583  1006021        3442  10192.895651
233584  1006023      262242  11148.522667
233585  1006025      161142   5721.284264
233586  1006026      110742  11559.836617
233587  1006028      162442   8550.173312
233588  1006030      129842   9838.386606
233589  1006030      241442   8966.948326
233590  1006032      252442   6755.200865
233591  1006033      127642  11584.112750
233592  1006035      135742   7964.061892
233593  1006036      255442   8118.594756
233594  1006036      118942   8392.150034
233595  1006036      254642   9428.739733
233596  1006036       31842  12251.952948
233597  1006037      124742   6881.331964
233598  1006039      316642   8152.718081

[233599 rows x 3 columns]

In [34]:
linear_model_solution.to_csv('LinearRegressionResult.csv')

In [35]:
train_data

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Category_Count,Product_Score,User_Score,Purchase
0,1000001,69042,0,0,10,0,2,0,3,0,0,1,0.120745,0.031707,8370
1,1000001,248942,0,0,10,0,2,0,1,6,14,3,0.309043,0.031707,15200
2,1000001,87842,0,0,10,0,2,0,12,0,0,1,0.054255,0.031707,1422
3,1000001,85442,0,0,10,0,2,0,12,14,0,2,0.181383,0.031707,1057
4,1000002,285442,1,6,16,2,4,0,8,0,0,1,0.107979,0.076917,7969
5,1000003,193542,1,2,15,0,3,0,1,2,0,2,0.327128,0.032423,15227
6,1000004,184942,1,4,7,1,2,1,1,8,17,3,0.765957,0.019595,19215
7,1000004,346142,1,4,7,1,2,1,1,15,0,2,0.315426,0.019595,15854
8,1000004,97242,1,4,7,1,2,1,1,16,0,2,0.485106,0.019595,15686
9,1000005,274942,1,2,20,0,1,1,8,0,0,1,0.421809,0.077917,7871
10,1000005,251242,1,2,20,0,1,1,5,11,0,2,0.631383,0.077917,5254
11,1000005,14542,1,2,20,0,1,1,8,0,0,1,0.357447,0.077917,3957
12,1000005,31342,1,2,20,0,1,1,8,0,0,1,0.019149,0.077917,6073
13,1000005,145042,1,2,20,0,1,1,1,2,5,3,0.747872,0.077917,15665
14,1000006,231342,0,5,9,0,1,0,5,8,14,3,0.044149,0.036057,5378
15,1000006,190242,0,5,9,0,1,0,4,5,0,2,0.101064,0.036057,2079
16,1000006,96642,0,5,9,0,1,0,2,3,4,3,0.092553,0.036057,13055
17,1000006,58442,0,5,9,0,1,0,5,14,0,2,0.293617,0.036057,8851
18,1000007,36842,1,3,1,1,1,1,1,14,16,3,0.470213,0.022271,11788
19,1000008,249542,1,2,12,2,4,1,1,5,15,3,0.417553,0.075600,19614
20,1000008,220442,1,2,12,2,4,1,5,14,0,2,0.681915,0.075600,8584
21,1000008,156442,1,2,12,2,4,1,8,0,0,1,0.444149,0.075600,9872
22,1000008,213742,1,2,12,2,4,1,8,0,0,1,0.186702,0.075600,9743
23,1000008,214442,1,2,12,2,4,1,8,0,0,1,0.267021,0.075600,5982
24,1000008,303442,1,2,12,2,4,1,1,8,14,3,0.189362,0.075600,11927
25,1000009,135742,1,2,17,2,0,0,6,8,0,2,0.218085,0.056383,16662
26,1000009,39942,1,2,17,2,0,0,8,0,0,1,0.088830,0.056383,5887
27,1000009,161442,1,2,17,2,0,0,5,14,0,2,0.267553,0.056383,6973
28,1000009,78742,1,2,17,2,0,0,5,8,14,3,0.150000,0.056383,5391
29,1000010,85942,0,3,1,1,4,1,2,4,8,3,0.512234,0.205896,16352
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
550038,1005995,375436,0,3,1,2,2,1,20,0,0,1,0.432979,0.096327,596
550039,1005996,371644,0,2,0,1,1,1,20,0,0,1,0.478191,0.286774,595
550040,1005997,370853,0,2,7,0,3,0,19,0,0,1,0.435106,0.038885,26
550041,1006000,371644,1,4,17,1,2,1,20,0,0,1,0.478191,0.225181,488
550042,1006002,371644,1,5,0,2,1,1,20,0,0,1,0.478191,0.174953,243
550043,1006003,370293,0,4,17,2,1,0,19,0,0,1,0.417553,0.152510,48
550044,1006004,370853,0,2,15,2,2,0,19,0,0,1,0.435106,0.030968,62
550045,1006005,371644,0,2,5,2,2,1,20,0,0,1,0.478191,0.035107,252
550046,1006006,375436,0,0,0,2,1,0,20,0,0,1,0.432979,0.048868,236
550047,1006009,372445,0,2,12,2,3,0,20,0,0,1,0.445213,0.026471,244
550048,1006010,371644,1,3,0,2,1,0,20,0,0,1,0.478191,0.183565,591
550049,1006011,375436,1,3,15,2,3,0,20,0,0,1,0.432979,0.113763,473
550050,1006012,371644,1,3,15,2,4,1,20,0,0,1,0.478191,0.012140,368
550051,1006013,375436,0,2,20,2,3,0,20,0,0,1,0.432979,0.059111,489
550052,1006016,375436,1,4,1,1,1,1,20,0,0,1,0.432979,0.357882,239
550053,1006017,371644,0,3,7,1,1,0,20,0,0,1,0.478191,0.015207,371
550054,1006018,370293,1,3,1,2,3,0,19,0,0,1,0.417553,0.092587,60
550055,1006019,372445,1,2,0,0,4,0,20,0,0,1,0.445213,0.057376,238
550056,1006022,375436,1,2,17,2,4,0,20,0,0,1,0.432979,0.026408,254
550057,1006023,370853,1,2,0,2,2,1,19,0,0,1,0.435106,0.115993,61
550058,1006024,372445,1,2,12,0,0,1,20,0,0,1,0.445213,0.078540,121
550059,1006025,370853,0,2,1,1,1,0,19,0,0,1,0.435106,0.098725,48
550060,1006026,371644,1,3,6,2,1,1,20,0,0,1,0.478191,0.046576,494
550061,1006029,372445,0,2,1,2,1,1,20,0,0,1,0.445213,0.014941,599
550062,1006032,372445,1,4,7,0,3,0,20,0,0,1,0.445213,0.049090,473
550063,1006033,372445,1,5,13,1,1,1,20,0,0,1,0.445213,0.047627,368
550064,1006035,375436,0,2,1,2,3,0,20,0,0,1,0.432979,0.090790,371
550065,1006036,375436,0,2,15,1,4,1,20,0,0,1,0.432979,0.390632,137
550066,1006038,375436,0,6,1,2,2,0,20,0,0,1,0.432979,0.008545,365
550067,1006039,371644,0,4,0,1,4,1,20,0,0,1,0.478191,0.056024,490

In [36]:
train_data.corr()

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Category_Count,Product_Score,User_Score,Purchase
User_ID,1.000000,-0.017619,-0.033474,0.032698,-0.023971,0.022859,-0.030737,0.020443,0.003825,0.003896,0.003605,0.004270,0.003688,-0.028524,0.004716
Product_ID,-0.017619,1.000000,0.021084,0.028892,0.009344,0.010162,-0.003162,0.013194,0.090193,-0.090600,-0.144360,-0.183299,-0.150652,-0.008751,-0.103961
Gender,-0.033474,0.021084,1.000000,-0.004262,0.117291,-0.004515,0.014660,-0.011603,-0.045594,-0.000954,0.036146,0.026808,0.020456,0.108409,0.060346
Age,0.032698,0.028892,-0.004262,1.000000,0.091463,0.123079,-0.004712,0.311738,0.061197,0.018770,-0.007422,-0.021246,-0.020741,-0.053110,0.015839
Occupation,-0.023971,0.009344,0.117291,0.091463,1.000000,0.034479,0.030005,0.024280,-0.007618,0.006712,0.012269,0.011600,0.011679,0.003933,0.020833
City_Category,0.022859,0.010162,-0.004515,0.123079,0.034479,1.000000,0.019946,0.039790,-0.014364,0.016003,0.035525,0.040739,0.109546,-0.502700,0.061914
Stay_In_Current_City_Years,-0.030737,-0.003162,0.014660,-0.004712,0.030005,0.019946,1.000000,-0.012819,-0.004213,0.001262,0.001977,0.002735,0.001470,-0.001142,0.005422
Marital_Status,0.020443,0.013194,-0.011603,0.311738,0.024280,0.039790,-0.012819,1.000000,0.019888,0.001099,-0.004629,-0.011257,-0.010415,-0.003875,-0.000463
Product_Category_1,0.003825,0.090193,-0.045594,0.061197,-0.007618,-0.014364,-0.004213,0.019888,1.000000,-0.067877,-0.385534,-0.518270,-0.205178,0.003524,-0.343703
Product_Category_2,0.003896,-0.090600,-0.000954,0.018770,0.006712,0.016003,0.001262,0.001099,-0.067877,1.000000,0.094750,0.444873,0.098062,-0.020652,0.052288
Product_Category_3,0.003605,-0.144360,0.036146,-0.007422,0.012269,0.035525,0.001977,-0.004629,-0.385534,0.094750,1.000000,0.791044,0.262332,-0.035989,0.288501
Category_Count,0.004270,-0.183299,0.026808,-0.021246,0.011600,0.040739,0.002735,-0.011257,-0.518270,0.444873,0.791044,1.000000,0.314808,-0.043950,0.323187
Product_Score,0.003688,-0.150652,0.020456,-0.020741,0.011679,0.109546,0.001470,-0.010415,-0.205178,0.098062,0.262332,0.314808,1.000000,-0.194668,0.308641
User_Score,-0.028524,-0.008751,0.108409,-0.053110,0.003933,-0.502700,-0.001142,-0.003875,0.003524,-0.020652,-0.035989,-0.043950,-0.194668,1.000000,-0.038439
Purchase,0.004716,-0.103961,0.060346,0.015839,0.020833,0.061914,0.005422,-0.000463,-0.343703,0.052288,0.288501,0.323187,0.308641,-0.038439,1.000000

In [37]:
from sklearn.linear_model import Ridge

In [38]:
ridgeReg = Ridge(alpha=0.05, normalize=True)

In [39]:
ridgeReg.fit(x_train, y_train)

Ridge(alpha=0.05, copy_X=True, fit_intercept=True, max_iter=None,
   normalize=True, random_state=None, solver='auto', tol=0.001)

In [40]:
ridgePrediction = ridgeReg.predict(test_data)

In [41]:
ridgePrediction

array([ 9496.39263831,  9120.60895591,  8206.22945701, ...,
       12201.3103221 ,  6970.12653767,  8158.05129572])

In [43]:
test_data['Purchase'] = ridgePrediction

In [44]:
test_data

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Category_Count,User_Score,Product_Score,Purchase
0,1000004,128942,1,4,7,1,2,1,1,11,0,2,0.019595,0.478890,9496.392638
1,1000009,113442,1,2,17,2,0,0,3,5,0,2,0.056383,0.141134,9120.608956
2,1000010,288442,0,3,1,1,4,1,5,14,0,2,0.205896,0.090470,8206.229457
3,1000010,145342,0,3,1,1,4,1,4,9,0,2,0.205896,0.009650,8754.667879
4,1000011,53842,0,2,1,2,1,0,4,5,12,3,0.052864,0.258142,9798.788386
5,1000013,350442,1,4,1,2,3,1,2,3,15,3,0.067755,0.142340,10783.621381
6,1000013,155442,1,4,1,2,3,1,1,11,15,3,0.067755,0.214717,11177.852125
7,1000013,94542,1,4,1,2,3,1,2,4,9,3,0.067755,0.082027,10739.720615
8,1000015,161842,1,2,7,0,1,0,10,13,16,3,0.099434,0.050663,8075.283571
9,1000022,67942,1,1,15,0,4,0,5,14,0,2,0.121470,0.183353,8202.479037
10,1000026,46742,1,2,7,1,2,1,1,2,15,3,0.152433,0.779252,12027.590780
11,1000026,40042,1,2,7,1,2,1,5,0,0,1,0.152433,0.059107,8338.231170
12,1000026,196542,1,2,7,1,2,1,5,8,14,3,0.152433,0.212304,10040.449517
13,1000026,4542,1,2,7,1,2,1,5,8,0,2,0.152433,0.155609,8868.601419
14,1000028,159542,0,2,1,2,2,1,10,15,16,3,0.049024,0.242461,7906.018853
15,1000029,111542,1,3,7,2,1,0,2,17,0,2,0.066073,0.255730,9296.134352
16,1000033,121042,1,4,3,0,1,1,15,0,0,1,0.184154,0.121834,5693.172456
17,1000033,344442,1,4,3,0,1,1,5,8,14,3,0.184154,0.162847,9929.692979
18,1000034,265242,0,1,0,0,0,0,5,8,0,2,0.076681,1.000000,7965.587929
19,1000035,96642,1,4,1,2,4,1,2,3,4,3,0.077945,0.094089,10557.939132
20,1000036,303042,1,2,3,1,0,0,5,0,0,1,0.219853,0.334138,8539.959677
21,1000036,59642,1,2,3,1,0,0,1,2,3,3,0.219853,0.184560,11207.241274
22,1000042,30842,1,2,8,2,0,1,1,2,15,3,0.140747,0.322075,11841.757794
23,1000045,346442,0,4,16,0,1,1,1,2,14,3,0.088118,0.124246,10267.427590
24,1000045,357242,0,4,16,0,1,1,5,0,0,1,0.088118,0.055489,7140.962940
25,1000045,284742,0,4,16,0,1,1,5,12,0,2,0.088118,0.069964,7548.652827
26,1000048,110842,1,2,4,1,3,1,1,2,5,3,0.264642,0.667069,11876.662122
27,1000048,251642,1,2,4,1,3,1,1,2,4,3,0.264642,0.120627,11171.563733
28,1000053,136742,1,2,0,1,1,0,1,14,16,3,0.405277,0.155609,12456.240796
29,1000053,97342,1,2,0,1,1,0,1,15,16,3,0.405277,0.149578,12480.807948
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
233569,1005996,184242,0,2,0,1,1,1,9,15,0,2,0.286774,0.234017,7699.614322
233570,1005996,45342,0,2,0,1,1,1,1,5,17,3,0.286774,0.174910,11871.440363
233571,1006001,124642,0,2,7,0,0,1,16,0,0,1,0.119326,0.173703,4512.885169
233572,1006002,121142,1,5,0,2,1,1,8,0,0,1,0.174953,0.178528,8251.037318
233573,1006002,233542,1,5,0,2,1,1,1,15,0,2,0.174953,0.323281,10322.795545
233574,1006002,226342,1,5,0,2,1,1,11,15,0,2,0.174953,0.316043,7604.977763
233575,1006002,284842,1,5,0,2,1,1,1,8,17,3,0.174953,0.095296,11823.270405
233576,1006003,313342,0,4,17,2,1,0,5,0,0,1,0.152510,0.313631,8346.223131
233577,1006010,223542,1,3,0,2,1,0,1,8,17,3,0.183565,0.208685,11841.662257
233578,1006013,20342,0,2,20,2,3,0,1,2,0,2,0.059111,0.186972,9610.042272
233579,1006016,14842,1,4,1,1,1,1,1,2,5,3,0.357882,0.235223,12435.092501
233580,1006016,109542,1,4,1,1,1,1,8,14,17,3,0.357882,0.243667,10744.915083
233581,1006018,71442,1,3,1,2,3,0,15,17,0,2,0.092587,0.404101,6133.350382
233582,1006021,112542,1,2,12,1,2,1,1,11,15,3,0.067330,0.595899,11175.837798
233583,1006021,3442,1,2,12,1,2,1,4,5,8,3,0.067330,0.469240,10184.367352
233584,1006023,262242,1,2,0,2,2,1,1,11,16,3,0.115993,0.211098,11142.861319
233585,1006025,161142,0,2,1,1,1,0,11,0,0,1,0.098725,0.013269,5836.823182
233586,1006026,110742,1,3,6,2,1,1,1,2,8,3,0.046576,0.820265,11428.075198
233587,1006028,162442,1,1,4,0,4,0,1,16,0,2,0.034448,0.118215,8596.453088
233588,1006030,129842,1,2,17,2,1,1,6,8,15,3,0.069979,0.287093,9889.523274
233589,1006030,241442,1,2,17,2,1,1,2,15,0,2,0.069979,0.065139,8987.799344
233590,1006032,252442,1,4,7,0,3,0,8,0,0,1,0.049090,0.107358,6818.708864
233591,1006033,127642,1,5,13,1,1,1,1,2,15,3,0.047627,0.437877,11526.195638
233592,1006035,135742,0,2,1,2,3,0,6,8,0,2,0.090790,0.184560,7992.582626
233593,1006036,255442,0,2,15,1,4,1,8,0,0,1,0.390632,0.009650,8132.611524
233594,1006036,118942,0,2,15,1,4,1,8,0,0,1,0.390632,0.090470,8395.177227
233595,1006036,254642,0,2,15,1,4,1,5,8,0,2,0.390632,0.083233,9410.977022
233596,1006036,31842,0,2,15,1,4,1,1,5,12,3,0.390632,0.094089,12201.310322
233597,1006037,124742,0,4,1,2,4,0,10,16,0,2,0.106249,0.102533,6970.126538
233598,1006039,316642,0,4,0,1,4,1,4,5,0,2,0.056024,0.200241,8158.051296

In [45]:
test_data.to_csv('RidgeResult.csv')

In [46]:
result_data = test_data[['User_ID', 'Product_ID', 'Purchase']]

In [47]:
result_data

        User_ID  Product_ID      Purchase
0       1000004      128942   9496.392638
1       1000009      113442   9120.608956
2       1000010      288442   8206.229457
3       1000010      145342   8754.667879
4       1000011       53842   9798.788386
5       1000013      350442  10783.621381
6       1000013      155442  11177.852125
7       1000013       94542  10739.720615
8       1000015      161842   8075.283571
9       1000022       67942   8202.479037
10      1000026       46742  12027.590780
11      1000026       40042   8338.231170
12      1000026      196542  10040.449517
13      1000026        4542   8868.601419
14      1000028      159542   7906.018853
15      1000029      111542   9296.134352
16      1000033      121042   5693.172456
17      1000033      344442   9929.692979
18      1000034      265242   7965.587929
19      1000035       96642  10557.939132
20      1000036      303042   8539.959677
21      1000036       59642  11207.241274
22      1000042       30842  11841.757794
23      1000045      346442  10267.427590
24      1000045      357242   7140.962940
25      1000045      284742   7548.652827
26      1000048      110842  11876.662122
27      1000048      251642  11171.563733
28      1000053      136742  12456.240796
29      1000053       97342  12480.807948
...         ...         ...           ...
233569  1005996      184242   7699.614322
233570  1005996       45342  11871.440363
233571  1006001      124642   4512.885169
233572  1006002      121142   8251.037318
233573  1006002      233542  10322.795545
233574  1006002      226342   7604.977763
233575  1006002      284842  11823.270405
233576  1006003      313342   8346.223131
233577  1006010      223542  11841.662257
233578  1006013       20342   9610.042272
233579  1006016       14842  12435.092501
233580  1006016      109542  10744.915083
233581  1006018       71442   6133.350382
233582  1006021      112542  11175.837798
233583  1006021        3442  10184.367352
233584  1006023      262242  11142.861319
233585  1006025      161142   5836.823182
233586  1006026      110742  11428.075198
233587  1006028      162442   8596.453088
233588  1006030      129842   9889.523274
233589  1006030      241442   8987.799344
233590  1006032      252442   6818.708864
233591  1006033      127642  11526.195638
233592  1006035      135742   7992.582626
233593  1006036      255442   8132.611524
233594  1006036      118942   8395.177227
233595  1006036      254642   9410.977022
233596  1006036       31842  12201.310322
233597  1006037      124742   6970.126538
233598  1006039      316642   8158.051296

[233599 rows x 3 columns]

In [48]:
result_data.to_csv('RidgeResult.csv')

In [49]:
from sklearn.linear_model import ElasticNet

In [50]:
eReg = ElasticNet(alpha=1, l1_ratio=0.5, normalize=False)

In [51]:
eReg.fit(x_train, y_train)

ElasticNet(alpha=1, copy_X=True, fit_intercept=True, l1_ratio=0.5,
      max_iter=1000, normalize=False, positive=False, precompute=False,
      random_state=None, selection='cyclic', tol=0.0001, warm_start=False)

In [53]:
test_data.drop(['Purchase'], axis=1)

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Category_Count,User_Score,Product_Score
0,1000004,128942,1,4,7,1,2,1,1,11,0,2,0.019595,0.478890
1,1000009,113442,1,2,17,2,0,0,3,5,0,2,0.056383,0.141134
2,1000010,288442,0,3,1,1,4,1,5,14,0,2,0.205896,0.090470
3,1000010,145342,0,3,1,1,4,1,4,9,0,2,0.205896,0.009650
4,1000011,53842,0,2,1,2,1,0,4,5,12,3,0.052864,0.258142
5,1000013,350442,1,4,1,2,3,1,2,3,15,3,0.067755,0.142340
6,1000013,155442,1,4,1,2,3,1,1,11,15,3,0.067755,0.214717
7,1000013,94542,1,4,1,2,3,1,2,4,9,3,0.067755,0.082027
8,1000015,161842,1,2,7,0,1,0,10,13,16,3,0.099434,0.050663
9,1000022,67942,1,1,15,0,4,0,5,14,0,2,0.121470,0.183353
10,1000026,46742,1,2,7,1,2,1,1,2,15,3,0.152433,0.779252
11,1000026,40042,1,2,7,1,2,1,5,0,0,1,0.152433,0.059107
12,1000026,196542,1,2,7,1,2,1,5,8,14,3,0.152433,0.212304
13,1000026,4542,1,2,7,1,2,1,5,8,0,2,0.152433,0.155609
14,1000028,159542,0,2,1,2,2,1,10,15,16,3,0.049024,0.242461
15,1000029,111542,1,3,7,2,1,0,2,17,0,2,0.066073,0.255730
16,1000033,121042,1,4,3,0,1,1,15,0,0,1,0.184154,0.121834
17,1000033,344442,1,4,3,0,1,1,5,8,14,3,0.184154,0.162847
18,1000034,265242,0,1,0,0,0,0,5,8,0,2,0.076681,1.000000
19,1000035,96642,1,4,1,2,4,1,2,3,4,3,0.077945,0.094089
20,1000036,303042,1,2,3,1,0,0,5,0,0,1,0.219853,0.334138
21,1000036,59642,1,2,3,1,0,0,1,2,3,3,0.219853,0.184560
22,1000042,30842,1,2,8,2,0,1,1,2,15,3,0.140747,0.322075
23,1000045,346442,0,4,16,0,1,1,1,2,14,3,0.088118,0.124246
24,1000045,357242,0,4,16,0,1,1,5,0,0,1,0.088118,0.055489
25,1000045,284742,0,4,16,0,1,1,5,12,0,2,0.088118,0.069964
26,1000048,110842,1,2,4,1,3,1,1,2,5,3,0.264642,0.667069
27,1000048,251642,1,2,4,1,3,1,1,2,4,3,0.264642,0.120627
28,1000053,136742,1,2,0,1,1,0,1,14,16,3,0.405277,0.155609
29,1000053,97342,1,2,0,1,1,0,1,15,16,3,0.405277,0.149578
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
233569,1005996,184242,0,2,0,1,1,1,9,15,0,2,0.286774,0.234017
233570,1005996,45342,0,2,0,1,1,1,1,5,17,3,0.286774,0.174910
233571,1006001,124642,0,2,7,0,0,1,16,0,0,1,0.119326,0.173703
233572,1006002,121142,1,5,0,2,1,1,8,0,0,1,0.174953,0.178528
233573,1006002,233542,1,5,0,2,1,1,1,15,0,2,0.174953,0.323281
233574,1006002,226342,1,5,0,2,1,1,11,15,0,2,0.174953,0.316043
233575,1006002,284842,1,5,0,2,1,1,1,8,17,3,0.174953,0.095296
233576,1006003,313342,0,4,17,2,1,0,5,0,0,1,0.152510,0.313631
233577,1006010,223542,1,3,0,2,1,0,1,8,17,3,0.183565,0.208685
233578,1006013,20342,0,2,20,2,3,0,1,2,0,2,0.059111,0.186972
233579,1006016,14842,1,4,1,1,1,1,1,2,5,3,0.357882,0.235223
233580,1006016,109542,1,4,1,1,1,1,8,14,17,3,0.357882,0.243667
233581,1006018,71442,1,3,1,2,3,0,15,17,0,2,0.092587,0.404101
233582,1006021,112542,1,2,12,1,2,1,1,11,15,3,0.067330,0.595899
233583,1006021,3442,1,2,12,1,2,1,4,5,8,3,0.067330,0.469240
233584,1006023,262242,1,2,0,2,2,1,1,11,16,3,0.115993,0.211098
233585,1006025,161142,0,2,1,1,1,0,11,0,0,1,0.098725,0.013269
233586,1006026,110742,1,3,6,2,1,1,1,2,8,3,0.046576,0.820265
233587,1006028,162442,1,1,4,0,4,0,1,16,0,2,0.034448,0.118215
233588,1006030,129842,1,2,17,2,1,1,6,8,15,3,0.069979,0.287093
233589,1006030,241442,1,2,17,2,1,1,2,15,0,2,0.069979,0.065139
233590,1006032,252442,1,4,7,0,3,0,8,0,0,1,0.049090,0.107358
233591,1006033,127642,1,5,13,1,1,1,1,2,15,3,0.047627,0.437877
233592,1006035,135742,0,2,1,2,3,0,6,8,0,2,0.090790,0.184560
233593,1006036,255442,0,2,15,1,4,1,8,0,0,1,0.390632,0.009650
233594,1006036,118942,0,2,15,1,4,1,8,0,0,1,0.390632,0.090470
233595,1006036,254642,0,2,15,1,4,1,5,8,0,2,0.390632,0.083233
233596,1006036,31842,0,2,15,1,4,1,1,5,12,3,0.390632,0.094089
233597,1006037,124742,0,4,1,2,4,0,10,16,0,2,0.106249,0.102533
233598,1006039,316642,0,4,0,1,4,1,4,5,0,2,0.056024,0.200241

In [55]:
test_data = test_data.drop(['Purchase'], axis=1)

In [56]:
elastic_result = eReg.predict(test_data)

In [57]:
elastic_result

array([10375.96586831,  9861.85327574,  8480.28384835, ...,
       12269.09658133,  7568.63027758,  8818.79362733])

In [58]:
test_data['Purchase'] = elastic_result

In [59]:
test_data

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Category_Count,User_Score,Product_Score,Purchase
0,1000004,128942,1,4,7,1,2,1,1,11,0,2,0.019595,0.478890,10375.965868
1,1000009,113442,1,2,17,2,0,0,3,5,0,2,0.056383,0.141134,9861.853276
2,1000010,288442,0,3,1,1,4,1,5,14,0,2,0.205896,0.090470,8480.283848
3,1000010,145342,0,3,1,1,4,1,4,9,0,2,0.205896,0.009650,9175.709292
4,1000011,53842,0,2,1,2,1,0,4,5,12,3,0.052864,0.258142,11070.662883
5,1000013,350442,1,4,1,2,3,1,2,3,15,3,0.067755,0.142340,11649.969751
6,1000013,155442,1,4,1,2,3,1,1,11,15,3,0.067755,0.214717,12472.122080
7,1000013,94542,1,4,1,2,3,1,2,4,9,3,0.067755,0.082027,11580.415447
8,1000015,161842,1,2,7,0,1,0,10,13,16,3,0.099434,0.050663,9212.857787
9,1000022,67942,1,1,15,0,4,0,5,14,0,2,0.121470,0.183353,8944.930747
10,1000026,46742,1,2,7,1,2,1,1,2,15,3,0.152433,0.779252,12476.743029
11,1000026,40042,1,2,7,1,2,1,5,0,0,1,0.152433,0.059107,8987.349526
12,1000026,196542,1,2,7,1,2,1,5,8,14,3,0.152433,0.212304,10684.021638
13,1000026,4542,1,2,7,1,2,1,5,8,0,2,0.152433,0.155609,9276.025348
14,1000028,159542,0,2,1,2,2,1,10,15,16,3,0.049024,0.242461,9339.593842
15,1000029,111542,1,3,7,2,1,0,2,17,0,2,0.066073,0.255730,10190.737679
16,1000033,121042,1,4,3,0,1,1,15,0,0,1,0.184154,0.121834,5517.054947
17,1000033,344442,1,4,3,0,1,1,5,8,14,3,0.184154,0.162847,10282.329826
18,1000034,265242,0,1,0,0,0,0,5,8,0,2,0.076681,1.000000,8095.087953
19,1000035,96642,1,4,1,2,4,1,2,3,4,3,0.077945,0.094089,10979.624812
20,1000036,303042,1,2,3,1,0,0,5,0,0,1,0.219853,0.334138,8279.715201
21,1000036,59642,1,2,3,1,0,0,1,2,3,3,0.219853,0.184560,10972.205230
22,1000042,30842,1,2,8,2,0,1,1,2,15,3,0.140747,0.322075,12681.282335
23,1000045,346442,0,4,16,0,1,1,1,2,14,3,0.088118,0.124246,11533.678987
24,1000045,357242,0,4,16,0,1,1,5,0,0,1,0.088118,0.055489,8107.343934
25,1000045,284742,0,4,16,0,1,1,5,12,0,2,0.088118,0.069964,8491.831074
26,1000048,110842,1,2,4,1,3,1,1,2,5,3,0.264642,0.667069,11118.007956
27,1000048,251642,1,2,4,1,3,1,1,2,4,3,0.264642,0.120627,10645.182708
28,1000053,136742,1,2,0,1,1,0,1,14,16,3,0.405277,0.155609,12396.768430
29,1000053,97342,1,2,0,1,1,0,1,15,16,3,0.405277,0.149578,12498.054247
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
233569,1005996,184242,0,2,0,1,1,1,9,15,0,2,0.286774,0.234017,7412.657966
233570,1005996,45342,0,2,0,1,1,1,1,5,17,3,0.286774,0.174910,12633.489721
233571,1006001,124642,0,2,7,0,0,1,16,0,0,1,0.119326,0.173703,4936.865737
233572,1006002,121142,1,5,0,2,1,1,8,0,0,1,0.174953,0.178528,8230.964160
233573,1006002,233542,1,5,0,2,1,1,1,15,0,2,0.174953,0.323281,10402.786920
233574,1006002,226342,1,5,0,2,1,1,11,15,0,2,0.174953,0.316043,7182.931303
233575,1006002,284842,1,5,0,2,1,1,1,8,17,3,0.174953,0.095296,12545.669061
233576,1006003,313342,0,4,17,2,1,0,5,0,0,1,0.152510,0.313631,8644.875832
233577,1006010,223542,1,3,0,2,1,0,1,8,17,3,0.183565,0.208685,12531.629004
233578,1006013,20342,0,2,20,2,3,0,1,2,0,2,0.059111,0.186972,10731.840089
233579,1006016,14842,1,4,1,1,1,1,1,2,5,3,0.357882,0.235223,11599.808467
233580,1006016,109542,1,4,1,1,1,1,8,14,17,3,0.357882,0.243667,10544.192511
233581,1006018,71442,1,3,1,2,3,0,15,17,0,2,0.092587,0.404101,6109.139075
233582,1006021,112542,1,2,12,1,2,1,1,11,15,3,0.067330,0.595899,12385.868806
233583,1006021,3442,1,2,12,1,2,1,4,5,8,3,0.067330,0.469240,10848.579266
233584,1006023,262242,1,2,0,2,2,1,1,11,16,3,0.115993,0.211098,12197.626046
233585,1006025,161142,0,2,1,1,1,0,11,0,0,1,0.098725,0.013269,6582.037234
233586,1006026,110742,1,3,6,2,1,1,1,2,8,3,0.046576,0.820265,11719.470358
233587,1006028,162442,1,1,4,0,4,0,1,16,0,2,0.034448,0.118215,9920.890658
233588,1006030,129842,1,2,17,2,1,1,6,8,15,3,0.069979,0.287093,10935.477850
233589,1006030,241442,1,2,17,2,1,1,2,15,0,2,0.069979,0.065139,9920.999668
233590,1006032,252442,1,4,7,0,3,0,8,0,0,1,0.049090,0.107358,7520.239948
233591,1006033,127642,1,5,13,1,1,1,1,2,15,3,0.047627,0.437877,12616.363823
233592,1006035,135742,0,2,1,2,3,0,6,8,0,2,0.090790,0.184560,8642.666398
233593,1006036,255442,0,2,15,1,4,1,8,0,0,1,0.390632,0.009650,7567.596082
233594,1006036,118942,0,2,15,1,4,1,8,0,0,1,0.390632,0.090470,7917.394961
233595,1006036,254642,0,2,15,1,4,1,5,8,0,2,0.390632,0.083233,8738.960899
233596,1006036,31842,0,2,15,1,4,1,1,5,12,3,0.390632,0.094089,12269.096581
233597,1006037,124742,0,4,1,2,4,0,10,16,0,2,0.106249,0.102533,7568.630278
233598,1006039,316642,0,4,0,1,4,1,4,5,0,2,0.056024,0.200241,8818.793627

In [60]:
test_data.to_csv('ElasticNetResult.csv')

In [61]:
elastic_csv = test_data[['User_ID', 'Product_ID', 'Purchase']]

In [62]:
elastic_csv

        User_ID  Product_ID      Purchase
0       1000004      128942  10375.965868
1       1000009      113442   9861.853276
2       1000010      288442   8480.283848
3       1000010      145342   9175.709292
4       1000011       53842  11070.662883
5       1000013      350442  11649.969751
6       1000013      155442  12472.122080
7       1000013       94542  11580.415447
8       1000015      161842   9212.857787
9       1000022       67942   8944.930747
10      1000026       46742  12476.743029
11      1000026       40042   8987.349526
12      1000026      196542  10684.021638
13      1000026        4542   9276.025348
14      1000028      159542   9339.593842
15      1000029      111542  10190.737679
16      1000033      121042   5517.054947
17      1000033      344442  10282.329826
18      1000034      265242   8095.087953
19      1000035       96642  10979.624812
20      1000036      303042   8279.715201
21      1000036       59642  10972.205230
22      1000042       30842  12681.282335
23      1000045      346442  11533.678987
24      1000045      357242   8107.343934
25      1000045      284742   8491.831074
26      1000048      110842  11118.007956
27      1000048      251642  10645.182708
28      1000053      136742  12396.768430
29      1000053       97342  12498.054247
...         ...         ...           ...
233569  1005996      184242   7412.657966
233570  1005996       45342  12633.489721
233571  1006001      124642   4936.865737
233572  1006002      121142   8230.964160
233573  1006002      233542  10402.786920
233574  1006002      226342   7182.931303
233575  1006002      284842  12545.669061
233576  1006003      313342   8644.875832
233577  1006010      223542  12531.629004
233578  1006013       20342  10731.840089
233579  1006016       14842  11599.808467
233580  1006016      109542  10544.192511
233581  1006018       71442   6109.139075
233582  1006021      112542  12385.868806
233583  1006021        3442  10848.579266
233584  1006023      262242  12197.626046
233585  1006025      161142   6582.037234
233586  1006026      110742  11719.470358
233587  1006028      162442   9920.890658
233588  1006030      129842  10935.477850
233589  1006030      241442   9920.999668
233590  1006032      252442   7520.239948
233591  1006033      127642  12616.363823
233592  1006035      135742   8642.666398
233593  1006036      255442   7567.596082
233594  1006036      118942   7917.394961
233595  1006036      254642   8738.960899
233596  1006036       31842  12269.096581
233597  1006037      124742   7568.630278
233598  1006039      316642   8818.793627

[233599 rows x 3 columns]

In [63]:
elastic_csv.to_csv('ElasticNetResult.csv')

In [64]:
test_data

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Category_Count,User_Score,Product_Score,Purchase
0,1000004,128942,1,4,7,1,2,1,1,11,0,2,0.019595,0.478890,10375.965868
1,1000009,113442,1,2,17,2,0,0,3,5,0,2,0.056383,0.141134,9861.853276
2,1000010,288442,0,3,1,1,4,1,5,14,0,2,0.205896,0.090470,8480.283848
3,1000010,145342,0,3,1,1,4,1,4,9,0,2,0.205896,0.009650,9175.709292
4,1000011,53842,0,2,1,2,1,0,4,5,12,3,0.052864,0.258142,11070.662883
5,1000013,350442,1,4,1,2,3,1,2,3,15,3,0.067755,0.142340,11649.969751
6,1000013,155442,1,4,1,2,3,1,1,11,15,3,0.067755,0.214717,12472.122080
7,1000013,94542,1,4,1,2,3,1,2,4,9,3,0.067755,0.082027,11580.415447
8,1000015,161842,1,2,7,0,1,0,10,13,16,3,0.099434,0.050663,9212.857787
9,1000022,67942,1,1,15,0,4,0,5,14,0,2,0.121470,0.183353,8944.930747
10,1000026,46742,1,2,7,1,2,1,1,2,15,3,0.152433,0.779252,12476.743029
11,1000026,40042,1,2,7,1,2,1,5,0,0,1,0.152433,0.059107,8987.349526
12,1000026,196542,1,2,7,1,2,1,5,8,14,3,0.152433,0.212304,10684.021638
13,1000026,4542,1,2,7,1,2,1,5,8,0,2,0.152433,0.155609,9276.025348
14,1000028,159542,0,2,1,2,2,1,10,15,16,3,0.049024,0.242461,9339.593842
15,1000029,111542,1,3,7,2,1,0,2,17,0,2,0.066073,0.255730,10190.737679
16,1000033,121042,1,4,3,0,1,1,15,0,0,1,0.184154,0.121834,5517.054947
17,1000033,344442,1,4,3,0,1,1,5,8,14,3,0.184154,0.162847,10282.329826
18,1000034,265242,0,1,0,0,0,0,5,8,0,2,0.076681,1.000000,8095.087953
19,1000035,96642,1,4,1,2,4,1,2,3,4,3,0.077945,0.094089,10979.624812
20,1000036,303042,1,2,3,1,0,0,5,0,0,1,0.219853,0.334138,8279.715201
21,1000036,59642,1,2,3,1,0,0,1,2,3,3,0.219853,0.184560,10972.205230
22,1000042,30842,1,2,8,2,0,1,1,2,15,3,0.140747,0.322075,12681.282335
23,1000045,346442,0,4,16,0,1,1,1,2,14,3,0.088118,0.124246,11533.678987
24,1000045,357242,0,4,16,0,1,1,5,0,0,1,0.088118,0.055489,8107.343934
25,1000045,284742,0,4,16,0,1,1,5,12,0,2,0.088118,0.069964,8491.831074
26,1000048,110842,1,2,4,1,3,1,1,2,5,3,0.264642,0.667069,11118.007956
27,1000048,251642,1,2,4,1,3,1,1,2,4,3,0.264642,0.120627,10645.182708
28,1000053,136742,1,2,0,1,1,0,1,14,16,3,0.405277,0.155609,12396.768430
29,1000053,97342,1,2,0,1,1,0,1,15,16,3,0.405277,0.149578,12498.054247
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
233569,1005996,184242,0,2,0,1,1,1,9,15,0,2,0.286774,0.234017,7412.657966
233570,1005996,45342,0,2,0,1,1,1,1,5,17,3,0.286774,0.174910,12633.489721
233571,1006001,124642,0,2,7,0,0,1,16,0,0,1,0.119326,0.173703,4936.865737
233572,1006002,121142,1,5,0,2,1,1,8,0,0,1,0.174953,0.178528,8230.964160
233573,1006002,233542,1,5,0,2,1,1,1,15,0,2,0.174953,0.323281,10402.786920
233574,1006002,226342,1,5,0,2,1,1,11,15,0,2,0.174953,0.316043,7182.931303
233575,1006002,284842,1,5,0,2,1,1,1,8,17,3,0.174953,0.095296,12545.669061
233576,1006003,313342,0,4,17,2,1,0,5,0,0,1,0.152510,0.313631,8644.875832
233577,1006010,223542,1,3,0,2,1,0,1,8,17,3,0.183565,0.208685,12531.629004
233578,1006013,20342,0,2,20,2,3,0,1,2,0,2,0.059111,0.186972,10731.840089
233579,1006016,14842,1,4,1,1,1,1,1,2,5,3,0.357882,0.235223,11599.808467
233580,1006016,109542,1,4,1,1,1,1,8,14,17,3,0.357882,0.243667,10544.192511
233581,1006018,71442,1,3,1,2,3,0,15,17,0,2,0.092587,0.404101,6109.139075
233582,1006021,112542,1,2,12,1,2,1,1,11,15,3,0.067330,0.595899,12385.868806
233583,1006021,3442,1,2,12,1,2,1,4,5,8,3,0.067330,0.469240,10848.579266
233584,1006023,262242,1,2,0,2,2,1,1,11,16,3,0.115993,0.211098,12197.626046
233585,1006025,161142,0,2,1,1,1,0,11,0,0,1,0.098725,0.013269,6582.037234
233586,1006026,110742,1,3,6,2,1,1,1,2,8,3,0.046576,0.820265,11719.470358
233587,1006028,162442,1,1,4,0,4,0,1,16,0,2,0.034448,0.118215,9920.890658
233588,1006030,129842,1,2,17,2,1,1,6,8,15,3,0.069979,0.287093,10935.477850
233589,1006030,241442,1,2,17,2,1,1,2,15,0,2,0.069979,0.065139,9920.999668
233590,1006032,252442,1,4,7,0,3,0,8,0,0,1,0.049090,0.107358,7520.239948
233591,1006033,127642,1,5,13,1,1,1,1,2,15,3,0.047627,0.437877,12616.363823
233592,1006035,135742,0,2,1,2,3,0,6,8,0,2,0.090790,0.184560,8642.666398
233593,1006036,255442,0,2,15,1,4,1,8,0,0,1,0.390632,0.009650,7567.596082
233594,1006036,118942,0,2,15,1,4,1,8,0,0,1,0.390632,0.090470,7917.394961
233595,1006036,254642,0,2,15,1,4,1,5,8,0,2,0.390632,0.083233,8738.960899
233596,1006036,31842,0,2,15,1,4,1,1,5,12,3,0.390632,0.094089,12269.096581
233597,1006037,124742,0,4,1,2,4,0,10,16,0,2,0.106249,0.102533,7568.630278
233598,1006039,316642,0,4,0,1,4,1,4,5,0,2,0.056024,0.200241,8818.793627

In [97]:
test_data = test_data.drop(['Purchase'], axis=1)

In [98]:
from sklearn.ensemble import ExtraTreesRegressor

In [99]:
eTreeReg = ExtraTreesRegressor(n_estimators=6)

In [100]:
eTreeReg.fit(x_train, y_train)

ExtraTreesRegressor(bootstrap=False, criterion='mse', max_depth=None,
          max_features='auto', max_leaf_nodes=None,
          min_impurity_decrease=0.0, min_impurity_split=None,
          min_samples_leaf=1, min_samples_split=2,
          min_weight_fraction_leaf=0.0, n_estimators=6, n_jobs=1,
          oob_score=False, random_state=None, verbose=0, warm_start=False)

In [101]:
eTreeResult = eTreeReg.predict(test_data)

In [102]:
eTreeResult

array([11785.33333333,  9625.33333333,  5058.33333333, ...,
       12289.5       , 18200.16666667,  2559.83333333])

In [103]:
test_data['Purchase'] = eTreeResult

In [104]:
e_tree_data = test_data[['User_ID', 'Product_ID', 'Purchase']]

In [105]:
e_tree_data

        User_ID  Product_ID      Purchase
0       1000004      128942  11785.333333
1       1000009      113442   9625.333333
2       1000010      288442   5058.333333
3       1000010      145342   2591.000000
4       1000011       53842   1889.166667
5       1000013      350442   9869.000000
6       1000013      155442   8627.000000
7       1000013       94542   8853.166667
8       1000015      161842  14345.500000
9       1000022       67942   5318.500000
10      1000026       46742  13519.666667
11      1000026       40042   5111.500000
12      1000026      196542   6197.166667
13      1000026        4542   5837.166667
14      1000028      159542  13008.166667
15      1000029      111542  12006.166667
16      1000033      121042  18444.666667
17      1000033      344442   5237.500000
18      1000034      265242   5820.000000
19      1000035       96642   9881.666667
20      1000036      303042   5865.333333
21      1000036       59642   9186.166667
22      1000042       30842  12547.166667
23      1000045      346442  11732.833333
24      1000045      357242   6711.666667
25      1000045      284742   8461.666667
26      1000048      110842  14574.666667
27      1000048      251642  11917.166667
28      1000053      136742  17332.000000
29      1000053       97342  14773.666667
...         ...         ...           ...
233569  1005996      184242  19244.666667
233570  1005996       45342  15424.000000
233571  1006001      124642  12377.666667
233572  1006002      121142   8709.333333
233573  1006002      233542  14287.000000
233574  1006002      226342   5758.833333
233575  1006002      284842  12808.166667
233576  1006003      313342   4955.500000
233577  1006010      223542  14760.500000
233578  1006013       20342  11824.500000
233579  1006016       14842  15545.833333
233580  1006016      109542   9180.333333
233581  1006018       71442  12768.333333
233582  1006021      112542  12442.833333
233583  1006021        3442   1309.500000
233584  1006023      262242  14482.500000
233585  1006025      161142   4004.666667
233586  1006026      110742  11254.666667
233587  1006028      162442   8050.666667
233588  1006030      129842  16934.333333
233589  1006030      241442  11629.833333
233590  1006032      252442   4435.333333
233591  1006033      127642  11710.166667
233592  1006035      135742  13538.500000
233593  1006036      255442   8677.333333
233594  1006036      118942   8566.833333
233595  1006036      254642   7063.000000
233596  1006036       31842  12289.500000
233597  1006037      124742  18200.166667
233598  1006039      316642   2559.833333

[233599 rows x 3 columns]

In [106]:
e_tree_data.to_csv('ExtraTressRegressor.csv')